apiVersion: oda.tmforum.org/v1beta4
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  componentMetadata:
    description: The billing account management component aims to provide all the
      needed functionalities to create, configure and modify billing accounts. BAM
      component has the goal to support and handle the following capabilities/ functionalities.
      Set-up/ creation of Billing account. Associate payment plan(s). Associate payment
      method(s) - optional. Account taxes/ fees exception management. Define account
      associations. Provide account balance details. Set-up Billing contacts. Set-up
      Billing preferences (e.g., bill cycle frequency, invoice media type, invoice
      template option, etc.)
    eTOMs:
    - 1.3.10_Customer_Bill_Payments_&_Receivables_Management_v23.0
    - 1.3.10.1_Manage_Customer_Billing_Account_v23.0
    functionalBlock: PartyManagement
    functionalFrameworkFunctions:
    - 77_Billing_Account_Information_Configuration_v23.0
    - 73_Billing_Account_Reporting_v23.0
    - 76_Billing_Account_Structure_Configuration_v23.0
    - 75_Billing_Accounts_Creation_v23.0
    - 248_Customer_Billing_Hierarchies_Management_v23.0
    id: TMFC024
    maintainers:
    - email: components@tmforum.org
      name: Redacted
      url: Redacted
    name: BillingAccountManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    publicationDate: 2024-11-18 00:00:00
    status: specified
    version: 2.0.0
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      id: TMF632
      name: party-management-api
      required: true
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      required: true
      resources:
      - PartyRole:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF670
      name: payment-method-management-api
      required: false
      resources:
      - paymentMethod:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF670_Payment_Method/4.0.0/swagger/TMF670_Payment_Method_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF676
      name: payment-management-api
      required: false
      resources:
      - payment:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF676_Payment/4.0.0/swagger/TMF676_Payment_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF701
      name: process-flow-management-api
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - PATCH
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      developerUI: not_defined
      id: TMF666
      implementation: not_defined
      name: account-management-api
      path: not_defined
      port: 8080
      required: true
      resources:
      - billingAccount:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      - billingCycleSpecification:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      - billFormat:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      - billPresentationMedia:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF666_Account/4.0.0/swagger/TMF666_Account_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      developerUI: not_defined
      id: TMF701
      implementation: not_defined
      name: process-flow-management-api
      path: not_defined
      port: 8080
      required: false
      resources:
      - processFlow:
        - GET
        - GET /id
        - POST
        - DELETE /id
      - taskFlow:
        - GET
        - GET /id
        - PATCH /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
  eventNotification:
    publishedEvents:
    - apiType: openapi
      id: TMF666
      implementation: /{{.Release.Name}}-accmngt
      name: AccountManagement
      port: 80
      resources:
      - billingAccountAttributeValueChangeEvent
      - billingAccountStateChangeEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF666_AccountManagement/master/TMF666-AccountManagement-v4.0.0.swagger.json
        version: v4.0.0
    subscribedEvents:
    - id: TMF669
      name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleCreateEvent
      - partyRoleAttributeValueChangeEvent
      - partyRoleStateChangeEvent
      - partyRoleDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
        version: v4.0.0
  managementFunction:
    dependentAPIs:
    - apiType: dependentAPI_apiType
      id: dependentAPI_id
      name: dependentAPI_name
      required: false
      resources: []
      specification:
      - url: dependentAPI_spec
        version: dependentAPI_version
      version: dependentAPI_version
    exposedAPIs:
    - apiType: prometheus
      developerUI: exposedAPI_developerUI
      id: exposedAPI_id
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
      required: false
      resources: []
      specification:
      - url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        version: v4.0.0
      version: exposedAPI_version
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    dependentAPIs: []
    exposedAPIs:
    - apiType: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      id: TMF669
      implementation: '{{.Release.Name}}-partyroleapi'
      name: party-role-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      required: true
      resources: []
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
