apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF632
      apiType: openapi
      apiSDO: tmForum
      name: party-management-api
      required: true
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
    - id: TMF669
      apiType: openapi
      apiSDO: tmForum
      name: party-role-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      resources:
      - partyRole:
        - GET
        - GET /id
    - id: TMF620
      apiType: openapi
      apiSDO: tmForum
      name: product-catalog-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF620_Product_Catalog/4.1.0/swagger/TMF620_Product_Catalog_Management_API_v4.1.0_swagger.json
        version: v4.0.0
      resources:
      - productOffering:
        - GET
        - GET /id
      - productOfferingPrice:
        - GET
        - GET /id
      - productSpecification:
        - GET
        - GET /id
    - id: TMF637
      apiType: openapi
      apiSDO: tmForum
      name: product-inventory-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF637_Product_Inventory/4.0.0/swagger/TMF637_Product_Inventory_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      resources:
      - product:
        - GET
        - GET /id
    - id: TMF701
      apiType: openapi
      apiSDO: tmForum
      name: process-flow-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - PATCH
    exposedAPIs:
    - id: TMF635
      apiType: openapi
      apiSDO: tmForum
      name: usage-management-api
      required: true
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF635_Usage/4.0.0/swagger/TMF635_Usage_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      path: not_defined
      developerUI: not_defined
      implementation: not_defined
      port: 8080
      resources:
      - usage:
        - GET
        - GET/id
        - POST
        - PATCH/id
    - id: TMF677
      apiType: openapi
      apiSDO: tmForum
      name: usage-consumption-management-api
      required: true
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF677_Usage_Consumption/4.0.0/swagger/TMF677_Usage_Consumption_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      path: not_defined
      developerUI: not_defined
      implementation: not_defined
      port: 8080
      resources:
      - queryUsageConsumption:
        - GET
        - GET/id
        - POST
    - id: TMF701
      apiType: openapi
      apiSDO: tmForum
      name: process-flow-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
      path: not_defined
      developerUI: not_defined
      implementation: not_defined
      port: 8080
      resources:
      - processFlow:
        - GET
        - GET /id
        - POST
        - DELETE /id
      - taskFlow:
        - GET
        - GET /id
        - PATCH /id
  componentMetadata:
    id: TMFC040
    name: ProductUsageManagement
    version: 1.1.0
    description: Product Usage Management component provides a standardized mechanism
      for creation, update, retrieval, import and export of a collection of usages.
      It allows a service provider to retrieve usage generated by a partner service
      platform in order to rate it, and provides rated usage to a partner for consumption
      follow-up purposes.
    publicationDate: 2024-10-22
    status: specified
    functionalBlock: CoreCommerce
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.2.16|Product_Usage_Management|v23.0
    - 1.2.16.1|Product_Usages|v23.0
    - 1.2.16.1.1|Add_Product_Usage_Data|v23.0
    - 1.2.16.1.2|Assign_Product_Usage_Price|v23.0
    - 1.2.16.2|Guide_and_Assign_Product_Usages|v23.0
    - 1.2.16.2.1|Assign_Product_Usages|v23.0
    - 1.2.16.2.2|Distribute_Product_Usage|v23.0
    - 1.2.16.2.3|Guide_Product_Usages|v23.0
    - 1.2.16.3|Mediate_Product_Usages|v23.0
    - 1.2.16.3.1|Edit_Product_Usages|v23.0
    - 1.2.16.3.2|Reformat_Product_Usages|v23.0
    - 1.2.16.4|Report_Product_Usage_Records|v23.0
    - 1.2.16.4.1|Generate_Product_Usage_Report|v23.0
    - 1.2.16.4.2|Investigate_Product_Usage_Related_Problem|v23.0
    - 1.2.16.4.3|Support_Product_Usage_Related_Process|v23.0
    - 1.2.17|Product_Rating_&_Rate_Assignment|v23.0
    - 1.2.17.1|Perform_Rating|v23.0
    - 1.2.17.2|Aggregate_Items_For_Rate_Assignment|v23.0
    - 1.2.17.3|Manage_Customer_Assignment_Hierarchy|v23.0
    - 1.2.17.4|Provide_Advice_of_Rate|v23.0
    - 1.2.17.5|Apply_Rate_Level_Discounts|v23.0
    functionalFrameworkFunctions:
    - 253|Customer_Usage_and_Charges_Report_Access|v23.0
    - 55|Price_and_Discount_Calculation|v23.0
    - 125|Charging_Event_Accumulation|v23.0
    - 126|Event_Charge/Credit_Calculation|v23.0
    - 127|Calculated_Charges/Credits_Proration|v23.0
    - 128|Late_Arrival_Usage_Charges/Credits_Recalculation|v23.0
    - 186|Charging/Rating_Recalculation|v23.0
    - 300|Discounts_Calculation|v23.0
    - 67|Usage_Summary_and_Details_Presentation|v23.0
    - 85|Billing_Event_Processing_Distribution|v23.0
    - 86|Billing_Event_Processing_Enrichment|v23.0
    SIDs:
    - Product_Domain|Product_Usage_ABE|v25.0
    - Product_Domain|Product_Offering_Instance_ABE|Product_Price_ABE|v25.0
  managementFunction:
    exposedAPIs:
    - name: metrics
      apiType: prometheus
      apiSDO: not_defined
      specification:
      - url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        version: v4.0.0
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
      id: exposedAPI_id
      version: exposedAPI_version
      resources: []
      required: false
      developerUI: exposedAPI_developerUI
    dependentAPIs:
    - name: dependentAPI_name
      id: dependentAPI_id
      version: dependentAPI_version
      apiType: dependentAPI_apiType
      apiSDO: dependentAPI_apiSDO
      specification:
      - url: dependentAPI_spec
        version: dependentAPI_version
      resources: []
      required: false
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - id: TMF669
      apiType: openapi
      apiSDO: not_defined
      name: party-role-management-api
      required: true
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      implementation: '{{.Release.Name}}-partyroleapi'
      port: 8080
      resources: []
    dependentAPIs: []
  eventNotification:
    publishedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UsageConsumption/hub
      name: UsageConsumption
      port: 80
      resources:
      - queryUsageConsumptionCreateEvent
      - queryUsageConsumptionDeleteEvent
      - queryUsageConsumptionStateChangeEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF677_UsageConsumption/blob/master/TMF677-UsageConsumption-v4.0.1.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF677
      apiSDO: not_defined
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/usageManagement/hub
      name: UsageManagement
      port: 80
      resources:
      - usageCreateEvent
      - usageAttributeValueChangeEvent
      - usageDeleteEvent
      - usageStateChangeEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF635_UsageManagement/blob/master/TMF635-UsageManagement-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF635
      apiSDO: not_defined
    subscribedEvents:
    - name: Party
      port: 80
      resources:
      - individualDeleteEvent
      - organizationDeleteEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF632
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/party/call-back
      apiSDO: not_defined
    - name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleCreateEvent
      - partyRoleAttributeValueChangeEvent
      - partyRoleStateChangeEvent
      - partyRoleDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF669
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/partyrole/call-back
      apiSDO: not_defined
