apiVersion: oda.tmforum.org/v1beta1
kind: component
metadata:
  name: TMFC020-agreementManagement
  labels:
    oda.tmforum.org/componentName: TMFC020-agreementManagement
    oda.tmforum.org/funtionalBlockName: PartyManagement
spec:
  type: TMFC020-agreementManagement
  version: 1.1.0
  description: >-
    Agreement Management ODA-Component specification, from Open-API reference
    implementation.
  maintainers:
    - name: Gaetano Biancardi
      email: gaetano.biancardi@accenture.com
  owners:
    - name: Gaetano Biancardi
      email: gaetano.biancardi@accenture.com
coreFunction:
  exposedAPIs:
    - name: AgreementManagement
      id: TMF651
      isRequired: 'yes'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF651_AgreementManagement/master/TMF651-AgreementManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}- agreemngtapi'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AgreementManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AgreementManagement/v4/docs
      port: 8080
      resources:
        - agreement:
            - GET
            - GET/id
            - POST
            - PATCH/id
            - DELETE/id
        - agreementSpecification:
            - GET
            - GET/id
            - POST
            - PATCH/id
            - DELETE/id
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: not
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlowManagement/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-procflowapi'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
      port: 8080
      resources: null
      processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      taskFlow:
        - PATCH
        - GET
        - GET /id
    - name: Event
      id: TMF688
      isRequired: not
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-PromotionManagement'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      port: 8080
      resources:
        - event:
            - GET
            - GET /id
            - POST
            - PATCH
            - DELETE
  dependantAPIs:
    - name: PartyManagement
      id: TMF632
      isRequired: 'yes'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - individual:
            - GET
            - GET/id
        - organization:
            - GET
            - GET/id
    - name: UserRolesandPermissions
      id: TMF672
      isRequired: 'yes'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRolesandPermissions/master/TMF672-UserRolesandPermissions-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - permission:
            - GET
            - GET/id
        - userRole:
            - GET
            - GET/id
    - name: PartyRoleManagement
      id: TMF669
      isRequired: 'yes'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRoleManagement/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - partyRole:
            - GET
            - GET/id
    - name: ProductCatalogManagement
      id: TMF620
      isRequired: 'no'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalogManagement/master/TMF620-ProductCatalogManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - productOffering:
            - GET
            - GET/id
        - productOfferingPrice:
            - GET
            - GET/id
    - name: ProductInventory
      id: TMF637
      isRequired: 'no'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF637_ProductInventory/master/TMF620-ProductInventory-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - product:
            - GET
            - GET/id
    - name: DocumentManagement
      id: TMF667
      isRequired: 'no'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF667_DocumentManagement/master/TMF667-DocumentManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - document:
            - GET
            - GET/id
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: not
      version: 4
      specification: >-
        ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - processFlow:
            - POST
            - GET
            - GET /id
            - DELETE
        - taskFlow:
            - PATCH
            - GET
            - GET /id
    - name: Event
      id: TMF688
      isRequired: not
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - event:
            - GET
            - GET /id
  publishedEvents:
    - name: userRole
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF651_AgreementManagement/master/TMF651-AgreementManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-agreemngtapi'
      apitype: openapi
      port: 80
      resources:
        agreement:
          - agreementCreateEvent
          - agreementAttributeValueChangeEvent
          - agreementStateChangeEvent
          - agreementSpecificationCreateEvent
          - agreementSpecificationAttributeValueChangeEvent
  subscribedEvents:
    - name: PartyManagement
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-PartyManagement'
      apitype: openapi
      port: 80
      resources: party - individualDeleteEvent - organizationDeleteEvent
management: []
reporting: []
security: []
