apiVersion: oda.tmforum.org/v1alpha1
kind: component
metadata:
  labels:
    oda.tmforum.org/componentName: Billing Account Management
    oda.tmforum.org/funtionalBlockName: Party Management
    name: TAG_REALESE_NAME - Billing Account Management
spec:
  componentKinds:
    - group: core
      kind: Inventory
  coreFunction:
    exposedAPIs:
      - name: AccountManagement
        specification: https://github.com/tmforum-apis/TMF666_AccountManagement/blob/main/TMF666-AccountManagement-v4.0.0.swagger.json
        required: true
        implementation: /{{.Release.Name}}-AccountManagement
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AccountManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AccountManagement/v4/docs
        port: 8080
      - name: ProcessFlowManagement
        specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-ProcessFlowManagement
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/processFlowManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/processFlowManagement/v4/docs
        port: 8080
      - name: Event
        specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-EventManagement-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-EventManagement
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4/docs
        port: 8080    
    dependantAPIs:
      - name: PartyRoleManagement
        specification: https://github.com/tmforum-apis/TMF669_PartyRole/blob/master/TMF669-PartyRole-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-PartyRoleManagement
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/v4/docs
        port: 8080
      - name: UserRoles&Permissions
        specification: https://github.com/tmforum-apis/TMF672-UserRoles&Permissions/blob/master/TMF672-UserRoles&Permissions-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-UserRoles&Permissions
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRoles&Permissions/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRoles&Permissions/v4/docs
        port: 8080
      - name: PaymentMethodManagement
        specification: https://github.com/tmforum-apis/TMF670-PaymentMethodManagement/blob/master/TMF670-PaymentMethodManagement-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-PaymentMethodManagement
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PaymentMethodManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PaymentMethodManagement/v4/docs
        port: 8080
      - name: ProcessFlowManagement
        specification: https://github.com/tmforum-apis/TMF701-ProcessFlowManagement/blob/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-ProcessFlowManagement
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
        port: 8080      
      - name: EventManagement
        specification: https://github.com/tmforum-apis/TMF688-EventManagement/blob/master/TMF688-EventManagement-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-EventManagement
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4/docs
        port: 8080
    managementAPIs:
  eventNotification:
    PublishedEvent:
        Account:
        - partyAccountAttributeValueChangeEvent
        - partyAccountStateChangeEvent
        - billingAccountAttributeValueChangeEvent
        - billingAccountStateChangeEvent
        - settlementAccountAttributeValueChangeEvent
        - settlementAccountStateChangeEvent
        - financialAccountCreateEvent
        - financialAccountAttributeValueChangeEvent
        - financialAccountStateChangeEvent
        - financialAccountDeleteEvent
    SubscribedEvent:
       PartyRole:
        - partyRoleCreateEvent
        - partyRoleAttributeValueChangeEvent
        - partyRoleStateChangeEvent
        - partyRoleDeleteEvent
        - UserRoleChangeNotification
       UserRolePermission:
        - permissionCreateEvent
        - permissionAttributeValueChangeEvent
        - permissionStateChangeEvent
        - permissionDeleteEvent
        - userRoleCreateEvent
        - userRoleAttributeValueChangeEvent
        - userRoleStateChangeEvent
        - userRoleDeleteEvent
  maintainers:
    - email: matteo.destino@accenture.com
      name: Matteo Destino
  management: []
  owners:
    - email: matteo.destino@accenture.com
      name: Matteo Destino
  security:
    securitySchemes: 
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  selector:
    matchLabels:
      oda.tmforum.org/componentName: Billing Account Management
  type: Party Management
  version: 1.1.0
