apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    exposedAPIs:
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
  componentMetadata:
    id: TMFC031
    name: BillCalculation
    version: 2.0.0
    description: The Bill Calculation component processes all charges against billing
      accounts during bill cycles. Bill Calculation can be executed both on a cyclic
      basis and on demand. It performs calculations with bill compilation of charges,
      credits, fees & taxes, including pro rata, at various levels, such as product
      and/or account level that have been generated since the last run for that account,
      applying promotions and discounts.
    publicationDate: 2023-06-25
    status: specified
    functionalBlock: CoreCommerce
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs: []
    functionalFrameworkFunctions: []
  managementFunction:
    exposedAPIs:
    - name: metrics
      apiType: prometheus
      apiSDO: not_defined
      specification:
      - url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        version: v4.0.0
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
      id: exposedAPI_id
      version: exposedAPI_version
      resources: []
      required: false
      developerUI: exposedAPI_developerUI
    dependentAPIs:
    - name: dependentAPI_name
      id: dependentAPI_id
      version: dependentAPI_version
      apiType: dependentAPI_apiType
      apiSDO: dependentAPI_apiSDO
      specification:
      - url: dependentAPI_spec
        version: dependentAPI_version
      resources: []
      required: false
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - array_id: null
      minItems: null
      apis: []
    dependentAPIs:
    - array_id: null
      minItems: null
      apis: []
  eventNotification:
    publishedEvents: []
    subscribedEvents:
    - name: usageManagement
      port: 80
      resources:
      - UsageCreateEvent
      - UsageAttributeValueChangeEvent
      - UsageDeleteEvent
      - UsageStateChangeEvent
      - UsageSpecificationCreateEvent
      - UsageSpecificationAttributeValueChangeEvent
      - UsageSpecificationDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF635_UsageManagement/blob/master/TMF635-UsageManagement-v4.0.0.swagger.json
        version: v4.0.0
      id: TMF635
      apiSDO: not_defined
