component:
  id: tmfc022
  name: tmfc022-partyprivacymanagement
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf644: tmforumorg/tmfc022-tmf644-v4.0.0:latest
  tmf669: tmforumorg/tmfc022-tmf669-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
