apiVersion: oda.tmforum.org/v1beta4
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  componentMetadata:
    description: 'Party Management component is responsible for the capture, validation
      and management of Parties and their Roles. A Party may be an individual or organization
      that has a relationship with an enterprise. In this context it is responsible
      for the e2e life cycle of: Individual, Organization. and its related sub-entities:Contact
      Medium, Currency and tax exemption certificates, Identification, Community'
    eTOMs:
    - 1.3.16_Customer_Inventory_Management_v23.0
    - 1.3.6_Customer_Information_Management_v23.0
    - 1.3.4_Customer_Relationship_Management_v23.0
    - 1.3.4.2_Establish_Customer_Relationship_v23.0
    - 1.3.4.3_Re-establish_Customer_Relationship_v23.0
    - 1.3.4.4_Terminate_Customer_Relationship_v23.0
    - 1.6.3_Party_Relationship_Development_&_Retirement_v23.0
    - 1.6.3.1_Party_Relationship_Management_v23.0
    - 1.6.3.1.5_Collect_Party_data_v23.0
    - 1.6.21_Party_Inventory_Management_v23.0
    - 1.7.7_Human_Resources_Management_v23.0
    - 1.7.7.2_Develop_the_Workforce_v23.0
    functionalBlock: PartyManagement
    functionalFrameworkFunctions:
    - 92_Customer_Relation_Map_Exposure_v23.0
    - 369_Customer_Data_Fencing_v23.0
    - 225_Customer_Details_Management_v23.0
    - 400_Customer_Information_Management_v23.0
    - 282_Customer_Information_Presentation_v23.0
    - 226_Customer_Preferences_Administration_v23.0
    - 364_Customer/Prospect_Data_Acquisition_v23.0
    - 233_Customer_Actions_Profile_Updating_v23.0
    - 195_Customers_Hierarchy_and_Group_Management_v23.0
    - 122_Customer_Information_Searching_v23.0
    - 91_Customer_Profile_Updating_v23.0
    - 121_Registration_v23.0
    - 124_Guided_Customer_Information_Capturing_v23.0
    - 1032_Partner_Group_and_Hierarchy_Definition_v23.0
    - 1033_Partner_Group_and_Hierarchy_Assigning_v23.0
    - 1035_Partner_Preferences_Management_v23.0
    - 1034_Partner_Profile_Management_v23.0
    - 1036_Partner_Profile_Enquiry_and_Filtering_v23.0
    - 1037_Partner_Profile_Storage_v23.0
    - 746_Partner_Workflow_Management_v23.0
    id: TMFC028
    maintainers:
    - email: components@tmforum.org
      name: Redacted
      url: Redacted
    name: PartyManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    publicationDate: 2024-10-14 00:00:00
    status: specified
    version: 2.1.0
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      required: true
      resources:
      - partyRole:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF673
      name: geographic-address-management-api
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF673_Geographic_Address/4.0.0/swagger/TMF673_Geographic_Address_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF674
      name: geographic-site-management-api
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF674_Geographic_Site/4.0.0/swagger/TMF674_Geographic_Site_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF675
      name: geographic-location-management-api
      required: false
      resources:
      - geographicLocation:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF675_Geographic_Location/4.0.0/swagger/TMF675_Geographic_Location_Management_API_v4.0.0_beta_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF701
      name: process-flow-management-api
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF688
      name: event-management-api
      required: false
      resources:
      - event:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF688_Event/4.0.0/swagger/TMF688_Event_Management_API_v4.0.0_beta_swagger.json
        version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      developerUI: not_defined
      id: TMF632
      implementation: not_defined
      name: party-management-api
      path: not_defined
      port: 8080
      required: true
      resources:
      - individual:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
      - organization:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      developerUI: not_defined
      id: TMF701
      implementation: not_defined
      name: process-flow-management-api
      path: not_defined
      port: 8080
      required: false
      resources:
      - processFlow:
        - GET
        - GET/id
        - POST
        - DELETE/id
      - taskFlow:
        - GET
        - GET/id
        - PATCH/id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
  eventNotification:
    publishedEvents:
    - apiType: openapi
      id: TMF632
      implementation: /{{.Release.Name}}-partymngtapi
      name: Party Management API
      port: 80
      resources:
      - IndividualCreateEvent
      - IndividualAttributeValueChangeEvent
      - IndividualStateChangeEvent
      - IndividualDeleteEvent
      - OrganizationCreateEvent
      - OrganizationAttributeValueChangeEvent
      - OrganizationStateChangeEvent
      - OrganizationDeleteEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
        version: v4.0.0
    subscribedEvents: []
  managementFunction:
    dependentAPIs:
    - apiType: dependentAPI_apiType
      id: dependentAPI_id
      name: dependentAPI_name
      required: false
      resources: []
      specification:
      - url: dependentAPI_spec
        version: dependentAPI_version
      version: dependentAPI_version
    exposedAPIs:
    - apiType: prometheus
      developerUI: exposedAPI_developerUI
      id: exposedAPI_id
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
      required: false
      resources: []
      specification:
      - url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        version: v4.0.0
      version: exposedAPI_version
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    dependentAPIs: []
    exposedAPIs:
    - apiType: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      id: TMF669
      implementation: '{{.Release.Name}}-partyroleapi'
      name: party-role-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      required: true
      resources: []
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
