apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Release.Name}}-productrecommendationmanagementinitialization
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-productrecommendationmanagementinitialization
    spec:
      containers:
      - name: {{.Release.Name}}-productrecommendationmanagementinitialization
        image: akumartmf/productrecommendationmanagementinitialization:0.2
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name}}
        - name: COMPONENT_NAME
          value: {{.Release.Name}}-{{.Values.component.name}}
        imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 10
