apiVersion: oda.tmforum.org/v1beta3
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      id: TMF702
      name: resource-activation-management-api
      port: 8080
      required: true
      resources:
      - resource:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - monitor:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF702_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF634
      name: resource-catalog-management-api
      port: 8080
      required: true
      resources:
      - resourceSpecification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF634_v4.1.0.swagger.json
      version: v4.1.0
    - apiType: openapi
      id: TMF639
      name: resource-inventory-management-api
      port: 8080
      required: true
      resources:
      - resource:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF639_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF664
      name: resource-function-activation-management-api
      port: 8080
      required: true
      resources:
      - resourceFunction:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF664_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF632
      name: party-management-api
      port: 8080
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF646
      name: appointment-management-api
      port: 8080
      required: false
      resources:
      - workOrder:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF646_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF673
      name: geographic-address-management-api
      port: 8080
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF673_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF674
      name: geographic-site-management-api
      port: 8080
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF674_v4.0.0.swagger.json
      version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      id: TMF652
      name: resource-order-management-api
      port: 8080
      required: true
      resources:
      - resourceOrder:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - cancelResourceOrder:
        - GET
        - GET /id
        - POST
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF652_v4.0.0.swagger.json
      version: v4.0.0
  description: Resource Order Management Component manages the end-to-end lifecycle
    of a resource  order request. This includes validating resource availability as
    well as the  resource order request. Other functionality includes resource order
    assurance,  resource order decomposition and resource order tracking, along with
    orchestrating  the activation and the test and turn-up processes.
  eventNotification:
    publishedEvents:
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/resourceOrderingManagement/hub
      id: TMF652
      implementation: /{{.Release.Name}}-ResourceOrderingManagementEvent
      name: ResourceOrderingManagement
      port: 80
      resources:
      - CancelResourceOrderInformationRequiredEvent
      - CancelResourceOrderInformationRequiredEventPayload
      - CancelResourceOrderStateChangeEvent
      - CancelResourceOrderStateChangeEventPayload
      - ResourceOrderAttributeValueChangeEvent
      - ResourceOrderAttributeValueChangeEventPayload
      - ResourceOrderCreateEvent
      - ResourceOrderCreateEventPayload
      - ResourceOrderDeleteEvent
      - ResourceOrderDeleteEventPayload
      - ResourceOrderInformationRequiredEvent
      - ResourceOrderInformationRequiredEventPayload
      - ResourceOrderStateChangeEvent
      - ResourceOrderStateChangeEventPayload
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF652-ResourceOrder-v4.0.0.swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      id: TMF701
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
    subscribedEvents:
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceFunctionActivationConfiguration/call-back
      id: TMF664
      implementation: /{{.Release.Name}}-ResourceFunctionActivationConfiguration
      name: ResourceFunctionActivationConfiguration
      port: 80
      resources:
      - resourceFunctionCreateEvent
      - resourceFunctionChangeEvent
      - monitorStatechangeEvent
      - healStatechangeEvent
      - scaleStatechangeEvent
      - migrateStatechangeEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF664_ResourceFunctionActivationConfiguration/master/TMF664-ResourceFunctionActivationConfiguration-v4.0.0.swagger.json
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceActivationAndConfiguration/call-back
      id: TMF702
      implementation: /{{.Release.Name}}-ResourceActivationAndConfiguration
      name: ResourceActivationAndConfiguration
      port: 80
      resources:
      - resourceChangeEvent
      - monitorCreateEvent
      - monitorStatechangeEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF702_ResourceActivation/master/TMF702-ResourceActivation-v4.0.0.swagger.json
  functionalBlock: Production
  id: TMFC011
  managementFunction:
    exposedAPIs:
    - apiType: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  name: ResourceOrderManagement
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  publicationDate: null
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    dependentAPIs: []
    exposedAPIs:
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      port: 8080
      required: true
      resources: []
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
  status: Pre-production
  version: 1.1.0
