component:
  id: tmfc040
  name: tmfc040-productusagemanagement
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf635: tmforumorg/tmfc040-tmf635-v4.0.0:latest
  tmf669: tmforumorg/tmfc040-tmf669-v4.0.0:latest
  tmf677: tmforumorg/tmfc040-tmf677-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
