component:
  id: TMFC054
  name: producttestmanagement
  functionalBlock: Production
  publicationDate: 2026-06-30T00:00:00.000Z
  version: "1.0.0"
  storageClassName: default
  apipolicy:
    apiKeyVerification:
      enabled: false
      location: "header"
    rateLimit:
      enabled: false
      identifier: "IP"
      limit: "6"
      interval: "pm"
    quota:
      identifier: ""
      limit: ""
    OASValidation:
      requestEnabled: false
      responseEnabled: false
      allowUnspecifiedHeaders: false
      allowUnspecifiedQueryParams: false
      allowUnspecifiedCookies: false
    CORS:
      enabled: false
      allowCredentials: false
      allowOrigins: "https://allowed-origin.com"
      handlePreflightRequests:
        enabled: false
        allowHeaders: "Accept, Content-Type"
        allowMethods: "GET, POST"
        maxAge: 36000
    template: ""

security:
  canvasSystemRole: Admin

mongodb:
  port: 27017
  database: tmf

image:
  pullPolicy: Always

api:
  image: "akumartmf/producttestapi:0.1"
  versionLabel: producttestapi-0.1
  port: 8080
  otlp:
    console:
      enabled: false
    protobuffCollector:
      enabled: false
      url: http://observability-opentelemetry-collector.monitoring.svc.cluster.local:4318/v1/traces

metrics:
  image: "akumartmf/producttestmanagementmetrics:0.1"

secretsManagement:
  podSelector:
    namespace: components
    name: ""
    serviceaccount: ""

canvasinfo:
  host: ""
  basepath: ""
