apiVersion: oda.tmforum.org/v1beta4
kind: Component
metadata:
  labels:
    oda.tmforum.org/componentName: '{{.Release.Name}}-{{.Values.component.name}}'
  name: '{{.Release.Name}}-{{.Values.component.name}}'
spec:
  componentMetadata:
    description: Party Interaction deals with the initial greeting and welcoming of
      a new contact. This will typically be the first component in a customer experience
      journey, shared by unassisted (self-service, retail kiosk) or assisted (call
      center, retail store) channels. It will identify known parties or new parties
      and react appropriately to propose available actions. It records all the interactions
      for the parties from all channels.
    eTOMs:
    - 1.3.5_Customer_Interaction_Management_v23.0
    - 1.3.5.1_Create_Customer_Interaction_v23.0
    - 1.3.5.2_Update_Customer_Interaction_v23.0
    - 1.3.5.3_Close_Customer_Interaction_v23.0
    - 1.3.5.4_Log_Customer_Interaction_v23.0
    - 1.3.5.6_Track_and_Manage_Customer_Interaction_v23.0
    - 1.3.5.7_Report_Customer_interaction_v23.0
    - 1.6.9_Business_Partner_Interaction_Management_v23.0
    - 1.6.9.1_Log_Business_Partner_Interaction_v23.0
    - 1.6.9.3_Track_and_Manage_Business_Partner_Interaction_v23.0
    - 1.6.9.5_Analyze_&_Report_Business_Partner_Interactions_v23.0
    functionalBlock: PartyManagement
    functionalFrameworkFunctions:
    - 93_Customer_Behavior_Tracking_v23.0
    - 163_Contact_Queuing_v23.0
    - 165_Customer_Support_Collaboration_Access_v23.0
    - 168_Voice_Channel_Contact_Routing_v23.0
    - 189_Customer_Interaction_Information_Capturing_v23.0
    - 191_Customer_Relationship/Context_Event_Data_Accumulation_v23.0
    - 196_Customer_Interaction_Logging_v23.0
    - 239_Recommendation_to_Customer_Notification_v23.0
    - 1041_Partner_Interaction_Journalizing_v23.0
    id: TMFC023
    maintainers:
    - email: components@tmforum.org
      name: Redacted
      url: Redacted
    name: PartyInteractionManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    publicationDate: 2024-04-30 00:00:00
    status: specified
    version: 1.1.0
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      name: party-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: party-role-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: user-role-permission-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/4.0.0/swagger/TMF672_User_Role_Permission_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: entity-catalog-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF662_Entity_Catalog/4.0.0/swagger/TMF662_Entity_Catalog_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: document-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF667_Document/4.0.0/swagger/TMF667_Document_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: event-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF688_Event/4.0.0/swagger/TMF688_Event_Management_API_v4.0.0_beta_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: communication-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF681_Communication/4.0.0/swagger/TMF681_Communication_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: process-flow-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      developerUI: not_defined
      implementation: '{{.Release.Name}}-party-interaction-management-api'
      name: party-interaction-management-api
      path: not_defined
      port: 8080
      specification:
      - - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Historic/TMF683_Party_Interaction/4.0.0/swagger/TMF683-PartyInteraction-4.0.0.swagger.json
        - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF683_Party_Interaction/4.0.0/swagger/TMF683_Party_Interaction_Management_API_v4.0.0_swagger.json
          version: v4.0.0
    - apiType: openapi
      developerUI: not_defined
      implementation: '{{.Release.Name}}-process-flow-management-api'
      name: process-flow-management-api
      path: not_defined
      port: 8080
      specification:
      - - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
          version: v4.0.0
    - apiType: openapi
      developerUI: not_defined
      implementation: '{{.Release.Name}}-event-management-api'
      name: event-management-api
      path: not_defined
      port: 8080
      specification:
      - - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF688_Event/4.0.0/swagger/TMF688_Event_Management_API_v4.0.0_beta_swagger.json
          version: v4.0.0
  eventNotification:
    publishedEvents:
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyInteractionManagement/hub
      id: TMF683
      implementation: /{{.Release.Name}}-PartyInteractionManagementEvent
      name: PartyInteractionManagement
      port: 80
      resources:
      - partyInteractionCreateEvent
      - partyInteractionAttributeValueChangeEvent
      - partyInteractionDeleteEvent
      - partyInteractionStatusChangeEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF683_PartyInteraction/blob/master/partyInteractionManagement_TMF_v1.0.0Review2.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      id: TMF701
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
        version: v4.0.0
    subscribedEvents:
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/call-back
      id: TMF632
      implementation: /{{.Release.Name}}-PartyManagement
      name: PartyManagement
      port: 80
      resources:
      - IndividualCreateEvent
      - IndividualAttributeValueChangeEvent
      - IndividualStateChangeEvent
      - IndividualDeleteEvent
      - OrganizationCreateEvent
      - OrganizationAttributeValueChangeEvent
      - OrganizationStateChangeEvent
      - OrganizationDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF632_PartyManagement/blob/master/TMF632-Party-v4.0.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/call-back
      id: TMF701
      implementation: /{{.Release.Name}}-PartyRoleManagement
      name: PartyRoleManagement
      port: 80
      resources:
      - PartyRoleCreateEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.1.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/DocumentgManagement/call-back
      id: TMF667
      implementation: /{{.Release.Name}}-DocumentgManagementEvent
      name: documentManagement
      port: 80
      resources:
      - documentChangeEvent
      - documentSpecificationAttributeValueChangeEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF667_Document/blob/master/TMF667-Document-v4.0.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      id: TMF701
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
        version: v4.0.0
  publicationDate: '{{.Values.component.publicationDate}}'
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - apiType: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      implementation: '{{.Release.Name}}-partyroleapi'
      name: party-role-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      specification:
      - - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
          version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
