apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: {{.Release.Name}}-{{.Values.component.name}}
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  componentMetadata:
    id: {{.Values.component.id}}
    name: {{.Values.component.name}}
    functionalBlock: {{.Values.component.functionalBlock}}
    publicationDate: {{.Values.component.publicationDate}}
    status: specified
    version: {{.Values.component.version}}
    description: "The Party Management component is responsible for the capture, validation and management of Parties. A Party may be an individual or organization that has a relationship with an enterprise."
    maintainers:
    - name: TM Forum
      email: components@tmforum.org
    owners:
    - name: TM Forum
      email: components@tmforum.org

  coreFunction:
    exposedAPIs:
    - name: party-management-api
      id: TMF632
      specification:
      - url: "https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/5.0.0/swagger/TMF632-Party_Management-v5.0.0.oas.yaml"
        implementation: {{.Release.Name}}-partymngtapi
        apiType: openapi
        gatewayConfiguration:
          apiKeyVerification: {{.Values.component.apipolicy.apiKeyVerification | toYaml | nindent 12}}
          rateLimit: {{.Values.component.apipolicy.rateLimit | toYaml | nindent 12}}
          quota: {{.Values.component.apipolicy.quota | toYaml | nindent 12}}
          OASValidation: {{.Values.component.apipolicy.OASValidation | toYaml | nindent 12}}
          CORS: {{.Values.component.apipolicy.CORS | toYaml | nindent 12}}
          template: "{{.Values.component.apipolicy.template}}"
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyManagement/v5
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyManagement/v5/api-docs
        port: 8632

    dependentAPIs:
    - name: party-role-management-api
      id: TMF669
      required: true
      specification:
      - url: "https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/5.0.0/swagger/TMF669-Party_Role_Management-v5.0.0.oas.yaml"
        apiType: openapi
        resources:
        - partyRole:
          - GET
          - GET /id

  eventNotification:
    publishedEvents:
    - apiType: openapi
      implementation: /{{.Release.Name}}-partymngtapi
      name: party-management-api
      port: 8632
      resources:
      - IndividualCreateEvent
      - IndividualAttributeValueChangeEvent
      - IndividualStateChangeEvent
      - IndividualDeleteEvent
      - OrganizationCreateEvent
      - OrganizationAttributeValueChangeEvent
      - OrganizationStateChangeEvent
      - OrganizationDeleteEvent
      id: TMF632
      apiSDO: tmForum
    subscribedEvents: []

  managementFunction:
    exposedAPIs:
    - name: metrics
      apiType: prometheus
      gatewayConfiguration:
        apiKeyVerification: {{.Values.component.apipolicy.apiKeyVerification | toYaml | nindent 10}}
        rateLimit: {{.Values.component.apipolicy.rateLimit | toYaml | nindent 10}}
        quota: {{.Values.component.apipolicy.quota | toYaml | nindent 10}}
        OASValidation: {{.Values.component.apipolicy.OASValidation | toYaml | nindent 10}}
        CORS: {{.Values.component.apipolicy.CORS | toYaml | nindent 10}}
        template: "{{.Values.component.apipolicy.template}}"
      implementation: {{.Release.Name}}-{{.Values.component.name}}-sm
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000

  securityFunction:
    canvasSystemRole: {{ .Values.security.canvasSystemRole }}
    exposedAPIs: []
