apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  maintainers:
    - name: Sylvie Demarest
      email: sylvie.demarest@orange.com
  owners:
    - name: Gaetano Biancardi
      email: gaetano.biancardi@accenture.com
  coreFunction:
    exposedAPIs:
      - name: ResourceInventory
        id: TMF639
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF639-ResourceInventory/master/TMF639-ResourceInventory-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-ResourceInventory
        apitype: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4.1.0
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4/docs
        port: 8080
        resources:
          - resource:
              - GET
              - GET /id
              - POST
              - PATCH
              - DELETE
        required: true
      - name: ResourcePoolManagement
        id: TMF685
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF685_ResourcePool/master/Resource_Pool_Management.admin.swagger.json
        implementation: /{{.Release.Name}}-PoolManagement
        apitype: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PoolManagement/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PoolManagement/v4/docs
        port: 8080
        resources:
          - resourcePool:
              - POST
              - PATCH
              - DELETE
          - reservation:
              - GET
              - GET /id
              - POST
              - PATCH
          - availabilityCheck:
              - GET
              - GET /id
              - POST
          - push:
              - GET
              - GET /id
              - POST
          - extract:
              - GET
              - GET /id
              - POST
        required: false
      - name: ProcessFlowManagement
        id: TMF701
        version: 4
        specification: >-
          ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-ProcessFlowManagement
        apitype: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
        port: 8080
        resources:
          - processFlow:
              - POST
              - GET
              - GET /id
              - DELETE
          - taskFlow:
              - PATCH
              - GET
              - GET /id
        required: false
      - name: Event
        id: TMF688
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF688-Event/master/TMF688-Event-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-Event
        apitype: openapi
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4/docs
        port: 8080
        resources:
          - event:
              - GET
              - GET /id
              - POST
              - PATCH
              - DELETE
        required: false
    publishedEvents:
      - name: ResourceInventory
        id: TMF634
        isRequired: 'yes'
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF639-ResourceInventory/master/TMF639-ResourceInventory-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-ResourceInventory
        apitype: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4.1.0
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4/docs
        port: 8080
        resources:
          resource:
            - resourceCreateEvent
            - resourceChangeEvent
            - resourceDeleteEvent
            - resourceAttributeValueChangeEvent
      - name: ResourcePoolManagement
        id: TMF685
        isRequired: 'yes'
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF685_ResourcePool/master/Resource_Pool_Management.admin.swagger.json
        implementation: /{{.Release.Name}}-ResourcePool
        apitype: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourcePool/v4.1.0
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourcePool/v4/docs
        port: 8080
        resources:
          resourcePool:
            - reservationStateChangeNotification
            - informationRequiredNotification
            - resourceReservationCreationEvent
            - resourceReservationRemoveEvent
      - name: ProcessFlowManagement
        specification: >-
          https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
        hub: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
        implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
        apitype: openapi
        port: 80
        '-resources':
          ProcessFlowManagement:
            - processFlowCreateEvent
            - processFlowStateChangeEvent
            - processFlowStateDeleteEvent
            - processFlowStateAttributeValueChangeEvent
            - taskFlowCreateEvent
            - taskFlowStateChangeEvent
            - taskFlowDeleteEvent
            - taskFlowAttributeValueChangeEvent
            - taskFlowInformationRequiredEvent
    subscribedEvents:
      - name: ResourceCatalogManagement
        id: TMF634
        isRequired: 'yes'
        version: 4.1
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF634_resourceCatalog/master/TMF634_resourceCatalog-v4.1.0.swagger.json
        implementation: /{{.Release.Name}}-ResourceCatalog
        apitype: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4.1.0
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4/docs
        port: 8080
        resources:
          ResourceCatalogManagement:
            - resourceCatalogCreateEvent
            - resourceCatalogChangeEvent
            - resourceCatalogDeleteEvent
            - resourceCategoryCreateEvent
            - resourceCategoryChangeEvent
            - resourceCategoryDeleteEvent
            - resourceCandidateCreateEvent
            - resourceCandidateChangeEvent
            - resourceCandidateDeleteEvent
            - resourceSpecificationCreateEvent
            - resourceSpecificationChangeEvent
            - resourceSpecificationDeleteEvent
            - importJobCreateEvent
            - exportJobCreateEvent
            - exportJobStateChangeEvent
      - name: ResourceInventory
        id: TMF634
        isRequired: 'yes'
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF639-ResourceInventory/master/TMF639-ResourceInventory-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-ResourceInventory
        apitype: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4.1.0
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4/docs
        port: 8080
        resources:
          resource:
            - resourceCreateEvent
            - resourceChangeEvent
            - resourceDeleteEvent
            - resourceAttributeValueChangeEvent
      - name: PartyRoleManagement
        specification: >-
          https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
        apitype: openapi
        port: 80
      - resources:
          PartyRole:
            - PartyRoleCreateEvent
            - PartyRoleAttributeValueChangeEvent
            - PartyRoleStateChangeEvent
            - PartyRoleDeleteEvent
      - name: UserRolesandPermissions
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRolesandPermissions/master/TMF672-UserRolesandPermissions-v4.0.0.swagger.json
        apitype: openapi
        port: 80
      - resources:
          UserRoles:
            - UserRoleCreationNotification
            - UserRoleChangeNotification
      - name: GeographicSiteManagement
        specification: https://open-api.tmforum.org20-GeographicSite-v4.0.0.swagger.json
        call-back: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSite/call-back
        port: 80
        implementation: /{{.Release.Name}}-GeographicSiteManagement
        apitype: openapi
        resources:
          - GeographicSite:
              - geographicSiteDeleteEvent
      - name: GeographicLocation
        specification: https://open-api.tmforum.org20-GeographicLocatin-v4.0.0.swagger.json
        call-back: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/call-back
        port: 80
        implementation: /{{.Release.Name}}-GeographicLocation
        apitype: openapi
        resources:
          - GeographicLocation:
              - geographicLocationDeleteEvent
      - name: PartyManagement
        specification: https://open-api.tmforum.org20-Party-v4.0.0.swagger.json
        call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Party/call-back
        port: 80
        implementation: /{{.Release.Name}}-PartyManagement
        apitype: openapi
        resources:
          - Party:
              - individualDeleteEvent
              - organizationDeleteEvent
    dependentAPIs:
      - name: ResourceCatalogManagement
        id: TMF634
        version: 4.1
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF634_resourceCatalog/master/TMF634_resourceCatalog-v4.1.0.swagger.json
        implementation: /{{.Release.Name}}-ResourceCatalog
        apitype: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4.1.0
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4/docs
        port: 8080
        resources:
          - resourceCatalog:
              - GET
              - GET /id
          - resourceCategory:
              - GET
              - GET /id
              - POST
              - PATCH
              - DELETE
          - resourceSpecification:
              - GET
              - GET /id
              - POST
              - PATCH
              - DELETE
          - resourceCandidate:
              - GET
              - GET /id
              - POST
              - PATCH
              - DELETE
          - exportJob:
              - GET
              - POST
              - DELETE
          - importJob:
              - GET
              - POST
              - DELETE
        required: true
      - name: PartyRoleManagement
        id: TMF669
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.swagger.json
        implementation: /{{.Release.Name}}-PartyRole
        apitype: openapi
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRole/v4.0
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4/docs
        port: 8080
        resources:
          - partyRole: '-GET -GET /id'
        required: false
      - name: Party
        id: TMF632
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF632_Party/master/TMF632-Party-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-Party
        apitype: openapi
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Party/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Party/v4/docs
        port: 8080
        resources:
          - individual:
              - GET
              - GET /id
          - organization:
              - GET
              - GET /id
        required: false
      - name: GeographicAddressManagement
        id: TMF673
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.1.swagger.json
        implementation: /{{.Release.Name}}-GeographicAddressManagement
        apitype: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/v4/docs
        port: 8080
        resources:
          - geographicAddress:
              - GET
              - GET /id
        required: true
      - name: GeographicSiteManagement
        id: TMF674
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF674_GeographicSite/master/TMF674-GeographicSite-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-GeographicSiteManagement
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/v4/docs
        port: 8080
        resources:
          - geographicSite:
              - GET
              - GET /id
        required: true
      - name: GeographicLocation
        id: TMF675
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF675_GeographicLocation/master/TMF675-GeographicLocation-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-GeographicLocation
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/v4/docs
        port: 8080
        resources:
          - geographicLocation:
              - GET
              - GET /id
        required: true
      - name: UserRolesPermissions
        id: TMF672
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRolesPermissions/master/TMF672-UserRolePermission-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-UserRolesPermissions
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRolesPermissions/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRolesPermissions/v4/docs
        port: 8080
        resources:
          - permission:
              - GET
              - GET /id
        required: true
      - name: ResourceInventoryManagement
        id: TMF639
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF639-ResourceInventory/master/TMF639-ResourceInventory-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-ResourceInventory
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4/docs
        port: 8080
        resources:
          - resource:
              - GET
              - GET /id
              - POST
              - PATCH
              - DELETE
        required: true
      - name: Event
        id: TMF688
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF688-Event/master/TMF688-Event-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-Event
        apitype: openapi
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4/docs
        port: 8080
        resources:
          - event:
              - POST
              - DELETE
        required: false
  securityFunction: []
  managementFunction: []
  id: TMFC012
  name: ResourceInventory
  functionalBlock: Production
  publicationDate: 2023-08-18T00:00:00.000Z
  status: specified
  version: 2.0.0
  description: >-
    Resource Inventory component is responsible for accounting for resources
    (all inputs - including stock, parts, assets, production components etc.)
    that are owned and/or held for allocation and/or use by the organization.
    Resource Inventory component has functionality that includes inventory items
    creation, inventory organization, inventory search or filter, inventory
    monitoring and tracking, inventory control (organization, re-stock
    management etc.) and inventory auditing. The minimum check to be performed
    at inventory items creation or update is the global consistency with related
    Resource Catalog information.
