apiVersion: oda.tmforum.org/v1beta4
kind: Component
metadata:
  labels:
    oda.tmforum.org/componentName: '{{.Release.Name}}-{{.Values.component.name}}'
  name: '{{.Release.Name}}-{{.Values.component.name}}'
spec:
  componentMetadata:
    description: 'This component is in charge of the orchestration of the delivery
      of Product Orders (status accepted). Based on the Product specification level
      of information available in the Product Catalog (ex: prerequisite links between
      product specifications, links between product and CFS specifications, ...):
      it determines in which order the product specification level order items need
      to be delivered, and to which CFS (or Resource) specification each ordered product
      corresponds, and prepares and addresses each related service (or resource) order
      to the production system in charge. During the delivery process execution, this
      component is in charge of the evolution of the status of the product specification
      level order items, and of the related product items . So, it triggers the updates
      of the related inventories.'
    eTOMs:
    - 1.3.3_Customer_Order_Handling_v23.0
    - 1.3.3.8_Manage_Order_Fallout_v23.0
    - 1.3.3.9_Customer_Order_Orchestration_v23.0
    - 1.2.9_Product_Offering_Purchasing_v23.0
    - 1.2.9.5_Complete_Product_Offering_Purchase_v23.0
    - 1.4.5_Service_Configuration_&_Activation_v23.0
    - 1.4.5.6_Issue_Service_Order_v23.0
    - 1.5.6_Resource_Provisioning_v23.0
    - 1.5.6.7_Issue_Resource_Order_v23.0
    functionalBlock: CoreCommerce
    functionalFrameworkFunctions:
    - 16_Fallout_Automated_Correction_vv23.0
    - 17_Fallout_Correction_Information_Collection_vv23.0
    - 18_Fallout_Management_to_Fulfillment_Application_Accessing_vv23.0
    - 19_Fallout_Manual_Correction_Queuing_vv23.0
    - 20_Fallout_Notification_vv23.0
    - 21_Fallout_Orchestration_vv23.0
    - 22_Fallout_Reporting_vv23.0
    - 23_Fallout_Dashboard_System_Log-in_Accessing_vv23.0
    - 24_Pre-populated_Fallout_Information_Presentation_vv23.0
    - 175_Customer_Support_Jeopardy_Notification_vv23.0
    - 174_Customer_Order_Error_Resolution_Support_vv23.0
    - 723_Customer_Order_Item_Decomposition_vv23.0
    - 214_Customer_Order_Orchestration_vv23.0
    - 215_Retro-active_order_orchestration_vv23.0
    - 342_Mass_Service/product_pre-activation_vv23.0
    - 743_Number_Portability_Orchestration_vv23.0
    - 756_Fallout_Rule_Based_Error_Correction_vv23.0
    id: TMFC003
    maintainers:
    - email: components@tmforum.org
      name: Redacted
      url: Redacted
    name: ProductOrderDeliveryOrchestrationAndManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    publicationDate: 2023-08-18 00:00:00
    status: specified
    version: 1.1.1
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      name: product-catalog-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF620_Product_Catalog/4.1.0/swagger/TMF620_Product_Catalog_Management_API_v4.1.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: product-ordering-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF622_Product_Ordering/4.0.0/swagger/TMF622_Product_Ordering_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: product-inventory-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF637_Product_Inventory/4.0.0/swagger/TMF637_Product_Inventory_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: service-catalog-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF633_Service_Catalog/4.0.0/swagger/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: service-inventory-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF638_Service_Inventory/4.0.0/swagger/TMF638_Service_Inventory_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: service-ordering-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF641_Service_Ordering/4.1.0/swagger/TMF641_Service_Ordering_Management_API_v4.1.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: resource-catalog-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF634_Resource_Catalog/4.1.0/swagger/TMF634_Resource_Catalog_Management_API_v4.1.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: resource-inventory-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF639_Resource_Inventory/4.0.0/swagger/TMF639_Resource_Inventory_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: resource-order-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF652_Resource_Order/4.0.0/swagger/TMF652_Resource_Order_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: process-flow-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      developerUI: not_defined
      implementation: '{{.Release.Name}}-process-flow-management-api'
      name: process-flow-management-api
      path: not_defined
      port: 8080
      specification:
      - - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
          version: v4.0.0
  eventNotification:
    publishedEvents:
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      id: TMF701
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
        version: v4.0.0
    subscribedEvents:
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOrder/call-back
      id: TMF622
      implementation: /{{.Release.Name}}-ProductOrderEvent
      name: ProductOrder
      port: 80
      resources:
      - productOrderStateChangeEvent
      - cancelProductOrderStateChangeEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/master/TMF622-ProductOrder-v4.0.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceOrderingManagement/call-back
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceOrderingManagement/v4/docs
      id: TMF641
      implementation: /{{.Release.Name}}-serviceOrderingManagementEvent
      name: ServiceOrder
      port: 80
      resources:
      - serviceOrderStateChangeEvent
      - serviceOrderAttributeValueChangeEvent
      - serviceOrderInformationRequiredEvent
      - serviceOrderMilestoneEvent
      - serviceOrderJeopardyEvent
      - cancelServiceOrderStateChangeEvent
      - cancelServiceOrderInformationRequiredEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF641_ServiceOrdering/master/TMF641-ServiceOrdering-v4.1.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceOrder/call-back
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceOrder/v4/docs
      id: TMF652
      implementation: /{{.Release.Name}}-ResourceOrder
      name: ResourceOrder
      port: 80
      resources:
      - resourceOrderStateChange
      - resourceOrderAttributeValueChangeEvent
      - resourceOrderInformationRequiredEvent
      - cancelResourceOrderStateChange
      - cancelResourceOrderInformationRequiredEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF652_ResourceOrderManagement/blob/master/TMF652-ResourceOrder-v4.0.0.swagger.json
        version: v4.0.0
  publicationDate: '{{.Values.component.publicationDate}}'
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - apiType: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      implementation: '{{.Release.Name}}-partyroleapi'
      name: party-role-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      specification:
      - - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
          version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
