apiVersion: oda.tmforum.org/v1beta3
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  name: ProductOrderCaptureAndValidation
  id: TMFC002
  functionalBlock: CoreCommerce
  description: Addresses the means of capturing what a customer wants to order, based
    on the CSP Product Catalog. This component permits to choose the configuration
    of the product offerings and products desired, to provide a quote, to check the
    eligibility of the customer order, and to complete it with information needed
    such as the related parties or associated the billing account and the delivery
    appointment if needed. This component is globally in charge of these quote management,
    order capture and validation steps, using dedicated components (e.g., Offering
    Configurator, Service Qualification, Party Mgt) when needed. After the delivery
    of the customer product order items, this component is also in charge of the commercial
    closure of the order. It includes update of the Product Inventory (status and
    starting/end date of tariffs and discounts) and potential commercial rules control
    (e.g. receipt of the contract document signed by the customer)
  publicationDate: 2024-09-05 00:00:00
  status: specified
  version: 2.0.1
  coreFunction:
    dependentAPIs:
    - id: TMF620
      version: v4.1.0
      apiType: openapi
      name: product-catalog-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF620_v4.1.0.swagger.json
      port: 8080
      resources:
      - productCategory:
        - GET
        - GET /id
      - productOffering:
        - GET
        - GET /id
      - productOfferingPrice:
        - GET
        - GET /id
      - productSpecification:
        - GET
        - GET /id
    - id: TMF637
      version: v4.0.0
      apiType: openapi
      name: product-inventory-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF637_v4.0.0.swagger.json
      port: 8080
      resources:
      - product:
        - GET
        - GET /id
        - POST
        - PATCH
    - id: TMF679
      version: v4.0.0
      apiType: openapi
      name: product-offering-qualification-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF679_v4.0.0.swagger.json
      port: 8080
      resources:
      - productOfferingQualification:
        - GET
        - GET /id
        - POST
        - PATCH
    - id: TMF645
      version: v4.0.0
      apiType: openapi
      name: service-qualification-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF645_v4.0.0.swagger.json
      port: 8080
      resources:
      - checkServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
      - queryServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
    - id: TMF646
      version: v4.0.0
      apiType: openapi
      name: appointment-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF646_v4.0.0.swagger.json
      port: 8080
      resources:
      - appointment:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - searchTimeSlot:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
    - id: TMF673
      version: v4.0.0
      apiType: openapi
      name: geographic-address-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF673_v4.0.0.swagger.json
      port: 8080
      resources:
      - geographicAddress:
        - GET
        - GET /id
      - geographicSubAddress:
        - GET
        - GET /id
      - geographicAddressValidation:
        - GET
        - GET /id
        - POST
        - PATCH
    - id: TMF674
      version: v4.0.0
      apiType: openapi
      name: geographic-site-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF674_v4.0.0.swagger.json
      port: 8080
      resources:
      - geographicSite:
        - GET
        - GET /id
    - id: TMF716
      version: v4.0.0
      apiType: openapi
      name: resource-reservation
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF716_v4.0.0.swagger.json
      port: 8080
      resources:
      - resourceReservation:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - cancelResourceReservation:
        - GET
        - GET /id
        - POST
    - id: TMF687
      version: v4.0.0
      apiType: openapi
      name: stock-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF687_v4.0.0.swagger.json
      port: 8080
      resources:
      - checkProductStock:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - queryProductStock:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - reserveProductStock:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - productStock:
        - GET
        - GET /id
    - id: TMF632
      version: v4.0.0
      apiType: openapi
      name: party-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v4.0.0.swagger.json
      port: 8080
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
    - id: TMF669
      version: v4.0.0
      apiType: openapi
      name: party-role-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      port: 8080
      resources:
      - partyRole:
        - GET
        - GET /id
    - id: TMF666
      version: v4.0.0
      apiType: openapi
      name: account-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF666_v4.0.0.swagger.json
      port: 8080
      resources:
      - billingAccount:
        - GET /id
        - GET
    - id: TMF676
      version: v4.0.0
      apiType: openapi
      name: payment-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF676_v4.0.0.swagger.json
      port: 8080
      resources:
      - payment:
        - GET / id
        - GET
    - id: TMF683
      version: v4.0.0
      apiType: openapi
      name: party-interaction-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF683_v4.0.0.swagger.json
      port: 8080
      resources:
      - partyInteraction:
        - GET / id
        - GET
    - id: TMF638
      version: v4.0.0
      apiType: openapi
      name: service-inventory-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF638_v4.0.0.swagger.json
      port: 8080
      resources:
      - service:
        - GET / id
        - GET
    - id: TMF639
      version: v4.0.0
      apiType: openapi
      name: resource-inventory-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF639_v4.0.0.swagger.json
      port: 8080
      resources:
      - resource:
        - GET / id
        - GET
    - id: TMF760
      version: v5.0.0
      apiType: openapi
      name: product-configuration-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF760_v5.0.0.swagger.json
      port: 8080
      resources:
      - checkProductConfiguration:
        - GET
        - GET /id
        - POST
      - queryProductConfiguration:
        - GET
        - GET /id
        - POST
    - id: TMF651
      version: v4.0.0
      apiType: openapi
      name: agreement-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF651_v4.0.0.swagger.json
      port: 8080
      resources:
      - agreement:
        - GET
        - GET /id
    exposedAPIs:
    - id: TMF622
      version: v4.0.0
      apiType: openapi
      name: product-ordering-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF622_v4.0.0.swagger.json
      port: 8080
      resources:
      - productOrder:
        - POST
        - GET
        - GET /id
        - PATCH
        - DELETE
      - cancelProductOrder:
        - POST
        - GET
        - GET /id
    - id: TMF648
      version: v4.0.0
      apiType: openapi
      name: quote-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF648_v4.0.0.swagger.json
      port: 8080
      resources:
      - quote:
        - POST
        - GET
        - GET /id
        - PATCH
        - DELETE
    - id: TMF663
      version: v4.0.0
      apiType: openapi
      name: shopping-cart-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF663_v4.0.0.swagger.json
      port: 8080
      resources:
      - shoppingCart:
        - POST
        - GET
        - GET /id
        - PATCH
        - DELETE
  owners:
  - email: Redacted
    name: Redacted
  maintainers:
  - name: Redacted
    email: components@tmforum.org
  managementFunction:
    exposedAPIs:
    - name: metrics
      apiType: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - id: TMF669
      version: v4.0.0
      apiType: openapi
      name: party-role-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      port: 8080
      resources: []
    dependentAPIs: []
  eventNotification:
    publishedEvents:
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOrder/hub
      implementation: /{{.Release.Name}}-ProductOrderEvent
      name: ProductOrder
      port: 80
      resources:
      - productOrderStateChange
      - productOrderCreateEvent
      - productOrderAttributeValueChange
      - productOrderDelete
      - productOrderInformationRequired
      - cancelProductOrderCreateEvent
      - cancelProductOrderStateChange
      - cancelProductOrderInformationRequired
      specification: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/master/TMF622-ProductOrder-v4.0.0.swagger.json
      id: TMF622
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Quote/hub
      implementation: /{{.Release.Name}}-QuoteEvent
      name: Quote
      port: 80
      resources:
      - quoteStateChange
      - quoteCreateEvent
      - quoteAttributeValueChange
      - quoteDelete
      - quoteInformationRequired
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF648_QuoteManagement/master/TMF648-QuoteManagement-v4.0.0.swagger.json
      id: TMF648
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ShoppingCart/hub
      implementation: /{{.Release.Name}}-ShoppingCartEvent
      name: ShoppingCart
      port: 80
      resources:
      - shoppingCartCreateEvent
      - shoppingCartAttributeValueChange
      - shoppingCartDelete
      specification: https://github.com/tmforum-apis/TMF663_ShoppingCart/blob/master/TMF663-ShoppingCart-v4.0.0.swagger.json
      id: TMF663
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
      id: TMF701
    subscribedEvents:
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOfferingQualification/call-back
      implementation: /{{.Release.Name}}-ProductOfferingQualificationEvent
      name: ProductOfferingQualification
      port: 80
      resources:
      - productOfferingQualificationStateChangeEvent
      specification: https://github.com/tmforum-apis/TMF679_ProductOfferingQualification/blob/master/TMF679-ProductOfferingQualification-v4.0.0.swagger.json
      id: TMF679
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/call-back
      implementation: /{{.Release.Name}}-ServiceQualificationEvent
      name: ServiceQualification
      port: 80
      resources:
      - checkServiceQualificationStateChangeEvent
      - queryServiceQualificationStateChangeEvent
      specification: https://github.com/tmforum-apis/TMF645_ServiceQualification/blob/master/TMF645-ServiceQualification-v4.0.0.swagger.json
      id: TMF645
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/call-back
      implementation: /{{.Release.Name}}-GeographicAddressManagementEvent
      name: GeographicAddressManagement
      port: 80
      resources:
      - geographicAddressValidationStateChange
      specification: https://github.com/tmforum-apis/TMF673_GeographicAddress/blob/master/TMF673-GeographicAddress-v4.0.1.swagger.json
      id: TMF673
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PaymentManagementEvent/call-back
      implementation: /{{.Release.Name}}-PaymentManagementEvent
      name: PaymentManagement
      port: 80
      resources:
      - paymentCreate
      - paymentStateChange
      specification: https://github.com/tmforum-apis/TMF676_PaymentManagement/blob/master/TMF676-Payment-v4.0.0.swagger.json
      id: TMF676
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceReservationEvent/call-back
      implementation: /{{.Release.Name}}-ResourceReservationEvent
      name: ResourceReservation
      port: 80
      resources:
      - resourceReservationCreateEvent
      - resourceReservationAttributeValueChangeEvent
      - resourceReservationDeleteEvent
      - resourceReservationStateChangeEvent
      - resourceReservationInformationRequiredEvent
      - cancelResourceReservationCreateEvent
      - cancelResourceReservationStateChangeEvent
      - cancelResourceReservationInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF716_ResourceReservation/blob/master/TMF716-ResourceReservation-v4.1.0.swagger.json
      id: TMF716
