apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "components.oda.tmforum.org"
spec:
  type: object
  properties:
    componentId: #added by gaetano.biancardi@accenture.com on 2023-07-15
      type: string
      description: TMF ODA Component identifier in the format TMFCXXX.
      example: TMFC001-productcatalogmanagement
    componentName: #added by gaetano.biancardi@accenture.com on 2023-07-15
      type: string
      description: TMF ODA Component Name
      example: Product Catalog Management      
    componentFunctionalBlock: #added by gaetano.biancardi@accenture.com on 2023-07-15
      type: string
      description: TMF ODA Component Name Functional Block
      example: Core Commerce Management           
    componenentDescription: #added by gaetano.biancardi@accenture.com on 2023-07-15
      type: string
      description: TMF ODA Component Description
      example: The Product Catalog Management ODA Component is responsible for organizing the collection of Products and Product Offerings specifications that identify and define all requirements of a product or a product offering that can be commercialized.              
    componentVersion: #added by gaetano.biancardi@accenture.com on 2023-07-15
      type: string
      description: TMF ODA Component Version
      example: 1.0.0  
    componentStatus: #added by gaetano.biancardi@accenture.com on 2023-07-15
      type: string
      enum: [Specified, Planned, Future]
      description: TMF ODA Component Version
      example: 1.0.0  
    componentPublicationDate: #added by gaetano.biancardi@accenture.com on 2023-07-15
      type: string
      format: date
      example: 2023-08-18
      description: TMF ODA Component publication date 
    maintainers:
      type: array  
      description: Maintainers is an optional list of maintainers of
        the component. The maintainers in this list maintain the the
        source code, images, and package for the component.
      items:
        description: ContactData contains information about an individual or organization.
        type: object
        properties:
          email:
            description: Email is the email address.
            type: string
          name:
            description: Name is the descriptive name.
            type: string
          url:
            description: Website address of maintaining organization.
            type: string
    owners:
      type: array
      description: Owners is an optional list of the owners of the installed component. 
      items:
        type: object
        description: ContactData contains information about an individual or organization.
        properties:
          email:
            description: Email is the email address.
            type: string
          name:
            description: Name is the descriptive name.
            type: string
          url:
            description: Website address of owning organization.
            type: string                 
    coreFunction:
      type: object  
      properties:  
        exposedAPIs:   
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Name of the API
              id: 
                type: string 
                description: Open API ID in the format TMFXXX #added by Gaetano
              isRequired: #modified by gaetano.biancardi@accenture.com on 2023-07-15
                type: string 
                enum: [yes, no] 
                description: It instructs about  mandatory API (yes) and optional API #added by Gaetano
              version: 
                type: string 
                required: true 
                description: Open API version #added by Gaetano 
              specification:
                type: string
                format: url
                description: url to the specification of the API, if required. e.g. url to the swagger file for Open API.
              apitype:
                type: string
                enum: [openapi, open-metrics]
                description: The type of API specification. Currently only OpenAPI (swagger) and open-metrics (metrics) APIs are supported.
              implementation:
                type: string
                description: The name of the service where the implementation of the API is found
              path:
                type: string
                description: The path to the root of the API
              developerUI:
                type: string
                description: (optional) The path to the developer User Interface for the API
              port:
                type: integer
                description: The port where the API is exposed
              resources:  #added by Gaetano 
                type: array  #added by Gaetano 
                items:  #added by Gaetano 
                  resources:   #added by Gaetano 
                  type: object  #added by Gaetano 
                  description: Open APIs resources specified for the Component  #added by Gaetano 
                  properties:  #added by Gaetano 
                    method  #added by Gaetano 
            required:
            - name
            - isRequired
            - apitype
            - implementation
            - path
            - port
        dependentAPIs:   
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                required: true
                description: Name of the API that this component is dependent on
              id: 
                type: string
                required: true
                description: Open API id in the format TMFXXX
              isRequired:
                type: string #added by Gaetano
                required: true 
                description: It instructs about  mandatory API (yes) and optional API #added by Gaetano
              version:
                type: string
                requires: true
                description: Open API version
              specification:
                type: string
                format: url
                description: url to the specification of the API. e.g. url to the swagger file
              apitype:
                type: string
                required: true
                enum: [openapi]
                description: The type of API specification. Currently only OpenAPI (swagger) and open-metrics (metrics) APIs are supported.
              resources:  #added by Gaetano 
                type: array  #added by Gaetano 
                items:  #added by Gaetano 
                  resources:   #added by Gaetano 
                  type: object  #added by Gaetano 
                  description: Open APIs resources specified for the Component  #added by Gaetano 
                  properties:  #added by Gaetano 
                    method  #added by Gaetano 
        publishedEvents: 
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Name of the published event
              specification:
                type: string
                format: url
                description: Url of the specification of the event
              hub:
                type: string
                description: The path for configuring the destination for the events
              implementation: #added by Gaetano
                type: string
                description: ULR where implementation can be retrieved
              apitype: #added by Gaetano
                type: string
                enum: [OpenAPI]
                description: The type of API specification. Currently only OpenAPI (swagger) and open-metrics (metrics) APIs are supported.
              port:
                type: integer
                description: The port where the hub is exposed 
              resources:  #added by Gaetano 
                type: array  #added by Gaetano 
                items:  #added by Gaetano 
                  resources:   #added by Gaetano 
                  type: object  #added by Gaetano 
                  description: Open APIs resources specified for the Component  #added by Gaetano 
                  properties:  #added by Gaetano 
                    method  #added by Gaetano               
        subscribedEvents: 
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Name of the subscribed events that this component want to subscribe to.
              specification:
                type: string
                format: url
                description: Url of the specification of the event
              call-back:
                type: string
                description: The path to call-back end-point for these events
              #filter:
               # type: string
                #description: The filter to use for this subscription
                #example: CatalogStateChangeEvent&status=active
              port:
                type: integer
                description: The port where the call-back is exposed 
              apitype: #added by Gaetano
                type: string
                enum: [OpenAPI]
                description: The type of API specification. Currently only OpenAPI (swagger) and open-metrics (metrics) APIs are supported.             
              resources:  #added by Gaetano 
                type: array  #added by Gaetano 
                items:  #added by Gaetano 
                  resources:   #added by Gaetano 
                  type: object  #added by Gaetano 
                  description: Open APIs resources specified for the Component  #added by Gaetano 
                  properties:  #added by Gaetano 
                    method  #added by Gaetano                    
    management:
      type: object  
      properties:  
        exposedAPIs:   
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                required: true
                description: Name of the API
              specification:
                type: string
                format: url
                description: url to the specification of the API. e.g. url to the swagger file
              apitype:
                type: string
                required: true
                enum: [openapi, open-metrics]
                description: The type of API specification. Currently only OpenAPI (swagger) and open-metrics (metrics) APIs are supported.
              implementation:
                type: string
                required: true
                description: The name of the service where the implementation of the API is found
              path:
                type: string
                required: true
                description: The path to the root of the API
              developerUI:
                type: string
                description: (optional) The path to the developer User Interface for the API
              port:
                type: integer
                required: true
                description: The port where the API is exposed 
            required:
            - name
            - apitype
            - implementation
            - path
            - port
        dependentAPIs:   
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                required: true
                description: Name of the API that this component is dependent on
              specification:
                type: string
                format: url
                description: url to the specification of the API. e.g. url to the swagger file
              apitype:
                type: string
                required: true
                enum: [openapi, open-metrics]
                description: The type of API specification. Currently only OpenAPI (swagger) and open-metrics APIs are supported.
    security:
      type: object  
      properties:  
        exposedAPIs:   
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                required: true
                description: Name of the API
              specification:
                type: string
                format: url
                description: url to the specification of the API. e.g. url to the swagger file
              apitype:
                type: string
                required: true
                enum: [openapi]
                description: The type of API specification. Currently only OpenAPI (swagger) and open-metrics APIs are supported.
              implementation:
                type: string
                required: true
                description: The name of the service where the implementation of the API is found
              path:
                type: string
                required: true
                description: The path to the root of the API
              developerUI:
                type: string
                description: (optional) The path to the developer User Interface for the API
              port:
                type: integer
                required: true
                description: The port where the API is exposed 
            required:
            - name
            - apitype
            - implementation
            - path
            - port
        dependentAPIs:   
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                required: true
                description: Name of the API that this component is dependent on
              specification:
                type: string
                format: url
                description: url to the specification of the API. e.g. url to the swagger file
              apitype:
                type: string
                required: true
                enum: [openapi, open-metrics]
                description: The type of API specification. Currently only OpenAPI (swagger) and open-metrics APIs are supported.
        controllerRole:
          description: This is the name of the role that the Canvas controllers will use to interact with the component's APIs.
            It must exist in the roles exposed by the partyRole API.
          type: string 
reporting:
      type: object  
      properties:  
        exposedAPIs:   
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                required: true
                description: Name of the API
              specification:
                type: string
                format: url
                description: url to the specification of the API. e.g. url to the swagger file
              apitype:
                type: string
                required: true
                enum: [openapi, open-metrics]
                description: The type of API specification. Currently only OpenAPI (swagger) and open-metrics (metrics) APIs are supported.
              implementation:
                type: string
                required: true
                description: The name of the service where the implementation of the API is found
              path:
                type: string
                required: true
                description: The path to the root of the API
              developerUI:
                type: string
                description: (optional) The path to the developer User Interface for the API
              port:
                type: integer
                required: true
                description: The port where the API is exposed 
            required:
            - name
            - apitype
            - implementation
            - path
            - port
        dependentAPIs:   
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                required: true
                description: Name of the API that this component is dependent on
              specification:
                type: string
                format: url
                description: url to the specification of the API. e.g. url to the swagger file
              apitype:
                type: string
                required: true
                enum: [openapi, open-metrics]
                description: The type of API specification. Currently only OpenAPI (swagger) and open-metrics APIs are supported.