apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF666
      name: account-management-api
      apiSDO: tmForum
      required: true
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF666_Account/5.0.0/swagger/TMF666-Account_Management-v5.0.0.oas.yaml
        resources:
        - billFormat:
          - GET
          - GET /id
        - billPresentationMedia:
          - GET
          - GET /id
        - billingAccount:
          - GET
          - GET /id
        - billingCycleSpecification:
          - GET
          - GET /id
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF666_Account/4.0.0/swagger/TMF666_Account_Management_API_v4.0.0_swagger.json
        resources:
        - billingAccount:
          - GET
          - GET /id
        - billingCycleSpecification:
          - GET
          - GET /id
        - billFormat:
          - GET
          - GET /id
        - billPresentationMedia:
          - GET
          - GET /id
    - id: TMF632
      name: party-management-api
      apiSDO: tmForum
      required: true
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/5.0.0/swagger/TMF632-Party_Management-v5.0.0.oas.yaml
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
    - id: TMF676
      name: payment-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF676_Payment/4.0.0/swagger/TMF676_Payment_Management_API_v4.0.0_swagger.json
        resources:
        - payment:
          - GET
          - GET /id
          - POST
        - refund:
          - GET
          - GET /id
          - POST
    - id: TMF667
      name: document-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF667_Document/4.0.0/swagger/TMF667_Document_Management_API_v4.0.0_swagger.json
        resources:
        - document:
          - GET
          - GET /id
          - POST
    - id: TMF637
      name: product-inventory-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF637_Product_Inventory/5.0.0/swagger/TMF637-ProductInventory-v5.0.0.oas.yaml
        resources:
        - product:
          - GET
          - GET /id
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF637_Product_Inventory/4.0.0/swagger/TMF637_Product_Inventory_Management_API_v4.0.0_swagger.json
        resources:
        - product:
          - GET
          - GET /id
    - id: TMF669
      name: party-role-management-api
      apiSDO: tmForum
      required: true
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/5.0.0/swagger/TMF669-Party_Role_Management-v5.0.0.oas.yaml
        resources:
        - partyRole:
          - GET
          - GET /id
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        resources:
        - PartyRole:
          - GET
          - GET /id
    - id: TMF701
      name: process-flow-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.1.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        resources:
        - processFlow:
          - POST
          - GET
          - GET /id
          - PATCH
        - taskFlow:
          - GET
          - GET /id
          - POST
          - PATCH
    exposedAPIs:
    - id: TMF678
      name: customer-bill-management-api
      apiSDO: tmForum
      required: true
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF678_Customer_Bill/5.0.0/swagger/TMF678-CustomerBill-v5.0.0.oas.yaml
        resources:
        - billCycle:
          - GET
          - GET /id
        - customerBill:
          - GET
          - GET /id
          - POST
          - PATCH /id
        - customerBillOnDemand:
          - GET
          - GET /id
          - POST
        path: not_defined
        developerUI: not_defined
        implementation: not_defined
        port: 8080
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF678_Customer_Bill/4.0.0/swagger/TMF678_Customer_Bill_Management_API_v4.0.0_swagger.json
        resources:
        - customerBillOnDemand:
          - GET
          - POST
          - GET /id
        - customerBill:
          - GET
          - GET / id
          - POST
          - PATCH /id
        - billCycle:
          - GET
          - GET /id
        path: not_defined
        developerUI: not_defined
        implementation: not_defined
        port: 8080
    - id: TMF701
      name: process-flow-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.1.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        resources:
        - processFlow:
          - GET
          - GET /id
          - POST
          - DELETE /id
        - taskFlow:
          - GET
          - GET /id
          - PATCH /id
        path: not_defined
        developerUI: not_defined
        implementation: not_defined
        port: 8080
  componentMetadata:
    id: TMFC030
    name: BillGenerationManagement
    version: 2.1.0
    description: The Bill Generation component is responsible for Party invoice management.
      It addresses the invoice formatting, presentation and dispatching via the appropriate
      means of communication.
    publicationDate: 2026-05-21
    status: preview
    functionalBlock: PartyManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.3.9|Customer_Bill_Invoice_Management|v23.0
    - 1.3.9.2|Create_Customer_Bill_Invoice|v23.0
    - 1.3.9.2.1|Render_&_Format_Customer_Invoice|v23.0
    - 1.3.9.2.2|Deliver_Electronic_Invoice|v23.0
    - 1.3.9.2.3|Verify_Customer_Invoice_Quality|v23.0
    - 1.3.9.2.4|Manage_Customer_Invoice_Quality|v23.0
    - 1.3.9.3|Produce_&_Distribute_Customer_Bill|v23.0
    - 1.3.9.3.1|Co-ordinate_Billing_Insertion|v23.0
    - 1.3.9.3.2|Establish_&_Manage_Bill_Production_Cycle|v23.0
    - 1.3.9.3.3|Deliver_Invoice_Information|v23.0
    - 1.3.9.4|Pricing,_Discounting,_Adjustments_&_Rebates_Application|v23.0
    - 1.3.9.4.2|Apply_Pricing,_Discounting,_Adjustments_&_Rebates_to_Customer_Account|v23.0
    - 1.6.15|BP_Bill/Invoice_Management|v23.0
    - 1.6.15.2|BP_Bill/Invoice_Control|v23.0
    - 1.6.15.2.1|Establish_&_Maintain_BP_Bill_Invoice_Format|v23.0
    - 1.6.15.2.2|Maintain_Bill_Invoice_BP_List|v23.0
    - 1.6.15.2.3|Define_BP_Billing_Cycle|v23.0
    - 1.6.15.3.2|Create_BP_Bill/Invoice|v23.0
    - 1.6.15.3.2|Create_BP_Bill/Invoice|v23.0
    - 1.6.15.3.3|Distribute_BP_Bill/Invoice|v23.0
    - 1.6.15.3.4|Manage_BP_Bill/Invoice_Archive|v23.0
    - 1.6.15.3.5|Receive_BP_Bill/Invoice|v23.0
    - 1.6.15.3.6|Administer_Commercial_Arrangement_for_BP_Bill/Invoice_Creation_Capability|v23.0
    functionalFrameworkFunctions:
    - 65|Bill_Image_Presentation|v23.0
    - 62|Invoice_Items_Listing|v23.0
    - 63|Invoice_Listing|v23.0
    - 329|Invoice_Tax_Calculation|v23.0
    - 309|Invoice_Balance_Calculation|v23.0
    - 310|Invoice_Charges_Compilation|v23.0
    - 312|Invoice_Detail_Collection|v23.0
    - 311|Invoice_Totals_Calculation|v23.0
    SIDs:
    - Customer_Domain|Customer_Bill_ABE|v25.0
  managementFunction:
    exposedAPIs:
    - name: metrics
      id: exposedAPI_id
      apiSDO: not_defined
      required: false
      specification:
      - version: v4.0.0
        url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        apiType: prometheus
        implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
        port: 4000
        resources: []
        developerUI: exposedAPI_developerUI
    dependentAPIs: []
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - id: TMF669
      name: partyrole
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        resources: []
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
        implementation: '{{.Release.Name}}-partyroleapi'
        port: 8080
    - id: TMF672
      name: user-role-permission-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/4.0.0/swagger/TMF672_User_Role_Permission_Management_API_v4.0.0_swagger.json
        resources: []
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v4/docs
        implementation: '{{.Release.Name}}-userrolepermissionapi'
        port: 8080
      - version: v5.1.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/5.1.0/swagger/TMF672-User_Role_Permission_Management_API-v5.1.0.oas.yaml
        resources: []
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v5
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v5/docs
        implementation: '{{.Release.Name}}-userrolepermissionapi'
        port: 8080
    dependentAPIs: []
  eventNotification:
    publishedEvents: []
    subscribedEvents:
    - name: partyRoleManagement
      port: 80
      resources:
      - partyRoleAttributeValueChangeEvent
      - partyRoleStateChangeEvent
      - partyRoleDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF669
      apiSDO: not_defined
