apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-rescatapi
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: {{.Release.Name}}-rescatapi
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-{{.Values.component.name}}
        impl: {{.Release.Name}}-rescatapi
        version: {{.Values.api.versionLabel}}
    spec:
      containers:
      - name: {{.Release.Name}}-rescatapi
        image: {{.Values.api.image}}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        env:
        - name: COMPONENT_NAME
          value: {{.Release.Name}}-{{.Values.component.name}}
        - name: PORT
          value: "8634"
        - name: dbhost
          value: {{.Release.Name}}-mongodb
        - name: dbport
          value: "{{.Values.mongodb.port}}"
        - name: dbname
          value: {{.Values.mongodb.database}}
        - name: LOG_LEVEL
          value: "info"
        ports:
        - containerPort: 8634
        startupProbe:
          httpGet:
            path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/resourceCatalog/v5/resourceCatalog
            port: 8634
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/resourceCatalog/v5/resourceCatalog
            port: 8634
          initialDelaySeconds: 10
          periodSeconds: 5
