component:
  id: tmfc046
  name: tmfc046-workforcemanagement
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf646: tmforumorg/tmfc046-tmf646-v4.0.0:latest
  tmf669: tmforumorg/tmfc046-tmf669-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
