apiVersion: oda.tmforum.org/v1beta4
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  componentMetadata:
    description: Service Qualification component is responsible for checking and validating
      the availability of a service according to specified and configured business
      rules. It must identify at least one technical solution (RFSspec) available
      to deliver the service (CFSspec) and check the availability of all the resources
      types involved in this technical solution. No resources are allocated during
      Service Qualification. Service Qualification component has functionality that
      include checking service feasibility status and publishing or reporting service
      qualification result, but also calculated service delivery due date and identified
      need of an appointment at the customer site. Service Qualification can also
      be in charge of the cost calculation of the technical solution identified, when
      it cannot be determined at catalog design time (complex B2B services). This
      information will be used as an input to price calculation.
    eTOMs:
    - 1.4.5_Service_Configuration_&_Activation_v23.0
    functionalBlock: Production
    functionalFrameworkFunctions:
    - 319_Service_Feasibility_Checking_v23.0
    - 586_Service_Availability_Validation_v23.0
    - 571_Service_Delivery_Due_Date_Calculation_v23.0
    id: TMFC009
    maintainers:
    - email: components@tmforum.org
      name: Redacted
      url: Redacted
    name: ServiceQualificationManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    publicationDate: 2023-08-18 00:00:00
    status: specified
    version: 1.1.0
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      id: TMF633
      name: service-catalog-management-api
      required: true
      resources:
      - serviceSpecification:
        - GET
        - GET /id
      - serviceCategory:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF633_Service_Catalog/4.0.0/swagger/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF638
      name: service-inventory-management-api
      required: false
      resources:
      - service:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF638_Service_Inventory/4.0.0/swagger/TMF638_Service_Inventory_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF634
      name: resource-catalog-management-api
      required: false
      resources:
      - resourceSpecification:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF634_Resource_Catalog/4.1.0/swagger/TMF634_Resource_Catalog_Management_API_v4.1.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF639
      name: resource-inventory-management-api
      required: false
      resources:
      - resource:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF639_Resource_Inventory/4.0.0/swagger/TMF639_Resource_Inventory_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF632
      name: party-management-api
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      required: false
      resources:
      - partyRole:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF673
      name: geographic-address-management-api
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      - geographicSubAddress:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF673_Geographic_Address/4.0.0/swagger/TMF673_Geographic_Address_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF674
      name: geographic-site-management-api
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF674_Geographic_Site/4.0.0/swagger/TMF674_Geographic_Site_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF675
      name: geographic-location-management-api
      required: false
      resources:
      - geographicLocation:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF675_Geographic_Location/4.0.0/swagger/TMF675_Geographic_Location_Management_API_v4.0.0_beta_swagger.json
        version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      developerUI: not_defined
      id: TMF645
      implementation: not_defined
      name: service-qualification-management-api
      path: not_defined
      port: 8080
      required: true
      resources:
      - checkServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - queryServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF645_Service_Qualification/4.0.0/swagger/TMF645_Service_Qualification_Management_API_v4.0.0_swagger.json
        version: v4.0.0
  eventNotification:
    publishedEvents:
    - apiType: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/v4/docs
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/hub
      id: TMF645
      implementation: /{{.Release.Name}}-ServiceQualification
      name: ServiceQualification
      port: 80
      resources:
      - checkServiceQualificationCreateEvent
      - checkServiceQualificationStateChangeEvent
      - checkServiceQualificationInformationRequiredEvent
      - checkServiceQualificationAttributeValueChangeEvent
      - checkServiceQualificationDeleteEvent
      - queryServiceQualificationStateChangeEvent
      - queryServiceQualificationCreateEvent
      - queryServiceQualificationDeleteEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF645_ServiceQualification/master/TMF645-ServiceQualification-v4.0.0.swagger.json
        version: v4.0.0
    subscribedEvents: []
  managementFunction:
    dependentAPIs:
    - apiType: dependentAPI_apiType
      id: dependentAPI_id
      name: dependentAPI_name
      required: false
      resources: []
      specification:
      - url: dependentAPI_spec
        version: dependentAPI_version
      version: dependentAPI_version
    exposedAPIs:
    - apiType: prometheus
      developerUI: exposedAPI_developerUI
      id: exposedAPI_id
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
      required: false
      resources: []
      specification:
      - url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        version: v4.0.0
      version: exposedAPI_version
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    dependentAPIs: []
    exposedAPIs:
    - apiType: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      id: TMF669
      implementation: '{{.Release.Name}}-partyroleapi'
      name: party-role-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      required: true
      resources: []
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
