apiVersion: oda.tmforum.org/v1beta3
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      id: TMF633
      name: service-catalog-management-api
      port: 8080
      required: true
      resources:
      - serviceSpecification:
        - GET
        - GET /id
      - serviceCategory:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF633_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF638
      name: service-inventory-management-api
      port: 8080
      required: false
      resources:
      - service:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF638_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF639
      name: resource-inventory-management-api
      port: 8080
      required: false
      resources:
      - resource:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF639_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF632
      name: party-management-api
      port: 8080
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      port: 8080
      required: false
      resources:
      - partyRole:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF673
      name: geographic-address-management-api
      port: 8080
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      - geographicSubAddress:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF673_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF674
      name: geographic-site-management-api
      port: 8080
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF674_v4.0.0.swagger.json
      version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      id: TMF645
      name: service-qualification-management-api
      port: 8080
      required: true
      resources:
      - checkServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - queryServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF645_v4.0.0.swagger.json
      version: v4.0.0
  description: Service Qualification component is responsible for checking and validating
    the availability of a service according to specified and configured business rules.
    It must identify at least one technical solution (RFSspec) available to deliver
    the service (CFSspec) and check the availability of all the resources types involved
    in this technical solution. No resources are allocated during Service Qualification.
    Service Qualification component has functionality that include checking service
    feasibility status and publishing or reporting service qualification result, but
    also calculated service delivery due date and identified need of an appointment
    at the customer site. Service Qualification can also be in charge of the cost
    calculation of the technical solution identified, when it cannot be determined
    at catalog design time (complex B2B services). This information will be used as
    an input to price calculation.
  eventNotification:
    publishedEvents:
    - apiType: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/v4/docs
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/hub
      id: TMF645
      implementation: /{{.Release.Name}}-ServiceQualification
      name: ServiceQualification
      port: 80
      resources:
      - checkServiceQualificationCreateEvent
      - checkServiceQualificationStateChangeEvent
      - checkServiceQualificationInformationRequiredEvent
      - checkServiceQualificationAttributeValueChangeEvent
      - checkServiceQualificationDeleteEvent
      - queryServiceQualificationStateChangeEvent
      - queryServiceQualificationCreateEvent
      - queryServiceQualificationDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF645_ServiceQualification/master/TMF645-ServiceQualification-v4.0.0.swagger.json
    subscribedEvents: []
  functionalBlock: Production
  id: TMFC009
  managementFunction:
    exposedAPIs:
    - apiType: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  name: ServiceQualificationManagement
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  - email: Anastasios.sarantis@cityfibre.com
    name: Tassos Sarantis
  publicationDate: 2023-08-18 00:00:00
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    dependentAPIs: []
    exposedAPIs:
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      port: 8080
      required: true
      resources: []
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
  status: specified
  version: 1.1.0
