component:
  id: tmfc014
  name: tmfc014-locationmanagement
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf669: tmforumorg/tmfc014-tmf669-v4.0.0:latest
  tmf673: tmforumorg/tmfc014-tmf673-v4.0.0:latest
  tmf674: tmforumorg/tmfc014-tmf674-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
