apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-mongodb
  labels:
    app: {{.Release.Name}}-{{.Values.component.name}}
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  ports:
  - name: mongodb
    port: {{.Values.mongodb.port}}
    targetPort: {{.Values.mongodb.port}}
    protocol: TCP
  selector:
    impl: {{.Release.Name}}-mongodb
  type: ClusterIP
