apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-serviceinventoryapi
  labels:
    app: {{.Release.Name}}-{{.Values.component.name}}
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  ports:
  - name: serviceinventoryapi-http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    impl: {{.Release.Name}}-serviceinventoryapi
  type: NodePort
