apiVersion: oda.tmforum.org/v1beta4
kind: Component
metadata:
  labels:
    oda.tmforum.org/componentName: '{{.Release.Name}}-{{.Values.component.name}}'
  name: '{{.Release.Name}}-{{.Values.component.name}}'
spec:
  componentMetadata:
    description: Resource Catalog Management component is responsible for organizing
      the collection resource specifications that identify and define all requirements
      for a resource. Resource Catalog Management component has the functionality
      that enable presenting a customer-facing view, so users are able to browse and
      select resource they need, as well as a technical view to enable define and
      setup resources contained in the resource catalog. Additional functionalities
      include capturing specifications of new resource specifications, managing resources
      (registering assets and components and identifying and mapping connections/relationships),
      administering the lifecycle of resources, describing relationships between resources,
      reporting on resources and changes to their attributes, and facilitating easy
      access to identify and assign resources.
    eTOMs:
    - 1.5.15_Resource_Catalog_Lifecycle_Management_v23.0
    - 1.5.16_Resource_Catalog_Operational_Readiness_Management_v23.0
    - 1.5.17_Resource_Catalog_Content_Management_v23.0
    - 1.5.18_Resource_Catalog_Planning_Management_v23.0
    - 1.5.19_Resource_Specification_Management_v23.0
    - 1.5.3_Resource_Specification_Development_&_Retirement_v23.0
    - 1.5.3.4_Develop_Detailed_Resource_Specifications_v23.0
    functionalBlock: Production
    functionalFrameworkFunctions:
    - 737_Resource_Capability_Specification_Management_v23.0
    - 467_Resource_Data_Transformation/Parsing_Rules_Configuration_v23.0
    - 951_Resource_Catalog_Entities_Management_v23.0
    - 996_Resource_Task_Item_Policy_Control_Configuration_v23.0
    - 1083_Resource_Specification_Repository_Management_v23.0
    - 1088_Resource_Specification_to_Supplier_Product_Specification_Relationship_Design_v23.0
    - 1089_Resource_Specification_Action_Skill_Design_v23.0
    - 1082_Resource_Specification_Change_Auditing_v23.0
    - 1064_Logical_and_Software_Resources_Designing_v23.0
    - 1087_Resource_Specification_Design_v23.0
    id: TMFC010
    maintainers:
    - email: components@tmforum.org
      name: Redacted
      url: Redacted
    name: ResourceCatalogManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    publicationDate: 2024-12-03 00:00:00
    status: specified
    version: 1.3.0
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      name: resource-catalog-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF634_Resource_Catalog/4.1.0/swagger/TMF634_Resource_Catalog_Management_API_v4.1.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: party-role-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: party-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: entity-catalog-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF662_Entity_Catalog/4.0.0/swagger/TMF662_Entity_Catalog_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      developerUI: not_defined
      implementation: '{{.Release.Name}}-resource-catalog-management-api'
      name: resource-catalog-management-api
      path: not_defined
      port: 8080
      specification:
      - - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF634_Resource_Catalog/4.1.0/swagger/TMF634_Resource_Catalog_Management_API_v4.1.0_swagger.json
          version: v4.0.0
    - apiType: openapi
      developerUI: not_defined
      implementation: '{{.Release.Name}}-process-flow-management-api'
      name: process-flow-management-api
      path: not_defined
      port: 8080
      specification:
      - - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
          version: v4.0.0
  eventNotification:
    publishedEvents:
    - hub: /{{.Release.Name}}-ResourceCatalog/hub
      id: TMF634
      implementation: /{{.Release.Name}}-ResourceCatalogEvent
      name: ResourceCatalogManagement
      port: 80
      resources:
      - resourceCatalogCreateEvent
      - resourceCatalogChangeEvent
      - resourceCatalogDeleteEvent
      - resourceCategoryCreateEvent
      - resourceCategoryChangeEvent
      - resourceCategoryDeleteEvent
      - resourceCandidateCreateEvent
      - resourceCandidateChangeEvent
      - resourceCandidateDeleteEvent
      - resourceSpecificationCreateEvent
      - resourceSpecificationChangeEvent
      - resourceSpecificationDeleteEvent
      - importJobCreateEvent
      - exportJobCreateEvent
      - exportJobStateChangeEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF634_resourceCatalog/master/TMF634-ResourceCatalog-v4.1.0.swagger.json
        version: v4.0.0
      version: 4
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      id: TMF701
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
        version: v4.0.0
      version: 4
    subscribedEvents:
    - callback: /{{.Release.Name}}-EntityCatalog/call-back
      id: TMF662
      name: EntityCatalogManagement
      port: 80
      resources:
      - entitySpecificationCreateEvent
      - entitySpecificationAttributeValueChangeEvent
      - entitySpecificationStateChangeEvent
      - entitySpecificationDeleteEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF662_EntityCatalog/master/TMF662-EntityCatalog-v4.0.0.swagger.json
        version: v4.0.0
      version: 4
    - callback: /{{.Release.Name}}-EntityCatalog/call-back
      id: TMF669
      name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleDeleteEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.swagger.json
      version: 4
    - callback: /{{.Release.Name}}-EntityCatalog/call-back
      id: TMF632
      name: Party
      port: 80
      resources:
      - individualDeleteEvent
      - organizationDeleteEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF632_Party/master/TMF632-Party-v4.0.0.swagger.json
        version: v4.0.0
      version: 4
  publicationDate: '{{.Values.component.publicationDate}}'
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - apiType: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      implementation: '{{.Release.Name}}-partyroleapi'
      name: party-role-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      specification:
      - - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
          version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
