apiVersion: oda.tmforum.org/v1beta3
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  name: ResourceCatalogManagement
  id: TMFC010
  functionalBlock: Production
  description: Resource Catalog Management component is responsible for organizing
    the collection resource specifications that identify and define all requirements
    for a resource. Resource Catalog Management component has the functionality that
    enable presenting a customer-facing view, so users are able to browse and select
    resource they need, as well as a technical view to enable define and setup resources
    contained in the resource catalog. Additional functionalities include capturing
    specifications of new resource specifications, managing resources (registering
    assets and components and identifying and mapping connections/relationships),
    administering the lifecycle of resources, describing relationships between resources,
    reporting on resources and changes to their attributes, and facilitating easy
    access to identify and assign resources.
  publicationDate: 2024-04-30 00:00:00
  status: specified
  version: 1.2.0
  coreFunction:
    dependentAPIs:
    - id: TMF634
      version: v4.1.0
      apiType: openapi
      name: resource-catalog-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF634_v4.1.0.swagger.json
      port: 8080
      resources:
      - resourceCatalog:
        - GET
        - GET /id
      - resourceCategory:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - resourceSpecification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - resourceCandidate:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - exportJob:
        - GET
        - POST
        - DELETE
      - importJob:
        - GET
        - POST
        - DELETE
    - id: TMF669
      version: v4.0.0
      apiType: openapi
      name: party-role-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      port: 8080
      resources:
      - partyRole:
        - GET
        - GET /id
    - id: TMF632
      version: v4.0.0
      apiType: openapi
      name: party-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v4.0.0.swagger.json
      port: 8080
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
    - id: TMF662
      version: v4.0.0
      apiType: openapi
      name: entity-catalog-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF662_v4.0.0.swagger.json
      port: 8080
      resources:
      - entitySpecification:
        - GET
        - GET /id
      - associationSpecification:
        - GET
        - GET /id
    - id: TMF672
      version: v4.0.0
      apiType: openapi
      name: user-role-permission-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF672_v4.0.0.swagger.json
      port: 8080
      resources:
      - permission:
        - GET
        - GET /id
    exposedAPIs:
    - id: TMF634
      version: v4.1.0
      apiType: openapi
      name: resource-catalog-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF634_v4.1.0.swagger.json
      port: 8080
      resources:
      - resourceCatalog:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - resourceCategory:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - resourceSpecification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - resourceCandidate:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - exportJob:
        - GET
        - GET /id
        - POST
        - DELETE
      - importJob:
        - GET
        - GET /id
        - POST
        - DELETE
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  managementFunction:
    exposedAPIs:
    - name: metrics
      apiType: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - id: TMF669
      version: v4.0.0
      apiType: openapi
      name: party-role-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      port: 8080
      resources: []
    dependentAPIs: []
  eventNotification:
    publishedEvents:
    - hub: /{{.Release.Name}}-ResourceCatalog/hub
      implementation: /{{.Release.Name}}-ResourceCatalogEvent
      name: ResourceCatalogManagement
      port: 80
      resources:
      - resourceCatalogCreateEvent
      - resourceCatalogChangeEvent
      - resourceCatalogDeleteEvent
      - resourceCategoryCreateEvent
      - resourceCategoryChangeEvent
      - resourceCategoryDeleteEvent
      - resourceCandidateCreateEvent
      - resourceCandidateChangeEvent
      - resourceCandidateDeleteEvent
      - resourceSpecificationCreateEvent
      - resourceSpecificationChangeEvent
      - resourceSpecificationDeleteEvent
      - importJobCreateEvent
      - exportJobCreateEvent
      - exportJobStateChangeEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF634_resourceCatalog/master/TMF634-ResourceCatalog-v4.1.0.swagger.json
      version: 4.1
      id: TMF634
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
      version: 4
      apiType: openapi
      id: TMF701
    subscribedEvents:
    - call-back: /{{.Release.Name}}-EntityCatalog/call-back
      id: TMF662
      name: EntityCatalogManagement
      port: 80
      resources:
      - entitySpecificationCreateEvent
      - entitySpecificationAttributeValueChangeEvent
      - entitySpecificationStateChangeEvent
      - entitySpecificationDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF662_EntityCatalog/master/TMF662-EntityCatalog-v4.0.0.swagger.json
      version: 4
    - call-back: /{{.Release.Name}}-EntityCatalog/call-back
      id: TMF669
      name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.swagger.json
      version: 4
    - call-back: /{{.Release.Name}}-EntityCatalog/call-back
      id: TMF672
      name: UserRolePermission
      port: 80
      resources:
      - permissionDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF672-UserRolePermission/master/TMF672-UserRolePermission-v4.0.0.swagger.json
      version: 4
    - call-back: /{{.Release.Name}}-EntityCatalog/call-back
      id: TMF632
      name: Party
      port: 80
      resources:
      - individualDeleteEvent
      - organizationDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_Party/master/TMF632-Party-v4.0.0.swagger.json
      version: 4
