component:
  id: tmfc010
  name: tmfc010-resourcecatalogmanagement
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf634: tmforumorg/tmfc010-tmf634-v4.1.0:latest
  tmf669: tmforumorg/tmfc010-tmf669-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
