apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-prodcatapiv5
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  ports:
  - name: prodcatapiv5-http
    port: 8620
    targetPort: 8620
    protocol: TCP
  selector:
    impl: {{.Release.Name}}-prodcatapiv5
  type: NodePort
