apiVersion: oda.tmforum.org/v1beta1
kind: component
metadata:
  name: TMFC014-locationmanagement
  labels:
    oda.tmforum.org/componentName: TMFC014-locationmanagement
    oda.tmforum.org/funtionalBlockName: Production
spec:
  type: TMFC014-locationmanagement
  version: 1.0.0
  description: "The Location Management Component  allows easy reference to geographic places important to other entities, where a geographic place is an entity that can answer the question “where?” . This component could  be a facade tool into GIS systems (e.g. Google Maps) " 
  maintainers:
  - name: Tassos Sarantis
    email: Anastasios.sarantis@cityfibre.com
  - name: Adam Tlemsani
    email: adam.tlemsani@cityfibre.com
  owners:
  - name: Gaetano Biancardi
    email: gaetano.biancardi@accenture.com
  - name: Tassos Sarantis
    email: Anastasios.sarantis@cityfibre.com
coreFunction:
    exposedAPIs:
        - name: GeographicAddressManagement
          id: TMF673
          isRequired: yes
          version: 4.0
          specification: https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.1.swagger.json
          implementation: /{{.Release.Name}}-GeographicAddressManagement
          apitype: openapi
          path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/v4
          developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/v4/docs
          port: 8080
          resources:
           - geographicAddressValidation:
                - GET
                - GET /id
                - POST
                - PATCH
           - geographicAddress:
                - GET
                - GET /id
           - geographicSubAddress:
                - GET
                - GET /id
        - name: GeographicSiteManagement
          id: TMF674
          isRequired: yes
          version: 4.0
          specification: https://raw.githubusercontent.com/tmforum-apis/TMF674_GeographicSite/master/TMF674-GeographicSite-v4.0.0.swagger.json
          implementation: /{{.Release.Name}}-GeographicSiteManagement
          path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/v4
          developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/v4/docs
          port: 8080
          resources:
          - geographicSite:
                - GET
                - GET /id
                - POST
                - PATCH
                - DELETE
        - name: GeographicLocation
          id: TMF675
          isRequired: yes
          version: 4.0
          specification: https://raw.githubusercontent.com/tmforum-apis/TMF675_GeographicLocation/master/TMF675-GeographicLocation-v4.0.0.swagger.json
          implementation: /{{.Release.Name}}-GeographicLocation
          path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/v4
          developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/v4/docs
          port: 8080
          resources: 
          - geographicLocation:
                - GET
                - GET /id
                - POST
                - PATCH
                - DELETE
        - name: ProcessFlowManagement
          id: TMF701
          isRequired: not
          version: 4.0
          specification: ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
          implementation: /{{.Release.Name}}-ProcessFlowManagement
          apitype: openapi
          path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
          developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
          port: 8080
          resources: 
          - processFlow:
              - POST
              - GET
              - GET /id
              - DELETE
          - taskFlow:
              - PATCH
              - GET
              - GET /id
        - name: Event
          id: TMF688
          isRequired: not
          version: 4.0
          specification: https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
          implementation: /{{.Release.Name}}-PromotionManagement
          apitype: openapi
          path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
          developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
          port: 8080
          resources: 
          - event:  
            - GET
            - GET /id
            - POST
            - PATCH
            - DELETE
    dependantAPIs:
    - name: PartyManagement
      id: TMF632
      isRequired: not
      version: 4.0
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-Party-v4.0.0.swagger.json
      apitype: openapi
      implementation: /{{.Release.Name}}-PartyManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4/docs
      port: 8080
      resources:  
      - PartyManagement:
        - GET
        - GET /id
    - name: GeographicSiteManagement
      id: TMF674
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF674_GeographicSite/blob/master/TMF674-GeographicSite-v4.0.0.swagger.json
      apitype: openapi
      resources:
      - geographicSite:
        - GET
        - GET /id
    - name: Event 
      id: TMF688
      isRequired: not
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json      
      apitype: openapi     
      resources: 
      - event:
        - GET
        - GET /id                                  
    publishedEvents: 
        - name: GeographicAddressManagement
          id: TMF673
          isRequired: yes
          version: 4.0
          specification: https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.1.swagger.json
          implementation: /{{.Release.Name}}-GeographicAddressManagement
          apitype: openapi
          path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/v4
          developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/v4/docs
          port: 8080
          resources:
          - geographicAddressValidation:
            - geographicAddressValidationStateChangeEvent
        - name: GeographicSiteManagement
          specification: https://raw.githubusercontent.com/tmforum-apis/TMF674_GeographicSite/master/TMF674-GeographicSite-v4.0.0.swagger.json
          hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/hub
          implementation: /{{.Release.Name}}-GeographicSiteManagementEvent
          port: 8080
          resources:
          - geographicSiteManagement:
                - geographicSiteAttributeValueChangeEvent
                - geographicSiteCreateEvent
                - geographicSiteDeleteEvent
                - geographicSiteStatusChangeEvent
        - name: GeographicLocation
          specification: https://raw.githubusercontent.com/tmforum-apis/TMF675_GeographicLocation/master/TMF675-GeographicLocation-v4.0.0.swagger.json
          hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/hub
          implementation: /{{.Release.Name}}-GeographicLocationEvent
          apitype: openapi
          port: 80
          resources: 
          - geographicLocation:
              - geographicLocationAttributeValueChangeEvent
              - geographicLocationCreateEvent
              - geographicLocationDeleteEvent
    
    subscribedEvents: 
   
management: []
reporting: []
security: []
