component:
  id: tmfc035
  name: tmfc035-permissionsmanagement
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf669: tmforumorg/tmfc035-tmf669-v4.0.0:latest
  tmf672: tmforumorg/tmfc035-tmf672-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
