apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  componentId: TMFC006
  componentName: ServiceCatalogManagement
  componentFunctionalBlock: Production 
  componenentDescription: "	Service Catalog Management component is responsible for organizing the collection of service specifications that identify and define all requirements of a service that can be performed. Service Catalog Management component has the functionality that enable present a customer-facing view so users are able to search and select services they need, as well as a technical view to enable define and setup what's needed to deliver service specifications (Customer Facing Service Specifications (CFSSs) and Resource Facing Service Specifications (RFSSs)) contained in the service catalog. Service Catalog Management component has functionalities that include creation of new service specifications, managing service specifications, administering the lifecycle of services, describing relationships between service specification attributes, reporting on service specification and their changes, and facilitating easy and systematic indexing and access to services, as well as facilitate automating the service delivery process." 
  componentVersion: 1.1.1
  componentStatus: specified 
  componentPublicationDate: 2023-08-18
  maintainers:
  - name: Gaetano Biancardi
    email: gaetano.biancardi@accenture.com
  owners:
  - name: Gaetano Biancardi
    email: gaetano.biancardi@accenture.com
coreFunction:
    exposedAPIs:
    - name: ServiceCatalogManagement
      id: TMF633
      isRequired: yes
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF633_ServiceCatalog/blob/master/TMF633-ServiceCatalog-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-TMF633_ServiceCatalog
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceCatalog/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceCatalog/v4/docs
      port: 8080
      resources:
      - catalog:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - category:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - serviceSpecification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - serviceCandidate:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - exportJob:
        - POST
        - GET
        - GET /id
        - DELETE
      - importJob :
        - POST
        - GET
        - GET /id
        - DELETE
    - name: ServiceQualityManagement
      id: TMF633
      isRequired: yes
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF657_ServiceQualityManagement/blob/master/TMF657-ServiceQualityManagement-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-ServiceQualityManagement
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualityManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualityManagement/v4/docs
      port: 8080
      resources:
      - serviceLevelSpecification:
        - GET
        - GET/id
        - POST
        - PATCH
        - DELETE
      - serviceLevelObjective:
        - GET
        - GET/id
        - POST
        - PATCH
        - DELETE       
      - serviceLevelSpecParameter:
        - GET
        - GET/id
        - POST
        - PATCH
        - DELETE               
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: no
      version: 4.0
      specification: ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-ProcessFlowManagement
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
      port: 8080
      resources: 
      - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
      - taskFlow:
          - PATCH
          - GET
          - GET /id
    - name: Event
      id: TMF688
      isRequired: no
      version: 4.0
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-PromotionManagement
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      port: 8080
      resources: 
      - listener:  
        - POST
      - hub:
        - POST
        - DELETE
    dependantAPIs:
    - name: ResourceCatalog
      id: TMF634
      isRequired: no
      version: 4.0
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF688-ResourceCatalog/master/TMF688-ResourceCatalog-v4.0.0.swagger.json
      apitype: openapi
      resources:
      - resourceSpecification:
        - GET
        - GET /id
    - name: PartyRoleManagement
      id: TMF669
      isRequired: no
      version: 4.0
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      apitype: openapi
      resources:  
      - PartyRole:
        - GET
        - GET /id
    - name: PartyManagement
      id: TMF632
      isRequired: no
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF632_PartyManagement/blob/master/TMF632-Party-v4.0.0.swagger.json
      apitype: openapi
      resources:  
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id        
    - name: EntityCatalogManagement
      id: TMF662
      isRequired: no
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF662_EntityCatalog/blob/master/TMF662-EntityCatalog-v4.0.0.swagger.json
      apitype: openapi
      resources: 
      - entitySpecification::
        - GET
        - GET /id
      - associationSpecification:
        - GET
        - GET /id
    - name: UserRoleAndPermission
      version: 4.0
      id : TMF672
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRoleAndPermission/master/TMF672-UserRoleAndPermission-v4.0.0.swagger.json 
      apitype: openapi
      resources:
      - permission:
        - GET
        - GET /id  
    - name: Event 
      id: TMF688
      isRequired: no
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json      
      apitype: openapi     
      resources: 
      - event:
        - GET
        - GET /id                                  
    publishedEvents: 
    - name: ServiceCatalogManagement
      specification: https://github.com/tmforum-apis/TMF633_ServiceCatalog/blob/master/TMF633-ServiceCatalog-v4.0.0.swagger.json
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceCatalog/hub
      implementation: /{{.Release.Name}}-ServiceCatalog
      apitype: openapi
      port: 80
      -resources: 
         ServiceCatalogManagement:
          - serviceSpecificationCreateEvent
          - serviceSpecificationChangeEvent
          - serviceSpecificationDeleteEvent
          - serviceCategoryCreateEvent
          - serviceCategoryChangeEvent
          - serviceCategoryDeleteEvent
          - serviceCandidateCreateEvent
          - serviceCandidateChangeEvent   
          - serviceCandidateDeleteEvent    
          - serviceCatalogCreateEvent
          - serviceCatalogChangeEvent 
          - serviceCatalogDeleteEvent
          - serviceCatalogBatchEvent
    - name: ServiceQualityManagement
      specification: https://github.com/tmforum-apis/TMF657_ServiceQualityManagement/blob/master/TMF657-ServiceQualityManagement-v4.0.0.swagger.json
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualityManagement/hub
      implementation: /{{.Release.Name}}-ServiceQualityManagement
      apitype: openapi
      port: 80
      -resources: 
        ServiceQuality:
          - serviceLevelObjectiveCreateEvent
          - serviceLevelObjectiveChangeEvent
          - serviceLevelObjectiveAttributeValueChangeEvent
          - serviceLevelSpecificationCreateEvent
          - serviceLevelSpecificationDeleteEvent
          - serviceLevelSpecificationAttributeValueChangeEvent  
    - name: ProcessFlowManagement
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      apitype: openapi
      port: 80
      -resources: 
        ProcessFlowManagement:
        - processFlowCreateEvent
        - processFlowStateChangeEvent
        - processFlowStateDeleteEvent
        - processFlowStateAttributeValueChangeEvent
        - taskFlowCreateEvent
        - taskFlowStateChangeEvent
        - taskFlowDeleteEvent
        - taskFlowAttributeValueChangeEvent
        - taskFlowInformationRequiredEvent
    subscribedEvents: 
    - name: ResourceCatalogManagement
      specification:  https://github.com/tmforum-apis/TMF634_ResourceCatalog/blob/master/TMF634-ResourceCatalog-v4.1.0.swagger.json
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/call-back
      port: 80
      implementation: /{{.Release.Name}}-ResourceCatalog
      apitype: openapi
      resources:   
      - ResourceCatalog:
        - resourceSpecificationCreateEvent
        - resourceSpecificationChangeEvent
        - resourceSpecificationDeleteEvent         
    - name: EntityCatalogManagement
      specification:  https://github.com/tmforum-apis/TMF662_EntityCatalog/blob/master/TMF662-EntityCatalog-v4.0.0.swagger.json
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EntityCatalog/call-back
      port: 80
      implementation: /{{.Release.Name}}-EntityCatalog
      apitype: openapi
      resources:   
      - ResourceCatalog:
        - entitySpecificationCreateEvent
        - entitySpecificationAttributeValueChangeEvent
        - entitySpecificationChangeEvent
        - entitySpecificationDeleteEvent             
managementFunction: []
reportingFunction: []
securityFunction: []
  
