component:
  id: TMFC022
  name: partyprivacymanagement
  functionalBlock: PartyManagement
  publicationDate: 2026-05-21T00:00:00.000Z
  version: "1.2.0"
  storageClassName: default
  apipolicy:
    apiKeyVerification:
      enabled: false
      location: "header"
    rateLimit:
      enabled: false
      identifier: "IP"
      limit: "6"
      interval: "pm"
    quota:
      identifier: ""
      limit: ""
    OASValidation:
      requestEnabled: false
      responseEnabled: false
      allowUnspecifiedHeaders: false
      allowUnspecifiedQueryParams: false
      allowUnspecifiedCookies: false
    CORS:
      enabled: false
      allowCredentials: false
      allowOrigins: "https://allowed-origin.com"
      handlePreflightRequests:
        enabled: false
        allowHeaders: "Accept, Content-Type"
        allowMethods: "GET, POST"
        maxAge: 36000
    template: ""

security:
  canvasSystemRole: Admin

mongodb:
  port: 27017
  database: tmf

image:
  pullPolicy: Always

api:
  image: "akumartmf/privacymanagementv5api:0.2"
  versionLabel: privacymanagementv5api-0.2
  port: 8080
  otlp:
    console:
      enabled: false
    protobuffCollector:
      enabled: false
      url: http://observability-opentelemetry-collector.monitoring.svc.cluster.local:4318/v1/traces

metrics:
  image: "akumartmf/privacymanagementv5metrics:0.1"

secretsManagement:
  podSelector:
    namespace: components
    name: ""
    serviceaccount: ""

canvasinfo:
  host: ""
  basepath: ""
