component:
  id: tmfc031
  name: tmfc031-billcalculation
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf669: tmforumorg/tmfc031-tmf669-v4.0.0:latest
  tmf678: tmforumorg/tmfc031-tmf678-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
