apiVersion: oda.tmforum.org/v1beta4
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  componentMetadata:
    description: Workforce Management provides capabilities to describe teams, organizations,
      skills and availability of sales / technical experts. It provides the ability
      in reserving time slots to carry out assigned task (internal or customer facing).
      It allows the reservation (and their updates / reschedule) of appointments and
      interventions. option, etc.)
    eTOMs:
    - 1.5.4_Resource_Readiness_&_Support_v23.0
    - 1.5.4.8_Manage_Field_Workforce_v23.0
    functionalBlock: Production
    functionalFrameworkFunctions:
    - 119_Center_Time_Management_v23.0
    - 1326_Work_List_Management_v23.0
    - 113_Care-center_Compliance_Management_v23.0
    - 116_Center_Activity_Management_v23.0
    - 449_Resource_Change_Project_Collaboration_v23.0
    - 1184_Workforce_Agenda_Booking_v23.0
    - 1183_Workforce_Availability_Check_v23.0
    - 114_Care-center_Case_Queing_v23.0
    - 554_Workforce_Appointment_Schedule_Configuration_v23.0
    - 555_Workload_Forecasting_v23.0
    - 556_Workforce_Availability_Management_v23.0
    - 558_Workforce_Dispatchability_Management_v23.0
    - 482_Workforce_Management_v23.0
    - 561_Workforce_Scheduling_v23.0
    id: TMFC046
    maintainers:
    - email: components@tmforum.org
      name: Redacted
      url: Redacted
    name: WorkforceManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    publicationDate: 2024-04-18 00:00:00
    status: specified
    version: 1.1.0
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      id: TMF632
      name: party-management-api
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      required: false
      resources:
      - PartyRole:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF701
      name: process-flow-management-api
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - PATCH
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      developerUI: not_defined
      id: TMF646
      implementation: not_defined
      name: appointment-management-api
      path: not_defined
      port: 8080
      required: true
      resources:
      - appointment:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      - searchTimeSlot:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF646_Appointment/4.0.0/swagger/TMF646_Appointment_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      developerUI: not_defined
      id: TMF701
      implementation: not_defined
      name: process-flow-management-api
      path: not_defined
      port: 8080
      required: false
      resources:
      - processFlow:
        - GET
        - GET /id
        - POST
        - DELETE /id
      - taskFlow:
        - GET
        - GET /id
        - PATCH /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
  eventNotification:
    publishedEvents:
    - apiType: openapi
      id: TMF646
      implementation: /{{.Release.Name}}-appointmentManagement
      name: appointmentManagement
      port: 80
      resources:
      - appointmentStateChange
      - appointmentCreateEvent
      - appointmentAttributeValueChangeEvent
      - appointmentDeleteEvent
      - searchTimeSlotCreateEvent
      - searchTimeSlotAttributeValueChangeEvent
      - searchTimeSlotStateChangeEvent
      - searchTimeSlotDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF646_AppointmentManagement/blob/master/TMF646-Appointment-v4.0.0.swagger.json
        version: v4.0.0
    subscribedEvents:
    - apiType: openapi
      id: TMF669
      name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleCreateEvent
      - partyRoleAttributeValueChangeEvent
      - partyRoleStateChangeEvent
      - partyRoleDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF701
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
        version: v4.0.0
  managementFunction:
    dependentAPIs:
    - apiType: dependentAPI_apiType
      id: dependentAPI_id
      name: dependentAPI_name
      required: false
      resources: []
      specification:
      - url: dependentAPI_spec
        version: dependentAPI_version
      version: dependentAPI_version
    exposedAPIs:
    - apiType: prometheus
      developerUI: exposedAPI_developerUI
      id: exposedAPI_id
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
      required: false
      resources: []
      specification:
      - url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        version: v4.0.0
      version: exposedAPI_version
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    dependentAPIs: []
    exposedAPIs:
    - apiType: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      id: TMF669
      implementation: '{{.Release.Name}}-partyroleapi'
      name: party-role-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      required: true
      resources: []
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
