apiVersion: oda.tmforum.org/v1beta4
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  componentMetadata:
    description: The Product Configurator ODA Component is empowering sales by offering
      the right product combinations, controlling discounting, and automating approvals
      through support of configuration, pricing and quote generation activities.
    functionalBlock: CoreCommerceManagement
    id: TMFC027
    maintainers:
    - email: components@tmforum.org
      name: Redacted
      url: Redacted
    name: ProductConfigurator
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    publicationDate: 2023-11-27
    status: specified
    version: 2.1.1
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      id: TMF637
      name: product-inventory-management-api
      required: true
      resources:
      - product:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF637_Product_Inventory/4.0.0/swagger/TMF637_Product_Inventory_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF620
      name: product-catalog-management-api
      required: true
      resources:
      - catalog:
        - GET
        - GET /id
      - category:
        - GET
        - GET /id
      - productOffering:
        - GET
        - GET /id
      - productOfferingPrice:
        - GET
        - GET /id
      - productSpecification:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF620_Product_Catalog/4.1.0/swagger/TMF620_Product_Catalog_Management_API_v4.1.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF622
      name: product-ordering-management-api
      required: true
      resources:
      - productOrder:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF622_Product_Ordering/4.0.0/swagger/TMF622_Product_Ordering_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF632
      name: party-management-api
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF666
      name: account-management-api
      required: false
      resources:
      - billingAccount:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF666_Account/4.0.0/swagger/TMF666_Account_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      required: false
      resources:
      - partyRole:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF673
      name: geographic-address-management-api
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      - geographicSubAddress:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF673_Geographic_Address/4.0.0/swagger/TMF673_Geographic_Address_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF674
      name: geographic-site-management-api
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF674_Geographic_Site/4.0.0/swagger/TMF674_Geographic_Site_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF701
      name: process-flow-management-api
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF662
      name: entity-catalog-management-api
      required: false
      resources:
      - entityCatalog:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF662_Entity_Catalog/4.0.0/swagger/TMF662_Entity_Catalog_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF921
      name: intent-management-api
      required: false
      resources:
      - intent:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF921_Intent/4.0.0/swagger/TMF921_Intent_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      developerUI: not_defined
      id: TMF679
      implementation: not_defined
      name: product-offering-qualification-management-api
      path: not_defined
      port: 8080
      required: true
      resources:
      - productOfferingQualification:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF679_Product_Offering_Qualification/4.0.0/swagger/TMF679_Product_Offering_Qualification_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      developerUI: not_defined
      id: TMF760
      implementation: not_defined
      name: product-configuration-management-api
      path: not_defined
      port: 8080
      required: true
      resources:
      - checkProductConfiguration:
        - GET
        - GET/id
        - POST
      - queryProductConfiguration:
        - GET
        - GET/id
        - POST
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF760_Product_Configuration/5.0.0/swagger/TMF760-ProductConfiguration-v5.0.0.oas.yaml
        version: null
    - apiType: openapi
      developerUI: not_defined
      id: TMF701
      implementation: not_defined
      name: process-flow-management-api
      path: not_defined
      port: 8080
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - GET
        - get /id
        - PATCH
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
  eventNotification:
    publishedEvents:
    - apiType: openapi
      id: null
      implementation: /{{.Release.Name}}-ProductConfiguration
      name: ProductConfiguration
      port: 80
      resources:
      - checkProductConfigurationAttributeValueChangeEvent
      - checkProductConfigurationCreateEvent
      - checkProductConfigurationDeleteEvent
      - checkProductConfigurationStateChangeEvent
      specification: ''
    - apiType: openapi
      id: null
      implementation: /{{.Release.Name}}-ProductOfferingQualification
      name: ProductOfferingQualification
      port: 80
      resources:
      - queryProductConfigurationAttributeValueChangeEvent
      - queryProductConfigurationCreateEvent
      - queryProductConfigurationDeleteEvent
      - queryProductConfigurationStateChangeEvent
      specification: ''
    - apiType: openapi
      id: TMF679
      implementation: /{{.Release.Name}}-pdtquali
      name: ProductConfiguration
      port: 80
      resources:
      - ProductOfferingQualificationCreateEvent
      - ProductOfferingQualificationAttributeValueChangeEvent
      - ProductOfferingQualificationStateChangeEvent
      - ProductOfferingQualificationDeleteEvent
      - ProductOfferingQualificationInformationRequiredEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF679_ProductOfferingQualificationManagement/master/TMF679-ProductOfferingQualificationManagement-v4.0.0.swagger.json
        version: v4.0.0
    subscribedEvents:
    - apiType: openapi
      id: TMF622
      name: ProductCatalogManagement
      port: 80
      resources:
      - CatalogCreateEvent
      - CatalogAttributeValueChangeEvent
      - CatalogStateChangeEvent
      - ProductOfferingCreateEvent
      - ProductOfferingAttributeValueChangeEvent
      - ProductOfferingStateChangeEvent
      - ProductOfferingDeleteEvent
      - ProductOfferingPriceCreateEvent
      - ProductOfferingPriceAttributeValueChangeEvent
      - ProductOfferingPriceStateChangeEvent
      - ProductOfferingPriceDeleteEvent
      - ProductSpecificationCreateEvent
      - ProductSpecificationAttributeValueChangeEvent
      - ProductSpecificationStateChangeEvent
      - ProductSpecificationDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF622-ProductCatalogManagement/blob/master/TMF622-ProductCatalogManagement-v4.0.0.swagger.json
        version: v4.0.0
  managementFunction:
    dependentAPIs:
    - apiType: dependentAPI_apiType
      id: dependentAPI_id
      name: dependentAPI_name
      required: false
      resources: []
      specification:
      - url: dependentAPI_spec
        version: dependentAPI_version
      version: dependentAPI_version
    exposedAPIs:
    - apiType: prometheus
      developerUI: exposedAPI_developerUI
      id: exposedAPI_id
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
      required: false
      resources: []
      specification:
      - url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        version: v4.0.0
      version: exposedAPI_version
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    dependentAPIs: []
    exposedAPIs:
    - apiType: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      id: TMF669
      implementation: '{{.Release.Name}}-partyroleapi'
      name: party-role-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      required: true
      resources: []
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
