apiVersion: oda.tmforum.org/v1beta1
kind: component
metadata:
  name: TMFC023-PartyInteractionManagement
  labels:
    oda.tmforum.org/componentName: TMFC023-PartyInteractionManagement
    oda.tmforum.org/funtionalBlockName: PartyManagement
spec:
  type: TMFC023-PartyInteractionManagement
  version: 1.1.0
  description: "Simple Party Interaction ODA-Component from Open-API reference implementation." 
  maintainers:
  - name: Gaetano Biancardi
    email: gaetano.biancardi@accenture.com
  owners:
  - name: Gaetano Biancardi
    email: gaetano.biancardi@accenture.com
coreFunction:
    exposedAPIs:
    - name: PartyInteractionManagement
      id: TMF683
      isRequired: yes
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF683_PartyInteraction/blob/master/partyInteractionManagement_TMF_v1.0.0Review2.json
      implementation: /{{.Release.Name}}-PartyInteractionManagement
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyInteractionManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyInteractionManagement/v4/docs
      port: 8080
      resources:
        - PartyInteraction:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: not
      version: 4.0
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-ProcessFlowManagement
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
      port: 8080
      resources: 
      - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
      - taskFlow:
          - PATCH
          - GET
          - GET /id
    - name: Event
      id: TMF688
      isRequired: not
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-PromotionManagement
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4/docs
      port: 8080
      rerouces: 
      - event:  
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
    dependantAPIs:
    - name: PartyManagement
      id: TMF632
      isRequired: not
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF632_PartyManagement/blob/master/TMF632-Party-v4.0.0.swagger.json
      apitype: openapi
      resources:  
      - individual:
        - GET    
      - organization:
        - GET      
    - name: PartyRoleManagement
      id: TMF669
      isRequired: not
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF669_PartyRole/blob/master/TMF669-PartyRole-v4.0.0.swagger.json
      apitype: openapi
      resources:  
      - PartyRoleManagement:
        - GET
        - GET /id
    - name: UserRolePermission 
      id: TMF672
      isRequired: not
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF672_UserRolesPermissions/blob/master/TMF672-UserRolePermission-v4.0.0.swagger.json     
      apitype: openapi     
      resources: 
      - permission:
        - GET
        - GET /id    
    - name: EntityCatalogManagement 
      id: TMF662
      isRequired: not
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF662_EntityCatalog/blob/master/TMF662-EntityCatalog-v4.0.0.swagger.json     
      apitype: openapi     
      resources: 
      - entitySpecification:
        - GET
        - GET /id      
      - associationSpecification:
        - GET
        - GET /id      
    - name: DocumentgManagement 
      id: TMF667
      isRequired: not
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF667_Document/blob/master/TMF667-Document-v4.0.0.swagger.json     
      apitype: openapi     
      resources: 
      - GET
      - GET /id  
    - name: Event 
      id: TMF688
      isRequired: not
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json      
      apitype: openapi     
      resources: 
      - event:
        - GET
        - GET /id                                  
    publishedEvents: 
    - name: PartyInteractionManagement
      specification: https://github.com/tmforum-apis/TMF683_PartyInteraction/blob/master/partyInteractionManagement_TMF_v1.0.0Review2.json
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyInteractionManagement/hub
      implementation: /{{.Release.Name}}-PartyInteractionManagementEvent
      apitype: openapi
      port: 80
      -resources: 
         partyInteractionManagement:
         - partyInteractionCreateEvent
         - partyInteractionAttributeValueChangeEvent
         - partyInteractionDeleteEvent
         - partyInteractionStatusChangeEvent   
    - name: ProcessFlowManagement
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      apitype: openapi
      port: 80
      -resources: 
        ProcessFlowManagement:
        - processFlowCreateEvent
        - processFlowStateChangeEvent
        - processFlowStateDeleteEvent
        - processFlowStateAttributeValueChangeEvent
        - taskFlowCreateEvent
        - taskFlowStateChangeEvent
        - taskFlowDeleteEvent
        - taskFlowAttributeValueChangeEvent
        - taskFlowInformationRequiredEvent
    subscribedEvents: 
    - name: PartyManagement
      specification: https://github.com/tmforum-apis/TMF632_PartyManagement/blob/master/TMF632-Party-v4.0.0.swagger.json
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/call-back
      port: 80
      implementation: /{{.Release.Name}}-PartyManagement
      apitype: openapi
      resources:   
      - Individual:
        - IndividualCreateEvent
        - IndividualAttributeValueChangeEvent
        - IndividualStateChangeEvent
        - IndividualDeleteEvent
      - Organization:
        - OrganizationCreateEvent
        - OrganizationAttributeValueChangeEvent
        - OrganizationStateChangeEvent
        - OrganizationDeleteEvent    
    - name: PartyRoleManagement
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json  
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/call-back
      port: 80
      implementation: /{{.Release.Name}}-PartyRoleManagement
      apitype: openapi
      resources:   
      - PartyRole:
        - PartyRoleCreateEvent
        - PartyRoleAttributeValueChangeEvent
        - PartyRoleStateChangeEvent
        - PartyRoleDeleteEvent                
    - name: DocumentgManagement
      specification: https://github.com/tmforum-apis/TMF667_Document/blob/master/TMF667-Document-v4.0.0.swagger.json    
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/DocumentgManagement/call-back
      port: 80
      implementation: /{{.Release.Name}}-DocumentgManagementEvent
      apitype: openapi
      resources:   
      - documentManagement:
        - documentChangeEvent
        - documentSpecificationAttributeValueChangeEvent 
    - name: ProcessFlowManagement
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      apitype: openapi
      port: 80
      -resources: 
        ProcessFlowManagement:
        - processFlowCreateEvent
        - processFlowStateChangeEvent
        - taskFlowCreateEvent
        - taskFlowStateChangeEvent
        - taskFlowDeleteEvent
management: []
reporting: []
security: []
  