apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF632
      name: party-management-api
      apiSDO: tmForum
      required: true
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/5.0.0/swagger/TMF632-Party_Management-v5.0.0.oas.yaml
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
    - id: TMF669
      name: party-role-management-api
      apiSDO: tmForum
      required: true
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/5.0.0/swagger/TMF669-Party_Role_Management-v5.0.0.oas.yaml
        resources:
        - partyRole:
          - GET
          - GET /id
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        resources:
        - PartyRole:
          - GET
          - GET /id
    - id: TMF670
      name: payment-method-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF670_Payment_Method/4.0.0/swagger/TMF670_Payment_Method_Management_API_v4.0.0_swagger.json
        resources:
        - paymentMethod:
          - GET
          - GET /id
    - id: TMF676
      name: payment-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF676_Payment/4.0.0/swagger/TMF676_Payment_Management_API_v4.0.0_swagger.json
        resources:
        - payment:
          - GET
          - GET /id
    - id: TMF701
      name: process-flow-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.1.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        resources:
        - processFlow:
          - POST
          - GET
          - GET /id
          - PATCH
    exposedAPIs:
    - id: TMF666
      name: account-management-api
      apiSDO: tmForum
      required: true
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF666_Account/5.0.0/swagger/TMF666-Account_Management-v5.0.0.oas.yaml
        resources:
        - billFormat:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
        - billPresentationMedia:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
        - billingAccount:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
        - billingCycleSpecification:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
        path: not_defined
        developerUI: not_defined
        implementation: not_defined
        port: 8080
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF666_Account/4.0.0/swagger/TMF666_Account_Management_API_v4.0.0_swagger.json
        resources:
        - billingAccount:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
        - billingCycleSpecification:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
        - billFormat:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
        - billPresentationMedia:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
        path: not_defined
        developerUI: not_defined
        implementation: not_defined
        port: 8080
    - id: TMF701
      name: process-flow-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.1.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        resources:
        - processFlow:
          - GET
          - GET /id
          - POST
          - DELETE /id
        - taskFlow:
          - GET
          - GET /id
          - PATCH /id
        path: not_defined
        developerUI: not_defined
        implementation: not_defined
        port: 8080
  componentMetadata:
    id: TMFC024
    name: BillingAccountManagement
    version: 2.2.1
    description: The billing account management component aims to provide all the
      needed functionalities to create, configure and modify billing accounts. BAM
      component has the goal to support and handle the following capabilities/ functionalities.
      Set-up/ creation of Billing account. Associate payment plan(s), Associate payment
      method(s) - optional, Account taxes/ fees exception management, Define account
      associations, Provide account balance details, Set-up Billing contacts, Set-up
      Billing preferences (e.g., bill cycle frequency, invoice media type, invoice
      template option, etc.)
    publicationDate: 2026-05-21
    status: roadmap
    functionalBlock: PartyManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.3.10|Customer_Bill_Payments_&_Receivables_Management|v23.0
    - 1.3.10.1|Manage_Customer_Billing_Account|v23.0
    functionalFrameworkFunctions:
    - 77|Billing_Account_Information_Configuration|v23.0
    - 73|Billing_Account_Reporting|v23.0
    - 76|Billing_Account_Structure_Configuration|v23.0
    - 75|Billing_Accounts_Creation|v23.0
    - 248|Customer_Billing_Hierarchies_Management|v23.0
    SIDs:
    - Customer_Domain|Customer_Billing_Account_ABE|v25.0
  managementFunction:
    exposedAPIs:
    - name: metrics
      id: exposedAPI_id
      apiSDO: not_defined
      required: false
      specification:
      - version: v4.0.0
        url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        apiType: prometheus
        implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
        port: 4000
        resources: []
        developerUI: exposedAPI_developerUI
    dependentAPIs: []
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - id: TMF669
      name: partyrole
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        resources: []
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
        implementation: '{{.Release.Name}}-partyroleapi'
        port: 8080
    - id: TMF672
      name: user-role-permission-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/4.0.0/swagger/TMF672_User_Role_Permission_Management_API_v4.0.0_swagger.json
        resources: []
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v4/docs
        implementation: '{{.Release.Name}}-userrolepermissionapi'
        port: 8080
      - version: v5.1.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/5.1.0/swagger/TMF672-User_Role_Permission_Management_API-v5.1.0.oas.yaml
        resources: []
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v5
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v5/docs
        implementation: '{{.Release.Name}}-userrolepermissionapi'
        port: 8080
    dependentAPIs: []
  eventNotification:
    publishedEvents:
    - implementation: /{{.Release.Name}}-accmngt
      name: AccountManagement
      port: 80
      resources:
      - billingAccountAttributeValueChangeEvent
      - billingAccountStateChangeEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF666_AccountManagement/master/TMF666-AccountManagement-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF666
      apiSDO: not_defined
    subscribedEvents:
    - name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleCreateEvent
      - partyRoleAttributeValueChangeEvent
      - partyRoleStateChangeEvent
      - partyRoleDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
        version: v4.0.0
      id: TMF669
      apiSDO: not_defined
