apiVersion: oda.tmforum.org/v1beta4
kind: Component
metadata:
  labels:
    oda.tmforum.org/componentName: '{{.Release.Name}}-{{.Values.component.name}}'
  name: '{{.Release.Name}}-{{.Values.component.name}}'
spec:
  componentMetadata:
    description: The Product Catalog Management ODA Component is responsible for organizing
      the collection of Products and Product Offerings specifications that identify
      and define all requirements of a product or a product offering that can be commercialized.
    eTOMs:
    - 1.2.20_Product_Catalog_Lifecycle_Management_v23.0
    - 1.1.19_Loyalty_Program_Management_v23.0
    - 1.1.19.1_Loyalty_Program_Development_&_Retirement_v23.0
    - 1.2.7_Product_Specification_&_Offering_Development_&_Retirement_v23.0
    - 1.2.8.7_Implement_Product_Capacity_Plan_v23.0
    - 1.6.4_Business_Partner_Offering_Development_&_Retirement_v23.0
    - 1.2.8_Product_Capacity_Management_v23.0
    - 1.2.22_Product_Catalog_Content_Management_v23.0
    - 1.2.21_Product_Catalog_Operational_Readiness_Management_v23.0
    - 1.2.19_Product_Catalog_Planning_Management_v23.0
    - 1.2.23_Product_Specification_Management_v23.0
    - 1.2.8.7.1_Specify_Required_Product_Capacity_v23.0
    functionalBlock: CoreCommerce
    functionalFrameworkFunctions:
    - 3_Repository_Entity_Relations_Configuration_v23.0
    - 4_Repository_Entity_Grouping_Configuration_v23.0
    - 6_Repository_Entity_Data_Model_Configuration_v23.0
    - 11_Repository_Entity_Hierarchy_Management_v23.0
    - 123_Product_Catalog_Browsing_v23.0
    - 210_Centralized_Ordering_Rules_Management_v23.0
    - 360_Contract_Template_Creation_v23.0
    - 407_Product_Modeling_Support_v23.0
    - 408_Product_Retirement_v23.0
    - 415_Product_Strategy_linking_v23.0
    - 649_Product_Sourcing_Registration_v23.0
    - 650_Partner_Product_Certification_v23.0
    - 662_Sourcing_Reference_Data_Collection_v23.0
    - 721_Customer_Order_Rules_Configuration_v23.0
    - 722_Order_Rules_Retrieval_v23.0
    - 992_Entity_Management_Notification_v23.0
    - 993_Entity_Management_Reporting_v23.0
    - 1050_Product_Onboarding_Management_v23.0
    - 1053_Onboarded_Product_Workflows_Definition_v23.0
    - 1076_Product_Specification_Design_v23.0
    - 1077_Product_Offering_Design_v23.0
    - 1078_Product_Specification_and_Offering_Change_Auditing_v23.0
    - 1079_Product_Specification_and_Offering_Repository_Management_v23.0
    - 238_Customer_Loyalty_Rules_Management_v23.0
    - 416_Product_Propositions_Operations_Planning_v23.0
    - 417_Product_Strategy_to_Proposition_Alignment_v23.0
    - 418_Product_Strategy/Propositions_Creation_v23.0
    - 419_Product_Strategy_performance_reporting_v23.0
    - 897_Building_Access_Control_v23.0
    - 900_Authorization_Control_Management_v23.0
    id: TMFC001
    maintainers:
    - email: components@tmforum.org
      name: Redacted
      url: Redacted
    name: ProductCatalogManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    publicationDate: 2024-11-12 00:00:00
    status: specified
    version: 2.1.0
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      name: service-catalog-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF633_Service_Catalog/4.0.0/swagger/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: party-role-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: party-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: resource-catalog-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF634_Resource_Catalog/4.1.0/swagger/TMF634_Resource_Catalog_Management_API_v4.1.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: agreement-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF651_Agreement/4.0.0/swagger/TMF651_Agreement_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: geographic-address-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF673_Geographic_Address/4.0.0/swagger/TMF673_Geographic_Address_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: geographic-site-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF674_Geographic_Site/4.0.0/swagger/TMF674_Geographic_Site_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: geographic-location-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF675_Geographic_Location/4.0.0/swagger/TMF675_Geographic_Location_Management_API_v4.0.0_beta_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: entity-catalog-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF662_Entity_Catalog/4.0.0/swagger/TMF662_Entity_Catalog_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      name: product-catalog-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF620_Product_Catalog/4.1.0/swagger/TMF620_Product_Catalog_Management_API_v4.1.0_swagger.json
        version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      developerUI: not_defined
      implementation: '{{.Release.Name}}-product-catalog-management-api'
      name: product-catalog-management-api
      path: not_defined
      port: 8080
      specification:
      - - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF620_Product_Catalog/4.1.0/swagger/TMF620_Product_Catalog_Management_API_v4.1.0_swagger.json
          version: v4.0.0
    - apiType: openapi
      developerUI: not_defined
      implementation: '{{.Release.Name}}-process-flow-management-api'
      name: process-flow-management-api
      path: not_defined
      port: 8080
      specification:
      - - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
          version: v4.0.0
    - apiType: openapi
      developerUI: not_defined
      implementation: '{{.Release.Name}}-promotion-management-api'
      name: promotion-management-api
      path: not_defined
      port: 8080
      specification:
      - - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF671_Promotion/4.0.0/swagger/TMF671_Promotion_Management_API_v4.0.0_beta_swagger.json
          version: v4.0.0
  eventNotification:
    publishedEvents:
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productspecification/hub
      id: TMF620
      implementation: /{{.Release.Name}}-ProductCatalogManagementEvent
      name: ProductCatalogManagement
      port: 80
      resources:
      - productSpecificationCreate
      - productSpecificationDeleteEvent
      - categoryCreateEvent
      - categoryDeleteEvent
      - productOfferingCreateEvent
      - productOfferingAttributeValueChangeEvent
      - productOfferingStateChangeEvent
      - productOfferingDeleteEvent
      - productOfferingPriceCreateEvent
      - productOfferingPriceAttributeValueChangeEvent
      - productOfferingPriceStateChangeEvent
      - productOfferingPriceDeleteEvent
      - catalogCreateEvent
      - catalogDeleteEvent
      - catalogBatchEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagementEvent/hub
      id: TMF671
      implementation: /{{.Release.Name}}-PromotionManagementEvent
      name: PromotionManagement
      port: 80
      resources:
      - promotionCreateEvent
      - promotionDeleteEvent
      - promotionAttributeValueChangeEvent
      - promotionStateChangeEvent
      - promotionInformationRequiredEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF671_Promotion/blob/master/TMF671-Promotion-v4.1.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      id: TMF701
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
        version: v4.0.0
    subscribedEvents:
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/servicepecification/call-back
      id: TMF633
      implementation: /{{.Release.Name}}-ServiceCatalogManagement
      name: ServiceCatalogManagement
      port: 80
      resources:
      - serviceSpecificationStateChange
      - serviceSpecificationAttributeValueChangeEvent
      - serviceSpecificationCreateEvent
      - serviceSpecificationDeleteEvent
      - resourceSpecificationCreateEvent
      - resourceSpecificationChangeEvent
      - resourceSpecificationDeleteEvent
      specification:
      - url: https://open-api.tmforum.org/TMF633-Servicecatalog-v4.0.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/servicepecification/call-back
      id: TMF632
      implementation: /{{.Release.Name}}-Party
      name: Party
      port: 80
      resources:
      - individualDeleteEvent
      - organizationDeleteEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF632_Party/master/TMF632-Party-v4.0.0.swagger.json
        version: v4.0.0
  publicationDate: '{{.Values.component.publicationDate}}'
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - apiType: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      implementation: '{{.Release.Name}}-partyroleapi'
      name: party-role-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      specification:
      - - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
          version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
