component:
  id: tmfc039
  name: tmfc039-agreementmanagement
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf651: tmforumorg/tmfc039-tmf651-v4.0.0:latest
  tmf669: tmforumorg/tmfc039-tmf669-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
