apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    exposedAPIs:
    - array_id: null
      minItems: null
      apis: []
  componentMetadata:
    id: TMFC009
    name: ServiceQualificationManagement
    version: 1.1.0
    description: The Service Qualification Management component is responsible for
      checking and validating the availability of a service according to specified
      and configured business rules. It must identify at least one technical solution
      (RFSspec) available to deliver the service (CFSspec) and check the availability
      of all the resources types involved in this technical solution. No resources
      are allocated during service qualification. The Service Qualification Management
      component has functionality that includes checking service feasibility status
      and publishing or reporting service qualification results, but also calculated
      service delivery due date and identified need of an appointment at the customer
      site. Service Qualification Management can also be responsible for the cost
      calculation of the technical solution identified, when it cannot be determined
      at catalog design time (complex B2B services). This information will be used
      as an input to price calculation.
    publicationDate: 2023-08-18 00:00:00
    status: specified
    functionalBlock: Production
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.4.5-Service_Configuration_&_Activation-v23.0
    functionalFrameworkFunctions:
    - 319-Service_Feasibility_Checking-v23.0
    - 586-Service_Availability_Validation-v23.0
    - 571-Service_Delivery_Due_Date_Calculation-v23.0
  managementFunction:
    exposedAPIs:
    - name: metrics
      apiType: prometheus
      apiSDO: not_defined
      specification:
      - url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        version: v4.0.0
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
      id: exposedAPI_id
      version: exposedAPI_version
      resources: []
      required: false
      developerUI: exposedAPI_developerUI
    dependentAPIs:
    - name: dependentAPI_name
      id: dependentAPI_id
      version: dependentAPI_version
      apiType: dependentAPI_apiType
      apiSDO: dependentAPI_apiSDO
      specification:
      - url: dependentAPI_spec
        version: dependentAPI_version
      resources: []
      required: false
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - array_id: null
      minItems: null
      apis: []
    dependentAPIs:
    - array_id: null
      minItems: null
      apis: []
  eventNotification:
    publishedEvents:
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/v4/docs
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/hub
      implementation: /{{.Release.Name}}-ServiceQualification
      name: ServiceQualification
      port: 80
      resources:
      - checkServiceQualificationCreateEvent
      - checkServiceQualificationStateChangeEvent
      - checkServiceQualificationInformationRequiredEvent
      - checkServiceQualificationAttributeValueChangeEvent
      - checkServiceQualificationDeleteEvent
      - queryServiceQualificationStateChangeEvent
      - queryServiceQualificationCreateEvent
      - queryServiceQualificationDeleteEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF645_ServiceQualification/master/TMF645-ServiceQualification-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF645
      apiSDO: not_defined
    subscribedEvents: []
