component:
  id: tmfc038
  name: tmfc038-resourceperformancemanagement
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf642: tmforumorg/tmfc038-tmf642-v4.0.0:latest
  tmf669: tmforumorg/tmfc038-tmf669-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
