component:
  id: tmfc020
  name: tmfc020-digitalidentitymanagement
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf669: tmforumorg/tmfc020-tmf669-v4.0.0:latest
  tmf720: tmforumorg/tmfc020-tmf720-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
