apiVersion: oda.tmforum.org/v1beta3
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  name: PartyManagement
  id: TMFC028
  functionalBlock: PartyManagement
  description: 'Party Management component is responsible for the capture, validation
    and management of Parties and their Roles. A Party may be an individual or organization
    that has a relationship with an enterprise. In this context it is responsible
    for the e2e life cycle of: Individual, Organization. and its related sub-entities:Contact
    Medium, Currency and tax exemption certificates, Identification, Community'
  publicationDate: 2024-10-14 00:00:00
  status: specified
  version: 2.1.0
  coreFunction:
    dependentAPIs:
    - id: TMF669
      version: v4.0.0
      apiType: openapi
      name: party-role-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      port: 8080
      resources:
      - partyRole:
        - GET
        - GET /id
    - id: TMF673
      version: v4.0.0
      apiType: openapi
      name: geographic-address-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF673_v4.0.0.swagger.json
      port: 8080
      resources:
      - geographicAddress:
        - GET
        - GET /id
    - id: TMF674
      version: v4.0.0
      apiType: openapi
      name: geographic-site-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF674_v4.0.0.swagger.json
      port: 8080
      resources:
      - geographicSite:
        - GET
        - GET /id
    exposedAPIs:
    - id: TMF632
      version: v4.0.0
      apiType: openapi
      name: party-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v4.0.0.swagger.json
      port: 8080
      resources:
      - individual:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
      - organization:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  managementFunction:
    exposedAPIs:
    - name: metrics
      apiType: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - id: TMF669
      version: v4.0.0
      apiType: openapi
      name: party-role-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      port: 8080
      resources: []
    dependentAPIs: []
  eventNotification:
    publishedEvents:
    - apiType: openapi
      implementation: /{{.Release.Name}}-partymngtapi
      name: Party Management API
      port: 80
      resources:
      - IndividualCreateEvent
      - IndividualAttributeValueChangeEvent
      - IndividualStateChangeEvent
      - IndividualDeleteEvent
      - OrganizationCreateEvent
      - OrganizationAttributeValueChangeEvent
      - OrganizationStateChangeEvent
      - OrganizationDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
      id: TMF632
    subscribedEvents: []
