apiVersion: oda.tmforum.org/v1beta3
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      id: TMF632
      name: party-management-api
      port: 8080
      required: true
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      port: 8080
      required: true
      resources:
      - partyRole:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF667
      name: document-management-api
      port: 8080
      required: false
      resources:
      - document:
        - GET
        - GET /id
        - POST
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF667_v4.0.0.swagger.json
      version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      id: TMF644
      name: privacy-management-api
      port: 8080
      required: true
      resources:
      - partyPrivacyProfileSpecification:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE
      - partyPrivacyProfile:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE
      - partyPrivacyAgreement:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF644_v4.0.0.swagger.json
      version: v4.0.0
  description: 'The Party Privacy Management component aims to: define the Privacy
    Policy rules established by the CSP, according to applicable regulations, such
    as GDPR in Europe, apply these rules to each Party interacting with the CSP and
    to all of their personnal information and personally identifiable information
    (PII); register explicit opt-in and opt-out given by Parties regarding the usage
    of some of their personal information for dedicated purpose, such as marketing.'
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  functionalBlock: PartyManagement
  id: TMFC022
  maintainers:
  - email: components@tmforum.org
    name: Redacted
  managementFunction:
    exposedAPIs:
    - apiType: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  name: PartyPrivacyManagement
  owners:
  - email: Redacted
    name: Redacted
  publicationDate: 2024-08-08
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    dependentAPIs: []
    exposedAPIs:
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      port: 8080
      required: true
      resources: []
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
  status: specified
  version: 1.1.0
