apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    exposedAPIs:
    - id: TMF642
      name: alarm-management-api
      apiSDO: tmForum
      required: true
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF642_Alarm/5.0.0/swagger/TMF642_Alarm_v5.0.1.oas.yaml
        resources:
        - ackAlarm:
          - GET
          - GET /id
          - POST
        - alarm:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
        - clearAlarm:
          - GET
          - GET /id
          - POST
        - groupAlarm:
          - GET
          - GET /id
          - POST
        - unAckAlarm:
          - GET
          - GET /id
          - POST
        - unGroupAlarm:
          - GET
          - GET /id
          - POST
        - commentAlarm:
          - GET
          - GET /id
          - POST
        path: not_defined
        developerUI: not_defined
        implementation: not_defined
        port: 8080
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF642_Alarm/4.0.0/swagger/TMF642_Alarm_Management_API_v4.0.0_swagger.json
        resources:
        - alarm:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
        - ackAlarm:
          - GET
          - GET /id
          - POST
        - unAckAlarm:
          - GET
          - GET /id
          - POST
        - clearAlarm:
          - GET
          - GET /id
          - POST
        - commentAlarmlarm:
          - GET
          - GET /id
          - POST
        - groupAlarm:
          - GET
          - GET /id
          - POST
        - unGroupAlarm:
          - GET
          - GET /id
          - POST
        path: not_defined
        developerUI: not_defined
        implementation: not_defined
        port: 8080
    - id: TMF656
      name: service-problem-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF656_Service_Problem/5.0.0/swagger/TMF656-Service_Problem_Management-v5.0.0.oas.yaml
        resources:
        - problemGroup:
          - POST
        - problemUngroup:
          - POST
        - serviceProblem:
          - GET
          - GET /id
          - POST
          - DELETE
        path: not_defined
        developerUI: not_defined
        implementation: not_defined
        port: 8080
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF656_Service_Problem/4.0.0/swagger/TMF656_Service_Problem_Management_API_v4.0.0_swagger.json
        resources:
        - serviceProblem:
          - GET
          - GET /id
          - POST
          - DELETE
        - problemGroup:
          - POST
        - problemUnGroup:
          - POST
        path: not_defined
        developerUI: not_defined
        implementation: not_defined
        port: 8080
    - id: TMF701
      name: process-flow-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.1.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        resources:
        - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
        - taskFlow:
          - PATCH
          - GET
          - GET /id
        path: not_defined
        developerUI: not_defined
        implementation: not_defined
        port: 8080
    dependentAPIs: []
  componentMetadata:
    id: TMFC043
    name: FaultManagement
    version: 1.1.0
    description: Fault Management component involves identifying, diagnosing, and
      resolving issues that prevent the communication resources and their overlaying
      services from functioning correctly. Its scope covers this functionality at
      the ODA Production layer while business related resolutions are not part of
      its scope. The Fault Management component manages the currently active alarms
      or problem candidates, potentially modifying or enhancing their data to make
      persistent alarms more actionable. It may apply logic to preserve alarms that
      reflect actual problems, eliminating those that are merely symptoms. Various
      actions can be taken using the alarm/problem information as part of the resolution
      process, such as applying automated/automonous corrective actions or opening
      trouble tickets.
    publicationDate: '2026-05-21'
    status: production
    functionalBlock: Production
    owners:
    - name: Redacted
      email: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.5.8|Resource_Trouble_Management|v25.0
    - 1.4.6|Service_Problem_Management|v25.0
    functionalFrameworkFunctions:
    - 1187|Resource_Trouble_Resolution|v25.0
    - 615|Service_Problem_Tracking_&_Management|v25.0
    - 1155|Resource_Diagnostic_and_Test_Analysis|v25.0
    - 1186|Resource_Trouble_Cause_Identification|v25.0
    - 610|Service_Problem_Prioritization|v25.0
    - 612|Service_Problem_Automatic_Correction|v25.0
    - 979|Service_Assurance_Control_Calculation|v25.0
    - 980|Service_Assurance_Trouble_Mitigation|v25.0
    - 1067|Service_Problem_Manual_Correction_Support|v25.0
    SIDs:
    - Resource_Domain|Resource_Trouble_ABE|Resource_Alarm_ABE|v25.0
    - Resource_Domain|Resource_Trouble_ABE|AlarmSeverityAssignmentProfile_BE|v25.0
    - Service_Domain|Service_Problem_ABE|v25.0
  managementFunction:
    exposedAPIs:
    - name: metrics
      id: exposedAPI_id
      apiSDO: not_defined
      required: false
      specification:
      - version: v4.0.0
        url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        apiType: prometheus
        implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
        port: 4000
        resources: []
        developerUI: exposedAPI_developerUI
    dependentAPIs: []
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - id: TMF669
      name: partyrole
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        resources: []
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
        implementation: '{{.Release.Name}}-partyroleapi'
        port: 8080
    - id: TMF672
      name: user-role-permission-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/4.0.0/swagger/TMF672_User_Role_Permission_Management_API_v4.0.0_swagger.json
        resources: []
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v4/docs
        implementation: '{{.Release.Name}}-userrolepermissionapi'
        port: 8080
      - version: v5.1.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/5.1.0/swagger/TMF672-User_Role_Permission_Management_API-v5.1.0.oas.yaml
        resources: []
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v5
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v5/docs
        implementation: '{{.Release.Name}}-userrolepermissionapi'
        port: 8080
    dependentAPIs: []
  eventNotification:
    publishedEvents:
    - id: TMF642
      name: Alarm Management API
      resources:
      - alarmCreateEvent
      - alarmAttributeValueChangeEvent
      - alarmStateChangeEvent
      - alarmDeleteEvent
      - ackAlarmsCreateEvent
      - ackAlarmsStateChangeEvent
      - unAckAlarmsCreateEvent
      - unAckAlarmsStateChangeEvent
      - clearAlarmsCreateEvent
      - clearAlarmsStateChangeEvent
      - commentAlarmsCreateEvent
      - commentAlarmsStateChangeEvent
      - groupAlarmsCreateEvent
      - groupAlarmsStateChangeEvent
      - unGroupAlarmsCreateEvent
      - unGroupAlarmsStateChangeEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF642_v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      apiSDO: not_defined
    - id: TMF701
      name: ProcessFlowManagement
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF701_Process_Management/5.0.0/swagger/TMF701-ProcessManagement-v5.0.0.oas.yaml
        version: v5.0.0
      apiType: openapi
      apiSDO: not_defined
    - id: TMF656
      name: ServiceProblemManagement
      resources:
      - problemAcknowledgementCreateEvent
      - problemAcknowledgementDeleteEvent
      - problemAcknowledgementStateChangeEvent
      - problemGroupCreateEvent
      - problemGroupDeleteEvent
      - problemGroupStateChangeEvent
      - problemUnacknowledgementCreateEvent
      - problemUnacknowledgementDeleteEvent
      - problemUnacknowledgementStateChangeEvent
      - problemUngroupCreateEvent
      - problemUngroupDeleteEvent
      - problemUngroupStateChangeEvent
      - serviceProblemAttributeValueChangeEvent
      - serviceProblemCreateEvent
      - serviceProblemDeleteEvent
      - serviceProblemInformationRequiredEvent
      - serviceProblemStateChangeEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF656_v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      apiSDO: not_defined
    subscribedEvents:
    - id: TMF633
      name: ServiceCatalogManagement
      resources:
      - serviceCatalogCreateEvent
      - serviceCatalogChangeEvent
      - serviceCatalogDeleteEvent
      - serviceCategoryCreateEvent
      - serviceCategoryChangeEvent
      - serviceCategoryDeleteEvent
      - serviceCandidateCreateEvent
      - serviceCandidateChangeEvent
      - serviceCandidateDeleteEvent
      - serviceSpecificationCreateEvent
      - serviceSpecificationChangeEvent
      - serviceSpecificationDeleteEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF633_v4.0.0.swagger.json
        version: v4.0.0
      apiSDO: not_defined
    - id: TMF638
      name: ServiceInventoryManagement
      resources:
      - serviceCreateEvent
      - serviceChangeEvent
      - serviceDeleteEvent
      - serviceStateChangeEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF638_v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      apiSDO: not_defined
    - id: TMF639
      name: ResourceInventoryManagement
      resources:
      - resourceCreateEvent
      - resourceChangeEvent
      - resourceDeleteEvent
      - resourceStateChangeEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF639_v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      apiSDO: not_defined
    - id: TMF673
      name: API Place - GeographicAddress
      resources:
      - geographicAddressValidationStateChangeEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF673_v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      apiSDO: not_defined
    - id: TMF674
      name: GeographicSiteManagement
      resources:
      - geographicSiteCreateEvent
      - geographicSiteAttributeValueChangeEvent
      - geographicSiteStatusChangeEvent
      - geographicSiteDeleteEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF674_v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      apiSDO: not_defined
    - id: TMF675
      name: GeographicLocationManagement
      resources:
      - geographicLocationCreateEvent
      - geographicLocationAttributeValueChangeEvent
      - geographicLocationDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF675_GeographicLocation/blob/master/TMF675-GeographicLocation-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      apiSDO: not_defined
    - id: TMF642
      name: AlarmManagement
      resources:
      - alarmCreateEvent
      - alarmAttributeValueChangeEvent
      - alarmStateChangeEvent
      - alarmDeleteEvent
      - ackAlarmsCreateEvent
      - ackAlarmsStateChangeEvent
      - unAckAlarmsCreateEvent
      - unAckAlarmsStateChangeEvent
      - clearAlarmsCreateEvent
      - clearAlarmsStateChangeEvent
      - commentAlarmsCreateEvent
      - commentAlarmsStateChangeEvent
      - groupAlarmsCreateEvent
      - groupAlarmsStateChangeEvent
      - unGroupAlarmsCreateEvent
      - unGroupAlarmsStateChangeEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF642_v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      apiSDO: not_defined
    - id: TMF656
      name: ServiceProblemManagement
      resources:
      - problemAcknowledgementCreateEvent
      - problemAcknowledgementDeleteEvent
      - problemAcknowledgementStateChangeEvent
      - problemGroupCreateEvent
      - problemGroupDeleteEvent
      - problemGroupStateChangeEvent
      - problemUnacknowledgementCreateEvent
      - problemUnacknowledgementDeleteEvent
      - problemUnacknowledgementStateChangeEvent
      - problemUngroupCreateEvent
      - problemUngroupDeleteEvent
      - problemUngroupStateChangeEvent
      - serviceProblemAttributeValueChangeEvent
      - serviceProblemCreateEvent
      - serviceProblemDeleteEvent
      - serviceProblemInformationRequiredEvent
      - serviceProblemStateChangeEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF656_v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      apiSDO: not_defined
    - id: TMF621
      name: TroubleTicketManagement
      resources:
      - troubleTicketCreateEvent
      - troubleTicketAttributeValueChangeEvent
      - troubleTicketStatusChangeEvent
      - troubleTicketDeleteEvent
      - troubleTicketResolvedEvent
      - troubleTicketInformationRequiredEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF621_v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      apiSDO: not_defined
    - id: TMF632
      name: PartyManagement
      resources:
      - individualDeleteEvent
      - organizationDeleteEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      apiSDO: not_defined
    - id: TMF669
      name: PartyRoleManagement
      resources:
      - partyRoleDeleteEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      apiSDO: not_defined
    - id: TMF662
      name: EntityCatalogManagement
      resources:
      - entityCatalogCreateEvent
      - entityCatalogDeleteEvent
      - entityCatalogItemCreateEvent
      - entityCatalogItemDeleteEvent
      - entitySpecificationCreateEvent
      - entitySpecificationDeleteEvent
      - associationSpecificationCreateEvent
      - associationSpecificationDeleteEvent
      - associationCreateEvent
      - associationDeleteEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF662_v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      apiSDO: not_defined
