apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: {{.Release.Name}}-{{.Values.component.name}}
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  componentMetadata:
    id: {{.Values.component.id}}
    name: {{.Values.component.name}}
    functionalBlock: {{.Values.component.functionalBlock}}
    publicationDate: "{{.Values.component.publicationDate}}"
    status: specified
    version: {{.Values.component.version}}
    description: "The Service Catalog Management component is responsible for organizing the collection of service specifications that identify and define all requirements of a service that can be performed."
    maintainers:
    - name: TMForum
      email: components@tmforum.org
    owners:
    - name: TMForum
      email: components@tmforum.org

  coreFunction:
    exposedAPIs:
    - name: service-catalog-management-api
      id: TMF633
      specification:
      - url: "https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF633_Service_Catalog/4.0.0/swagger/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json"
        implementation: {{.Release.Name}}-svcatalogapi
        apiType: openapi
        gatewayConfiguration:
          apiKeyVerification: {{.Values.component.apipolicy.apiKeyVerification | toYaml | nindent 12}}
          rateLimit: {{.Values.component.apipolicy.rateLimit | toYaml | nindent 12}}
          quota: {{.Values.component.apipolicy.quota | toYaml | nindent 12}}
          OASValidation: {{.Values.component.apipolicy.OASValidation | toYaml | nindent 12}}
          CORS: {{.Values.component.apipolicy.CORS | toYaml | nindent 12}}
          template: "{{.Values.component.apipolicy.template}}"
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/serviceCatalogManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/serviceCatalogManagement/v4/docs
        port: 8080
    - name: service-quality-management-api
      id: TMF657
      specification:
      - url: "https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF657_Service_Quality_Management/4.0.0/swagger/TMF657_Service_Quality_Management_Management_API_v4.0.0_swagger.json"
        implementation: {{.Release.Name}}-svcqualityapi
        apiType: openapi
        gatewayConfiguration:
          apiKeyVerification: {{.Values.component.apipolicy.apiKeyVerification | toYaml | nindent 12}}
          rateLimit: {{.Values.component.apipolicy.rateLimit | toYaml | nindent 12}}
          quota: {{.Values.component.apipolicy.quota | toYaml | nindent 12}}
          OASValidation: {{.Values.component.apipolicy.OASValidation | toYaml | nindent 12}}
          CORS: {{.Values.component.apipolicy.CORS | toYaml | nindent 12}}
          template: "{{.Values.component.apipolicy.template}}"
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/serviceQualityManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/serviceQualityManagement/v4/docs
        port: 8080

    dependentAPIs: []

  eventNotification:
    publishedEvents: []
    subscribedEvents: []

  managementFunction:
    exposedAPIs:
    - name: metrics
      apiType: prometheus
      gatewayConfiguration:
        apiKeyVerification: {{.Values.component.apipolicy.apiKeyVerification | toYaml | nindent 10}}
        rateLimit: {{.Values.component.apipolicy.rateLimit | toYaml | nindent 10}}
        quota: {{.Values.component.apipolicy.quota | toYaml | nindent 10}}
        OASValidation: {{.Values.component.apipolicy.OASValidation | toYaml | nindent 10}}
        CORS: {{.Values.component.apipolicy.CORS | toYaml | nindent 10}}
        template: "{{.Values.component.apipolicy.template}}"
      implementation: {{.Release.Name}}-{{.Values.component.name}}-sm
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000

  securityFunction:
    canvasSystemRole: {{ .Values.security.canvasSystemRole }}
    exposedAPIs: []
