apiVersion: oda.tmforum.org/v1beta1
kind: component
metadata:
  name: TMFC036 - Lead and Opportunity Management
  labels:
    oda.tmforum.org/componentName: TMFC036 - Lead and Opportunity Management
    oda.tmforum.org/funtionalBlockName: Party Management
spec:
  type: TMFC036 - Lead and Opportunity Management
  version: 1.1.0
  description: "Simple Lead and Opportunity Management ODA-Component from Open-API reference implementation." 
  maintainers:
  - name: Gaetano Biancardi
    email: gaetano.biancardi@accenture.com
  owners:
  - name: Gaetano Biancardi
    email: gaetano.biancardi@accenture.com
coreFunction:
    exposedAPIs:
    - name: SalesManagement
      id: TMF699
      isRequired: yes
      version: 4.0
      specification:  https://raw.githubusercontent.com/tmforum-apis/TMF699_SalesManagement/master/TMF699-SalesManagement-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-SalesManagement
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/SalesManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/SalesManagement/v4/docs
      port: 8080
      resources:
        - SalesLead:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
        - SalesOpportunity:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: not
      version: 4.0
      specification: ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-ProcessFlowManagement
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
      port: 8080
      resources: 
      - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
      - taskFlow:
          - PATCH
          - GET
          - GET /id
    - name: Event
      id: TMF688
      isRequired: not
      version: 4.0
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-PromotionManagement
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      port: 8080
      rerouces: 
      - event:  
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
    dependantAPIs:
    - name: PartyManagement
      id: TMF632
      isRequired: not
      version: 4.0
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-Party-v4.0.0.swagger.json
      apitype: openapi
      resources:  
      - individual:
        - GET    
      - organization:
        - GET            
    - name: PartyRoleManagement
      id: TMF669
      isRequired: not
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF669_PartyRole/blob/master/TMF669-PartyRole-v4.0.0.swagger.json
      apitype: openapi
      resources:  
      - PartyRoleManagement:
        - GET
    - name: ProductCatalogManagement 
      id: TMF620
      isRequired: not
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json     
      apitype: openapi     
      resources: 
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE   
    - name: AgreementManagement
      id: TMF651
      isRequired: not
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF651_AgreementManagement/blob/master/TMF651-Agreement-v4.0.0.swagger.json
      apitype: openapi
      resources: 
      - agreement:
        - GET
        - GET /id
      - agreementSpecification:
        - GET
        - GET /id
    - name: QuoteManagement
      id: TMF648
      version: 4.0
      specification:  https://raw.githubusercontent.com/tmforum-apis/TMF648_QuoteManagement/master/TMF648-QuoteManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
      - Quote:
        - GET
        - GET /id    
    - name: Event 
      id: TMF688
      isRequired: not
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json      
      apitype: openapi     
      resources: 
      - event:
        - GET
        - GET /id   
    - name: ProductOrder 
      id: TMF622
      isRequired: not
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/master/TMF622-ProductOrder-v4.0.0.swagger.json
      apitype: openapi     
      resources: 
      - ProductOrder:
        - GET
        - GET /id        
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: not
      version: 4.0
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      apitype: openapi
      resources: 
      - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
      - taskFlow:
          - PATCH
          - GET
          - GET /id                             
    publishedEvents: 
    - name: SalesManagement
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF699_SalesManagement/master/TMF699-SalesManagement-v4.0.0.swagger.json
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/SalesManagement/hub
      implementation: /{{.Release.Name}}-SalesManagement
      apitype: openapi
      port: 80
      -resources: 
        SalesLead:
          - SalesLeadCreateEvent
          - SalesLeadAttributeValueChangeEvent
          - SalesLeadStateChangeEvent
          - SalesLeadDeleteEvent        
          - productSpecificationCreate
        SalesOpportunity:
            - SalesOpportunityCreateEvent
            - SalesOpportunityAttributeValueChangeEvent
            - SalesOpportunityStateChangeEvent
            - SalesOpportunityDeleteEvent 
    - name: ProcessFlowManagement
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      apitype: openapi
      port: 80
      -resources: 
        ProcessFlowManagement:
        - processFlowCreateEvent
        - processFlowStateChangeEvent
        - processFlowStateDeleteEvent
        - processFlowStateAttributeValueChangeEvent
        - taskFlowCreateEvent
        - taskFlowStateChangeEvent
        - taskFlowDeleteEvent
        - taskFlowAttributeValueChangeEvent
        - taskFlowInformationRequiredEvent
    subscribedEvents:   
    - name: PartyManagement
      specification: https://github.com/tmforum-apis/TMF632_PartyManagement/blob/master/TMF632-Party-v4.0.0.swagger.json
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/call-back
      port: 80
      implementation: /{{.Release.Name}}-PartyManagement
      apitype: openapi
      resources:   
      - Individual:
        - IndividualCreateEvent
        - IndividualAttributeValueChangeEvent
        - IndividualStateChangeEvent
        - IndividualDeleteEvent
      - Organization:
        - OrganizationCreateEvent
        - OrganizationAttributeValueChangeEvent
        - OrganizationStateChangeEvent
        - OrganizationDeleteEvent
    - name: ProductCatalogManagement
      specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json  
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductCatalogManagement/call-back
      port: 80
      implementation: /{{.Release.Name}}-ProductCatalogManagement
      apitype: openapi
      resources:   
      - ProductOffering:
        - ProductOfferingCreateEvent
        - ProductOfferingAttributeValueChangeEvent
        - ProductOfferingStateChangeEvent
        - ProductOfferingDeleteEvent     
      - ProductSpecification:
        - ProductSpecificationCreateEvent
        - ProductSpecificationAttributeValueChangeEvent
        - ProductSpecificationStateChangeEvent
        - ProductSpecificationDeleteEvent           
      - ProductOfferingPrice:
        - ProductOfferingPriceCreateEvent
        - ProductOfferingPriceAttributeValueChangeEvent
        - ProductOfferingPriceStateChangeEvent
        - ProductOfferingPriceDeleteEvent  
    - name: ProductOrder
      specification: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/ProductOrder/TMF622-ProductOrder-v4.0.0.swagger.json  
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductCatalogManagement/call-back
      port: 80
      implementation: /{{.Release.Name}}-ProductOrder
      apitype: openapi
      resources:   
      - ProductOrder:
        - ProductOrderCreateEvent 
        - ProductOrderAttributeValueChangeEvent 
        - ProductOrderDeleteEvent 
        - ProductOrderStateChangeEvent 
        - ProductOrderInformationRequiredEvent
    - name: AgreementManagement
      specification: https://github.com/tmforum-apis/TMF651_AgreementManagement/blob/master/TMF651-Agreement-v4.0.0.swagger.json  
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Agreement/call-back
      port: 80
      implementation: /{{.Release.Name}}-Agreement
      apitype: openapi
      resources:   
      - Agreement:
        - AgreementCreateEvent
        - AgreementAttributeValueChangeEvent
        - AgreementStateChangeEvent
        - AgreementDeleteEvent       
      - AgreementSpecification:
        - AgreementSpecificationCreateEvent
        - AgreementSpecificationAttributeValueChangeEvent
        - AgreementSpecificationStateChangeEvent
        - AgreementSpecificationDeleteEvent        
    - name: QuoteManagement
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF648_QuoteManagement/master/TMF648-QuoteManagement-v4.0.0.swagger.json  
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/QuoteManagement/call-back
      port: 80
      implementation: /{{.Release.Name}}-QuoteManagement
      apitype: openapi
      resources:   
      - Quote:
        - QuoteCreateEvent
        - QuoteStateChangeEvent
        - QuoteDeleteEvent
        - QuoteInformationRequiredEvent
        - QuoteAttributeValueChangeEvent                  
    - name: PartyRoleManagement
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json  
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/call-back
      port: 80
      implementation: /{{.Release.Name}}-PartyRoleManagement
      apitype: openapi
      resources:   
      - PartyRole:
        - PartyRoleCreateEvent
        - PartyRoleAttributeValueChangeEvent
        - PartyRoleStateChangeEvent
        - PartyRoleDeleteEvent                    
management: []
reporting: []
security: []
  