component:
  id: tmfc006
  name: tmfc006-servicecatalogmanagement
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf633: tmforumorg/tmfc006-tmf633-v4.0.0:latest
  tmf657: tmforumorg/tmfc006-tmf657-v4.0.0:latest
  tmf669: tmforumorg/tmfc006-tmf669-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
