apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    exposedAPIs:
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
  componentMetadata:
    id: TMFC027
    name: ProductConfigurator
    version: 2.1.1
    description: The Product Configurator component empowers sales by offering the
      right product combinations, controlling discounting, and automating approvals
      through support of configuration, pricing and quote generation activities.
    publicationDate: 2023-11-27
    status: specified
    functionalBlock: CoreCommerce
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs: []
    functionalFrameworkFunctions: []
  managementFunction:
    exposedAPIs:
    - name: metrics
      apiType: prometheus
      apiSDO: not_defined
      specification:
      - url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        version: v4.0.0
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
      id: exposedAPI_id
      version: exposedAPI_version
      resources: []
      required: false
      developerUI: exposedAPI_developerUI
    dependentAPIs:
    - name: dependentAPI_name
      id: dependentAPI_id
      version: dependentAPI_version
      apiType: dependentAPI_apiType
      apiSDO: dependentAPI_apiSDO
      specification:
      - url: dependentAPI_spec
        version: dependentAPI_version
      resources: []
      required: false
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - array_id: null
      minItems: null
      apis: []
    dependentAPIs:
    - array_id: null
      minItems: null
      apis: []
  eventNotification:
    publishedEvents:
    - implementation: /{{.Release.Name}}-ProductConfiguration
      name: ProductConfiguration
      port: 80
      resources:
      - checkProductConfigurationAttributeValueChangeEvent
      - checkProductConfigurationCreateEvent
      - checkProductConfigurationDeleteEvent
      - checkProductConfigurationStateChangeEvent
      specification: ''
      apiType: openapi
      id: null
      apiSDO: not_defined
    - implementation: /{{.Release.Name}}-ProductOfferingQualification
      name: ProductOfferingQualification
      port: 80
      resources:
      - queryProductConfigurationAttributeValueChangeEvent
      - queryProductConfigurationCreateEvent
      - queryProductConfigurationDeleteEvent
      - queryProductConfigurationStateChangeEvent
      specification: ''
      apiType: openapi
      id: null
      apiSDO: not_defined
    - implementation: /{{.Release.Name}}-pdtquali
      name: ProductConfiguration
      port: 80
      resources:
      - ProductOfferingQualificationCreateEvent
      - ProductOfferingQualificationAttributeValueChangeEvent
      - ProductOfferingQualificationStateChangeEvent
      - ProductOfferingQualificationDeleteEvent
      - ProductOfferingQualificationInformationRequiredEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF679_ProductOfferingQualificationManagement/master/TMF679-ProductOfferingQualificationManagement-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF679
      apiSDO: not_defined
    subscribedEvents:
    - name: ProductCatalogManagement
      port: 80
      resources:
      - CatalogCreateEvent
      - CatalogAttributeValueChangeEvent
      - CatalogStateChangeEvent
      - ProductOfferingCreateEvent
      - ProductOfferingAttributeValueChangeEvent
      - ProductOfferingStateChangeEvent
      - ProductOfferingDeleteEvent
      - ProductOfferingPriceCreateEvent
      - ProductOfferingPriceAttributeValueChangeEvent
      - ProductOfferingPriceStateChangeEvent
      - ProductOfferingPriceDeleteEvent
      - ProductSpecificationCreateEvent
      - ProductSpecificationAttributeValueChangeEvent
      - ProductSpecificationStateChangeEvent
      - ProductSpecificationDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF622-ProductCatalogManagement/blob/master/TMF622-ProductCatalogManagement-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF622
      apiSDO: not_defined
