component:
  id: tmfc029
  name: tmfc029-paymentmanagement
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf669: tmforumorg/tmfc029-tmf669-v4.0.0:latest
  tmf670: tmforumorg/tmfc029-tmf670-v4.0.0:latest
  tmf676: tmforumorg/tmfc029-tmf676-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
