component:
  id: tmfc011
  name: tmfc011-resourceordermanagement
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf652: tmforumorg/tmfc011-tmf652-v4.0.0:latest
  tmf669: tmforumorg/tmfc011-tmf669-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
