apiVersion: oda.tmforum.org/v1beta4
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  componentMetadata:
    description: Service Inventory component is responsible for storage and exposure
      of CFS (Customer Facing Service) that are associated to Product Inventory items.
      It is also responsible for RFS (Resource Facing Service) definition, mapping
      between CFS and RFS and mapping with infrastructure/network resources. Service
      Inventory component has functionality that enables inventory items creation,
      inventory organization, inventory search or filter, inventory monitoring and
      tracking, inventory control and inventory auditing.The minimum check to be performed
      at inventory items creation or update is the global consistency with related
      Service Catalog information.
    eTOMs:
    - 1.4.4_Service_Support_Readiness_v23.0
    - 1.4.4.1_Manage_Service_Inventory_v23.0
    functionalBlock: Production
    functionalFrameworkFunctions:
    - 576_Service_Data_Retrieval_v23.0
    - 593_Service_Inventory_Repository_Updating_v23.0
    - 628_Service_to_Resource_Relationship_Management_v23.0
    - 629_Service_to_Resource_Relationship_Synchronization_v23.0
    - 630_Service-Resource_Relationship_Management_Notifications_v23.0
    - 964_Onboarded_Service_Integration_Configuration_v23.0
    - 965_Service_Instance_Lifecycle_Management_v23.0
    - 1344_Service_Topology_Discovery_v23.0
    id: TMFC008
    maintainers:
    - email: components@tmforum.org
      name: Redacted
      url: Redacted
    name: ServiceInventory
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    publicationDate: 2024-11-12 00:00:00
    status: specified
    version: 1.2.0
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      id: TMF633
      name: service-catalog-management-api
      required: true
      resources:
      - serviceSpecification:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF633_Service_Catalog/4.0.0/swagger/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      required: false
      resources:
      - PartyRole:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF639
      name: resource-inventory-management-api
      required: false
      resources:
      - resource:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF639_Resource_Inventory/4.0.0/swagger/TMF639_Resource_Inventory_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF638
      name: service-inventory-management-api
      required: false
      resources:
      - service:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF638_Service_Inventory/4.0.0/swagger/TMF638_Service_Inventory_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF673
      name: geographic-address-management-api
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      - geographicSubAddress:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF673_Geographic_Address/4.0.0/swagger/TMF673_Geographic_Address_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF674
      name: geographic-site-management-api
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF674_Geographic_Site/4.0.0/swagger/TMF674_Geographic_Site_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF675
      name: geographic-location-management-api
      required: false
      resources:
      - geographicLocation:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF675_Geographic_Location/4.0.0/swagger/TMF675_Geographic_Location_Management_API_v4.0.0_beta_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF641
      name: service-ordering-management-api
      required: false
      resources:
      - serviceOrder:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF641_Service_Ordering/4.1.0/swagger/TMF641_Service_Ordering_Management_API_v4.1.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      id: TMF632
      name: party-management-api
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      developerUI: not_defined
      id: TMF638
      implementation: not_defined
      name: service-inventory-management-api
      path: not_defined
      port: 8080
      required: true
      resources:
      - service:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF638_Service_Inventory/4.0.0/swagger/TMF638_Service_Inventory_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    - apiType: openapi
      developerUI: not_defined
      id: TMF701
      implementation: not_defined
      name: process-flow-management-api
      path: not_defined
      port: 8080
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
  eventNotification:
    publishedEvents:
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceInventory/hub
      id: TMF638
      implementation: /{{.Release.Name}}-serviceInventoryEvent
      name: ServiceInventoryManagement
      port: 80
      resources:
      - serviceCreateEvent
      - serviceAttributeValueChangeEvent
      - serviceStateChangeEvent
      - serviceDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF638_ServiceInventoryManagement/blob/master/TMF638_ServiceInventoryManagement-v4.0.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      id: TMF701
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
        version: v4.0.0
    subscribedEvents:
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Resource/call-back
      id: null
      implementation: /{{.Release.Name}}-ResourceInventoryManagement
      name: ResourceInventoryManagement
      port: 80
      resources:
      - resourceDeleteEvent
      specification:
      - url: https://open-api.tmforum.org20-ResourceInventory-v4.0.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceInventory/call-back
      id: null
      implementation: /{{.Release.Name}}-ServiceInventoryManagement
      name: ServiceInventoryManagement
      port: 80
      resources:
      - serviceCreateEvent
      - serviceAttributeValueChangeEvent
      - serviceStateChangeEvent
      - serviceDeleteEvent
      specification:
      - url: https://open-api.tmforum.org20-ServiceInventory-v4.0.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceCatalog/call-back
      id: null
      implementation: /{{.Release.Name}}-ServiceCatalogManagement
      name: ServiceCatalogManagement
      port: 80
      resources:
      - serviceSpecificationDeleteEvent
      specification:
      - url: https://open-api.tmforum.org20-ServiceCatalog-v4.0.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRole/call-back
      id: null
      implementation: /{{.Release.Name}}-GeographicSiteManagement
      name: GeographicSiteManagement
      port: 80
      resources:
      - geographicSiteDeleteEvent
      specification:
      - url: https://open-api.tmforum.org20-GeographicSite-v4.0.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/call-back
      id: null
      implementation: /{{.Release.Name}}-GeographicLocation
      name: GeographicLocation
      port: 80
      resources:
      - geographicLocationDeleteEvent
      specification:
      - url: https://open-api.tmforum.org20-GeographicLocatin-v4.0.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Party/call-back
      id: null
      implementation: /{{.Release.Name}}-PartyManagement
      name: PartyManagement
      port: 80
      resources:
      - individualDeleteEvent
      - organizationDeleteEvent
      specification:
      - url: https://open-api.tmforum.org20-Party-v4.0.0.swagger.json
        version: v4.0.0
    - apiType: openapi
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceOrdering/call-back
      id: null
      implementation: /{{.Release.Name}}-ServiceOrderingManagement
      name: ServiceOrderingManagement
      port: 80
      resources:
      - serviceOrderDeleteEvent
      specification:
      - url: https://open-api.tmforum.org20-ServiceOrdering-v4.0.0.swagger.json
        version: v4.0.0
  managementFunction:
    dependentAPIs:
    - apiType: dependentAPI_apiType
      id: dependentAPI_id
      name: dependentAPI_name
      required: false
      resources: []
      specification:
      - url: dependentAPI_spec
        version: dependentAPI_version
      version: dependentAPI_version
    exposedAPIs:
    - apiType: prometheus
      developerUI: exposedAPI_developerUI
      id: exposedAPI_id
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
      required: false
      resources: []
      specification:
      - url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        version: v4.0.0
      version: exposedAPI_version
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    dependentAPIs: []
    exposedAPIs:
    - apiType: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      id: TMF669
      implementation: '{{.Release.Name}}-partyroleapi'
      name: party-role-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      required: true
      resources: []
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
