apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF632
      version: v4.0.0
      name: party-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
      port: 8080
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
    - id: TMF669
      version: v4.0.0
      name: party-role-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
      port: 8080
      resources:
      - PartyRole:
        - GET
        - GET /id
    - id: TMF672
      version: v4.0.0
      name: user-role-permission-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/4.0.0/swagger/TMF672_User_Role_Permission_Management_API_v4.0.0_swagger.json
      port: 8080
      resources:
      - permission:
        - GET
        - GET /id
      - userRole:
        - GET
        - GET /id
    - id: TMF670
      version: v4.0.0
      name: payment-method-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF670_Payment_Method/4.0.0/swagger/TMF670_Payment_Method_Management_API_v4.0.0_swagger.json
      port: 8080
      resources:
      - paymentMethod:
        - GET
        - GET /id
    - id: TMF676
      version: v4.0.0
      name: payment-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF676_Payment/4.0.0/swagger/TMF676_Payment_Management_API_v4.0.0_swagger.json
      port: 8080
      resources:
      - payment:
        - GET
        - GET /id
    exposedAPIs:
    - id: TMF666
      version: v4.0.0
      name: account-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF666_Account/4.0.0/swagger/TMF666_Account_Management_API_v4.0.0_swagger.json
      port: 8080
      resources:
      - BillingAccount:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      - BillingCycleSpecification:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      - BillFormat:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      - BillPresentationMedia:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
    publishedEvents:
    - apitype: openapi
      implementation: /{{.Release.Name}}-accmngt
      name: AccountManagement
      port: 80
      resources:
      - billingAccountAttributeValueChangeEvent
      - billingAccountStateChangeEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF666_AccountManagement/master/TMF666-AccountManagement-v4.0.0.swagger.json
    subscribedEvents:
    - apitype: openapi
      name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleCreateEvent
      - partyRoleAttributeValueChangeEvent
      - partyRoleStateChangeEvent
      - partyRoleDeleteEvent
      specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
    - apitype: openapi
      name: UserRolePermissionManagement
      port: 80
      resources:
      - permissionCreateEvent
      - permissionAttributeValueChangeEvent
      - permissionStateChangeEvent
      - permissionDeleteEvent
      - userRoleCreateEvent
      - userRoleAttributeValueChangeEvent
      - userRoleStateChangeEvent
      - userRoleDeleteEvent
      specification: https://github.com/tmforum-apis/TMF672-UserRolePermission/blob/master/TMF672-UserRolePermission-v4.0.0.swagger.json
  description: The billing account management component aims to provide all the needed
    functionalities to create, configure and modify billing accounts. BAM component
    has the goal to support and handle the following capabilities/ functionalities.
    Set-up/ creation of Billing account. Associate payment plan(s). Associate payment
    method(s) - optional. Account taxes/ fees exception management. Define account
    associations. Provide account balance details. Set-up Billing contacts. Set-up
    Billing preferences (e.g., bill cycle frequency, invoice media type, invoice template
    option, etc.)
  functionalBlock: PartyManagement
  id: TMFC024
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  name: BillingAccountManagement
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  publicationDate: 2024-04-16 00:00:00
  status: specified
  version: 2.0.0
  managementFunction:
    exposedAPIs:
    - name: metrics
      apitype: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - id: TMF669
      version: v4.0.0
      name: party-role-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
      port: 8080
      resources: []
    dependentAPIs: []
