apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF632
      version: v4.0.0
      name: party-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v4.0.0.swagger.json
      port: 8080
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
    - id: TMF633
      version: v4.0.0
      name: service-catalog-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF633_v4.0.0.swagger.json
      port: 8080
      resources:
      - serviceSpecification:
        - GET
        - GET /id
    - id: TMF638
      version: v4.0.0
      name: service-inventory-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF638_v4.0.0.swagger.json
      port: 8080
      resources:
      - service:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
    - id: TMF639
      version: v4.0.0
      name: resource-inventory-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF639_v4.0.0.swagger.json
      port: 8080
      resources:
      - resource:
        - GET
        - GET /id
    - id: TMF640
      version: v4.0.0
      name: service-activation-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF640_v4.0.0.swagger.json
      port: 8080
      resources:
      - monitor:
        - GET
        - GET /id
    - id: TMF645
      version: v4.0.0
      name: service-qualification-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF645_v4.0.0.swagger.json
      port: 8080
      resources:
      - checkServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
      - queryServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
    - id: TMF646
      version: v4.0.0
      name: appointment-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF646_v4.0.0.swagger.json
      port: 8080
      resources:
      - appointment:
        - GET
        - GET /id
        - POST
        - PATCH
      - searchTimeSlot:
        - GET
        - GET /id
        - POST
        - PATCH
    - id: TMF652
      version: v4.0.0
      name: resource-order-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF652_v4.0.0.swagger.json
      port: 8080
      resources:
      - resourceOrder:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - cancelResourceOrder:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
    - id: TMF672
      version: v4.0.0
      name: user-role-permission-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF672_v4.0.0.swagger.json
      port: 8080
      resources:
      - permission:
        - GET
        - GET /id
    - id: TMF669
      version: v4.0.0
      name: party-role-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      port: 8080
      resources:
      - PartyRole:
        - GET
        - GET /id
    - id: TMF673
      version: v4.0.0
      name: geographic-address-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF673_v4.0.0.swagger.json
      port: 8080
      resources:
      - geographicAddress:
        - GET
        - GET /id
      - geographicSubAddress:
        - GET
        - GET /id
      - geographicAddressValidation:
        - GET
        - GET /id
        - POST
    - id: TMF674
      version: v4.0.0
      name: geographic-site-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF674_v4.0.0.swagger.json
      port: 8080
      resources:
      - geographicLocation:
        - GET
        - GET /id
    - id: TMF681
      version: v4.0.0
      name: communication-management-api
      required: false
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF681_v4.0.0.swagger.json
      port: 8080
      resources:
      - communicationMessage:
        - GET
        - GET /id
    exposedAPIs:
    - id: TMF641
      version: v4.1.0
      name: service-ordering-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF641_v4.1.0.swagger.json
      port: 8080
      resources:
      - serviceOrder:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - cancelServiceOrder:
        - GET
        - GET /id
        - POST
    publishedEvents:
    - apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceOrdeManagement/hub
      name: TMF641 Service Ordering Management API
      port: 80
      resources:
      - serviceOrderCreateEvent
      - serviceOrderStateChangeEvent
      - serviceOrderDeleteEvent
      - serviceOrderAttributeValueChangeEvent
      - serviceOrderInformationRequiredEvent
      - serviceOrderMilestoneEvent
      - serviceOrderJeopardyEvent
      - cancelServiceOrderCreateEvent
      - cancelServiceOrderStateChangeEvent
      - cancelServiceOrderInformationRequiredEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.1.0/swagger/TMF641_Service_Ordering_Management_API_v4.1.0_swagger.json
    - apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    subscribedEvents:
    - apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceOrderManagement/hub
      name: ResourceOrderManagement
      port: 80
      resources:
      - resourceOrderStateChange
      - resourceOrderAttributeValueChangeEvent
      - resourceOrderInformationRequiredEvent
      - cancelResourceOrderStateChange
      - cancelResourceOrderInformationRequiredEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.1.0/swagger/TMF634_Resource_Catalog_Management_API_v4.1.0_swagger.json
    - apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/hub
      name: ServiceQualification
      port: 80
      resources:
      - checkServiceQualificationStateChangeEvent
      - queryServiceQualificationStateChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF645_Service_Qualification_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourcePoolManagement/hub
      name: ResourcePoolManagement
      port: 80
      resources:
      - reservationStateChangeNotification
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Historic/3.0.0/swagger/TMF685-ResourcePool-v3.0.0.admin.swagger.json
    - apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Communication/hub
      name: Communication
      port: 80
      resources:
      - communicationMessageStateChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF681_Communication_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/WorkOrder/hub
      name: WorkOrder
      port: 80
      resources:
      - workOrderStateChange
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/4.0.0/swagger/TMF697_Work_Order_Management_API_v4.0.0_swagger.json
  description: The SOM is the entry point of the Production Domain. It oversees Customer-Facing-Service
    (CFS) delivery of resources (network and service platforms equipment). The SOM
    exposes in particular the API ServiceOrder. It is triggered when the Product Order
    Orchestration Management component calls this API to request CFS delivery. To
    achieve delivery of a CFS, the SOM orchestrates the CFS delivery process which.
    Identifies possible RFS and chooses one, using the catalog and technical inventory.
    Selects the resources (servers, equipment, etc.) and their instances. Requests
    the ROM to update selected resource instances to deliver CFS. Request sent to
    the ROM contain the CFS and the list of configured resource instances to update.
  functionalBlock: Production
  id: TMFC007
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  - email: sylvie.demarest@orange.com
    name: Sylvie Demarest
  name: ServiceOrderManagement
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  - email: sylvie.demarest@orange.com
    name: Sylvie Demarest
  publicationDate: 2024-02-23
  status: specified
  version: 1.1.1
  managementFunction:
    exposedAPIs:
    - name: metrics
      apitype: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - id: TMF669
      version: v4.0.0
      name: party-role-management-api
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      port: 8080
      resources: []
    dependentAPIs: []
