apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    exposedAPIs:
    - array_id: null
      minItems: null
      apis: []
  componentMetadata:
    id: TMFC003
    name: ProductOrderDeliveryOrchestrationAndManagement
    version: 1.1.1
    description: This component orchestrates the delivery of Product Orders (status
      accepted). Based on the level of Product specification information available
      in the Product Catalog (eg prerequisite links between product specifications,
      links between product and CFS specifications...) it determines in which order
      the product specification level order items need to be delivered, and to which
      CFS (or Resource) specification each ordered product corresponds, and prepares
      and addresses each related service (or Resource) order to the production system
      in charge. During the delivery process execution, this component is in charge
      of the evolution of the status of the product specification level order items,
      and of the related product items, triggering updates of the related inventories.
    publicationDate: 2023-08-18 00:00:00
    status: specified
    functionalBlock: CoreCommerce
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.3.3-Customer_Order_Handling-v23.0
    - 1.3.3.8-Manage_Order_Fallout-v23.0
    - 1.3.3.9-Customer_Order_Orchestration-v23.0
    - 1.2.9-Product_Offering_Purchasing-v23.0
    - 1.2.9.5-Complete_Product_Offering_Purchase-v23.0
    - 1.4.5-Service_Configuration_&_Activation-v23.0
    - 1.4.5.6-Issue_Service_Order-v23.0
    - 1.5.6-Resource_Provisioning-v23.0
    - 1.5.6.7-Issue_Resource_Order-v23.0
    functionalFrameworkFunctions:
    - 16-Fallout_Automated_Correction_v23.0
    - 17-Fallout_Correction_Information_Collection_v23.0
    - 18-Fallout_Management_to_Fulfillment_Application_Accessing_v23.0
    - 19-Fallout_Manual_Correction_Queuing_v23.0
    - 20-Fallout_Notification_v23.0
    - 21-Fallout_Orchestration_v23.0
    - 22-Fallout_Reporting_v23.0
    - 23-Fallout_Dashboard_System_Log-in_Accessing_v23.0
    - 24-Pre-populated_Fallout_Information_Presentation_v23.0
    - 175-Customer_Support_Jeopardy_Notification_v23.0
    - 174-Customer_Order_Error_Resolution_Support_v23.0
    - 723-Customer_Order_Item_Decomposition_v23.0
    - 214-Customer_Order_Orchestration_v23.0
    - 215-Retro-active_order_orchestration_v23.0
    - 342-Mass_Service/product_pre-activation_v23.0
    - 743-Number_Portability_Orchestration_v23.0
    - 756-Fallout_Rule_Based_Error_Correction_v23.0
  managementFunction:
    exposedAPIs:
    - name: metrics
      apiType: prometheus
      apiSDO: not_defined
      specification:
      - url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        version: v4.0.0
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
      id: exposedAPI_id
      version: exposedAPI_version
      resources: []
      required: false
      developerUI: exposedAPI_developerUI
    dependentAPIs:
    - name: dependentAPI_name
      id: dependentAPI_id
      version: dependentAPI_version
      apiType: dependentAPI_apiType
      apiSDO: dependentAPI_apiSDO
      specification:
      - url: dependentAPI_spec
        version: dependentAPI_version
      resources: []
      required: false
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - array_id: null
      minItems: null
      apis: []
    dependentAPIs:
    - array_id: null
      minItems: null
      apis: []
  eventNotification:
    publishedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF701
      apiSDO: not_defined
    subscribedEvents:
    - implementation: /{{.Release.Name}}-ProductOrderEvent
      name: ProductOrder
      port: 80
      resources:
      - productOrderStateChangeEvent
      - cancelProductOrderStateChangeEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/master/TMF622-ProductOrder-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF622
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOrder/call-back
      apiSDO: not_defined
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceOrderingManagement/v4/docs
      implementation: /{{.Release.Name}}-serviceOrderingManagementEvent
      name: ServiceOrder
      port: 80
      resources:
      - serviceOrderStateChangeEvent
      - serviceOrderAttributeValueChangeEvent
      - serviceOrderInformationRequiredEvent
      - serviceOrderMilestoneEvent
      - serviceOrderJeopardyEvent
      - cancelServiceOrderStateChangeEvent
      - cancelServiceOrderInformationRequiredEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF641_ServiceOrdering/master/TMF641-ServiceOrdering-v4.1.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF641
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceOrderingManagement/call-back
      apiSDO: not_defined
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceOrder/v4/docs
      implementation: /{{.Release.Name}}-ResourceOrder
      name: ResourceOrder
      port: 80
      resources:
      - resourceOrderStateChange
      - resourceOrderAttributeValueChangeEvent
      - resourceOrderInformationRequiredEvent
      - cancelResourceOrderStateChange
      - cancelResourceOrderInformationRequiredEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF652_ResourceOrderManagement/blob/master/TMF652-ResourceOrder-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF652
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceOrder/call-back
      apiSDO: not_defined
