component:
  id: tmfc009
  name: tmfc009-servicequalificationmanagement
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf645: tmforumorg/tmfc009-tmf645-v4.0.0:latest
  tmf669: tmforumorg/tmfc009-tmf669-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
