apiVersion: oda.tmforum.org/v1beta3
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      id: TMF632
      name: party-management-api
      port: 8080
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF633
      name: service-catalog-management-api
      port: 8080
      required: true
      resources:
      - serviceSpecification:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF633_Service_Catalog/4.0.0/swagger/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF634
      name: resource-catalog-management-api
      port: 8080
      required: false
      resources:
      - resourceSpecification:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF634_Resource_Catalog/4.1.0/swagger/TMF634_Resource_Catalog_Management_API_v4.1.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF638
      name: service-inventory-management-api
      port: 8080
      required: true
      resources:
      - service:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF638_Service_Inventory/4.0.0/swagger/TMF638_Service_Inventory_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF639
      name: resource-inventory-management-api
      port: 8080
      required: false
      resources:
      - resource:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF639_Resource_Inventory/4.0.0/swagger/TMF639_Resource_Inventory_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF640
      name: service-activation-management-api
      port: 8080
      required: false
      resources:
      - monitor:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF640_Service_Activation/4.0.0/swagger/TMF640_Service_Activation_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF641
      name: service-ordering-management-api
      port: 8080
      required: false
      resources:
      - serviceOrder:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - cancelServiceOrder:
        - GET
        - GET /id
        - POST
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF641_Service_Ordering/4.1.0/swagger/TMF641_Service_Ordering_Management_API_v4.1.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF645
      name: service-qualification-management-api
      port: 8080
      required: false
      resources:
      - checkServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
      - queryServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF645_Service_Qualification/4.0.0/swagger/TMF645_Service_Qualification_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF646
      name: appointment-management-api
      port: 8080
      required: false
      resources:
      - appointment:
        - GET
        - GET /id
        - POST
        - PATCH
      - searchTimeSlot:
        - GET
        - GET /id
        - POST
        - PATCH
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF646_Appointment/4.0.0/swagger/TMF646_Appointment_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF652
      name: resource-order-management-api
      port: 8080
      required: false
      resources:
      - resourceOrder:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - cancelResourceOrder:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF652_Resource_Order/4.0.0/swagger/TMF652_Resource_Order_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF653
      name: service-test-management-api
      port: 8080
      required: false
      resources:
      - serviceTest:
        - GET
        - GET /id
      - serviceTestSpecification:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF653_Service_Test/4.2.0/swagger/TMF653_Service_Test_Management_API_v4.2.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      port: 8080
      required: false
      resources:
      - partyRole:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF673
      name: geographic-address-management-api
      port: 8080
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      - geographicSubAddress:
        - GET
        - GET /id
      - geographicAddressValidation:
        - GET
        - GET /id
        - POST
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF673_Geographic_Address/4.0.0/swagger/TMF673_Geographic_Address_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF674
      name: geographic-site-management-api
      port: 8080
      required: false
      resources:
      - geographicLocation:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF674_Geographic_Site/4.0.0/swagger/TMF674_Geographic_Site_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF675
      name: geographic-location-management-api
      port: 8080
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF675_Geographic_Location/4.0.0/swagger/TMF675_Geographic_Location_Management_API_v4.0.0_beta_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF681
      name: communication-management-api
      port: 8080
      required: false
      resources:
      - communicationMessage:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF681_Communication/4.0.0/swagger/TMF681_Communication_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF697
      name: work-order-management-api
      port: 8080
      required: false
      resources:
      - workOrder:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF697_Work_Order/4.0.0/swagger/TMF697_Work_Order_Management_API_v4.0.0_beta_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF701
      name: process-flow-management-api
      port: 8080
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - PATCH
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
      version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      id: TMF641
      name: service-ordering-management-api
      port: 8080
      required: true
      resources:
      - serviceOrder:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - cancelServiceOrder:
        - GET
        - GET /id
        - POST
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF641_Service_Ordering/4.1.0/swagger/TMF641_Service_Ordering_Management_API_v4.1.0_swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF701
      name: process-flow-management-api
      port: 8080
      required: false
      resources:
      - processFlow:
        - GET
        - GET /id
        - POST
        - DELETE /id
      - taskFlow:
        - GET
        - GET /id
        - PATCH /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
      version: v4.0.0
  description: The SOM is the entry point of the Production Domain. It oversees Customer-Facing-Service
    (CFS) delivery of resources (network and service platforms equipment). The SOM
    exposes in particular the API ServiceOrder. It is triggered when the Product Order
    Orchestration Management component calls this API to request CFS delivery. To
    achieve delivery of a CFS, the SOM orchestrates the CFS delivery process which.
    Identifies possible RFS and chooses one, using the catalog and technical inventory.
    Selects the resources (servers, equipment, etc.) and their instances. Requests
    the ROM to update selected resource instances to deliver CFS. Request sent to
    the ROM contain the CFS and the list of configured resource instances to update.
  eventNotification:
    publishedEvents:
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceOrdeManagement/hub
      id: TMF641
      name: TMF641 Service Ordering Management API
      port: 80
      resources:
      - serviceOrderCreateEvent
      - serviceOrderStateChangeEvent
      - serviceOrderDeleteEvent
      - serviceOrderAttributeValueChangeEvent
      - serviceOrderInformationRequiredEvent
      - serviceOrderMilestoneEvent
      - serviceOrderJeopardyEvent
      - cancelServiceOrderCreateEvent
      - cancelServiceOrderStateChangeEvent
      - cancelServiceOrderInformationRequiredEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.1.0/swagger/TMF641_Service_Ordering_Management_API_v4.1.0_swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      id: TMF701
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    subscribedEvents:
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceOrderManagement/hub
      id: TMF634
      name: ResourceOrderManagement
      port: 80
      resources:
      - resourceOrderStateChange
      - resourceOrderAttributeValueChangeEvent
      - resourceOrderInformationRequiredEvent
      - cancelResourceOrderStateChange
      - cancelResourceOrderInformationRequiredEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.1.0/swagger/TMF634_Resource_Catalog_Management_API_v4.1.0_swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/hub
      id: TMF645
      name: ServiceQualification
      port: 80
      resources:
      - checkServiceQualificationStateChangeEvent
      - queryServiceQualificationStateChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF645_Service_Qualification_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Communication/hub
      id: TMF681
      name: Communication
      port: 80
      resources:
      - communicationMessageStateChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF681_Communication_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/WorkOrder/hub
      id: TMF697
      name: WorkOrder
      port: 80
      resources:
      - workOrderStateChange
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/4.0.0/swagger/TMF697_Work_Order_Management_API_v4.0.0_swagger.json
  functionalBlock: Production
  id: TMFC007
  maintainers:
  - email: components@tmforum.org
    name: Redacted
  managementFunction:
    exposedAPIs:
    - apiType: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  name: ServiceOrderManagement
  owners:
  - email: Redacted
    name: Redacted
  publicationDate: 2024-02-23
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    dependentAPIs: []
    exposedAPIs:
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      port: 8080
      required: true
      resources: []
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
  status: specified
  version: 2.0.0
