apiVersion: oda.tmforum.org/v1beta3
kind: Component
metadata:
  labels:
    oda.tmforum.org/componentName: '{{.Release.Name}}-{{.Values.component.name}}'
  name: '{{.Release.Name}}-{{.Values.component.name}}'
spec:
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      name: resource-catalog-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF634_Resource_Catalog/4.1.0/swagger/TMF634_Resource_Catalog_Management_API_v4.1.0_swagger.json
    - apiType: openapi
      name: party-role-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: party-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: entity-catalog-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF662_Entity_Catalog/4.0.0/swagger/TMF662_Entity_Catalog_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: user-role-permission-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/4.0.0/swagger/TMF672_User_Role_Permission_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: event-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF688_Event/4.0.0/swagger/TMF688_Event_Management_API_v4.0.0_beta_swagger.json
    exposedAPIs:
    - apiType: openapi
      implementation: '{{.Release.Name}}-service-catalog-management-api'
      name: service-catalog-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/serviceCatalogManagement/v4/
      port: 8080
      specification:
      - https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF633_Service_Catalog/4.0.0/swagger/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      implementation: '{{.Release.Name}}-service-quality-management-management-api'
      name: service-quality-management-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/serviceQualityManagement/v4/
      port: 8080
      specification:
      - https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF657_Service_Quality_Management/4.0.0/swagger/TMF657_Service_Quality_Management_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      implementation: '{{.Release.Name}}-process-flow-management-api'
      name: process-flow-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/processFlowManagement/v4/
      port: 8080
      specification:
      - https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
    - apiType: openapi
      implementation: '{{.Release.Name}}-event-management-api'
      name: event-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/event/v4/
      port: 8080
      specification:
      - https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF688_Event/4.0.0/swagger/TMF688_Event_Management_API_v4.0.0_beta_swagger.json
  description: "\tService Catalog Management component is responsible for organizing\
    \ the collection of service specifications that identify and define all requirements\
    \ of a service that can be performed. Service Catalog Management component has\
    \ the functionality that enable present a customer-facing view so users are able\
    \ to search and select services they need, as well as a technical view to enable\
    \ define and setup what's needed to deliver service specifications (Customer Facing\
    \ Service Specifications (CFSSs) and Resource Facing Service Specifications (RFSSs))\
    \ contained in the service catalog. Service Catalog Management component has functionalities\
    \ that include creation of new service specifications, managing service specifications,\
    \ administering the lifecycle of services, describing relationships between service\
    \ specification attributes, reporting on service specification and their changes,\
    \ and facilitating easy and systematic indexing and access to services, as well\
    \ as facilitate automating the service delivery process."
  eventNotification:
    publishedEvents:
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceCatalog/hub
      id: TMF633
      implementation: /{{.Release.Name}}-ServiceCatalog
      name: ServiceCatalogManagement
      port: 80
      resources:
      - serviceSpecificationCreateEvent
      - serviceSpecificationChangeEvent
      - serviceSpecificationDeleteEvent
      - serviceCategoryCreateEvent
      - serviceCategoryChangeEvent
      - serviceCategoryDeleteEvent
      - serviceCandidateCreateEvent
      - serviceCandidateChangeEvent
      - serviceCandidateDeleteEvent
      - serviceCatalogCreateEvent
      - serviceCatalogChangeEvent
      - serviceCatalogDeleteEvent
      - serviceCatalogBatchEvent
      specification: https://github.com/tmforum-apis/TMF633_ServiceCatalog/blob/master/TMF633-ServiceCatalog-v4.0.0.swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualityManagement/hub
      id: TMF657
      implementation: /{{.Release.Name}}-ServiceQualityManagement
      name: ServiceQualityManagement
      port: 80
      resources:
      - serviceLevelObjectiveCreateEvent
      - serviceLevelObjectiveChangeEvent
      - serviceLevelObjectiveAttributeValueChangeEvent
      - serviceLevelSpecificationCreateEvent
      - serviceLevelSpecificationDeleteEvent
      - serviceLevelSpecificationAttributeValueChangeEvent
      specification: https://github.com/tmforum-apis/TMF657_ServiceQualityManagement/blob/master/TMF657-ServiceQualityManagement-v4.0.0.swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      id: TMF701
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
    subscribedEvents:
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/call-back
      id: TMF634
      implementation: /{{.Release.Name}}-ResourceCatalog
      name: ResourceCatalogManagement
      port: 80
      resources:
      - resourceSpecificationCreateEvent
      - resourceSpecificationChangeEvent
      - resourceSpecificationDeleteEvent
      specification: https://github.com/tmforum-apis/TMF634_ResourceCatalog/blob/master/TMF634-ResourceCatalog-v4.1.0.swagger.json
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EntityCatalog/call-back
      id: TMF662
      implementation: /{{.Release.Name}}-EntityCatalog
      name: EntityCatalogManagement
      port: 80
      resources:
      - entitySpecificationCreateEvent
      - entitySpecificationAttributeValueChangeEvent
      - entitySpecificationChangeEvent
      - entitySpecificationDeleteEvent
      specification: https://github.com/tmforum-apis/TMF662_EntityCatalog/blob/master/TMF662-EntityCatalog-v4.0.0.swagger.json
  functionalBlock: Production
  id: TMFC006
  maintainers:
  - email: components@tmforum.org
    name: Redacted
  name: ServiceCatalogManagement
  owners:
  - email: Redacted
    name: Redacted
  publicationDate: '{{.Values.component.publicationDate}}'
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - apiType: openapi
      implementation: '{{.Release.Name}}-partyrole-management-api'
      name: partyrole-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      specification:
      - https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
  status: specified
  version: 1.1.1
