apiVersion: oda.tmforum.org/v1alpha1
kind: component
metadata:
  name: TAG_REALESE_NAME - Digital Identity Management
  labels:
    oda.tmforum.org/componentName: Digital Identity Management
    oda.tmforum.org/funtionalBlockName: Party Management
spec:
  componentKinds:
    - group: core
      kind: Inventory
  coreFunction:
    exposedAPIs:
      - name: DigitalIdentityManagement
        specification: >-
          https://github.com/tmforum-apis/TMF720_DigitalIdentity/blob/main/TMF720-DigitalIdentity-v4.0.0.swagger.json
        required: true
        implementation: '/{{.Release.Name}}-DigitalIdentityManagement'
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/DigitalIdentityManagement/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/DigitalIdentityManagement/v4/docs
        port: 8080
      - name: ProcessFlowManagement
        specification: >-
          https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
        implementation: '/{{.Release.Name}}-ProcessFlowManagement'
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/processFlowManagement/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/processFlowManagement/v4/docs
        port: 8080
      - name: Event
        specification: >-
          https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
        implementation: '/{{.Release.Name}}-Event'
        path: '/{{.Release.Name}}-{{.Values.component.type}}/tmf-api/event/v4'
        developerUI: '/{{.Release.Name}}-{{.Values.component.type}}/tmf-api/event/v4/docs'
        port: 8080
    dependantAPIs:
      - name: PartyRoleManagement
        specification: >-
          https://github.com/tmforum-apis/TMF669_PartyRole/blob/master/TMF669-PartyRole-v4.0.0.swagger.json
        implementation: '/{{.Release.Name}}-PartyRoleManagement'
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/v4/docs
        port: 8080
      - name: Party
        specification: >-
          https://github.com/tmforum-apis/TMF632_PartyManagement/blob/master/TMF632-Party-v4.0.0.swagger.json
        implementation: '/{{.Release.Name}}-Party'
        path: '/{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Party/v4'
        developerUI: '/{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Party/v4/docs'
        port: 8080
      - name: Event
        specification: >-
          https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
        implementation: '/{{.Release.Name}}-Event'
        path: '/{{.Release.Name}}-{{.Values.component.type}}/tmf-api/event/v4'
        developerUI: '/{{.Release.Name}}-{{.Values.component.type}}/tmf-api/event/v4/docs'
        port: 8080
    managementAPIs: null
  eventNotification:
    PublishedEvent:
      DigitalIdentity:
        - DigitalIdentityCreateEvent
        - DigitalIdentityStateChangeEvent
        - DigitalIdentityDeleteEvent
        - DigitalIdentityAttributeValueChangeEvent
    SubscribedEvent:
      UserRoles:
        - UserRoleCreationNotification
        - UserRoleChangeNotification
  maintainers:
    - email: gaetano.biancardi@accenture.com
      name: Gaetano Biancardi
  management: []
  owners:
    - email: gaetano.biancardi@accenture.com
      name: Gaetano Biancardi
  security:
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  selector:
    matchLabels:
      oda.tmforum.org/componentName: Digital Identity Management
  type: Digital Identity Management
  version: 1.0.0
