apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  maintainers:
    - name: Matteo Destino
      email: matteo.destino@accenture.com
      owners: null
    - name: Matteo Destino
      email: matteo.destino@accenture.com
  coreFunction:
    exposedAPIs:
      - name: DigitalIdentityManagement
        id: TMF720
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF720_DigitalIdentityManagement/master/TMF720-DigitalIdentityManagement-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-digidemngt
        apitype: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/DigitalIdentityManagement/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/DigitalIdentityManagement/v4/docs
        port: 8080
        resources:
          - digitalIdentity:
              - GET
              - GET/id
              - POST
              - PATCH/id
              - DELETE/id
          - roles:
              - GET
              - GET/id
              - POST
              - PATCH/id
              - DELETE/id
        required: true
      - name: ProcessFlowManagement
        id: TMF701
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlowManagement/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-procmngttapi
        apitype: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
        port: 8080
        resources:
          - processFlow:
              - GET
              - GET/id
              - POST
              - DELETE/id
          - taskFlow:
              - GET
              - GET/id
              - PATCH/id
        required: false
      - name: Event
        id: TMF688
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-PromotionManagement
        apitype: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
        port: 8080
        resources:
          - event:
              - GET
              - GET /id
        required: false
    publishedEvents:
      - name: digitalIdentity
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF720_DigitalIdentityManagement/master/TMF720-DigitalIdentityManagement-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-digidemngt
        apitype: openapi
        port: 80
        resources:
          DigitalIdentity:
            - DigitalIdentityCreateEvent
            - DigitalIdentityStateChangeEvent
            - DigitalIdentityDeleteEvent
            - DigitalIdentityAttributeValueChangeEvent
    subscribedEvents:
      - name: PartyRoleManagement
        specification: >-
          https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
        apitype: openapi
        port: 80
        resources: userRoles - UserRoleCreationNotification - UserRoleChangeNotification
    dependentAPIs:
      - name: PartyManagement
        id: TMF632
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
        apitype: openapi
        resources:
          - individual:
              - GET
              - GET/id
          - organization:
              - GET
              - GET/id
        required: true
      - name: PartyRoleManagement
        id: TMF669
        version: 4
        specification: >-
          https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
        apitype: openapi
        resources:
          - partyRole:
              - POST
        required: true
      - name: ProcessFlowManagement
        id: TMF701
        version: 4
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
        apitype: openapi
        resources:
          - processFlow:
              - POST
              - GET
              - GET /id
              - DELETE
          - taskFlow:
              - PATCH
              - GET
              - GET /id
        required: false
      - name: Event
        id: TMF688
        version: 4
        specification: >-
          https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
        apitype: openapi
        resources:
          - event:
              - GET
              - GET /id
        required: false
  securityFunction: []
  managementFunction: []
  id: TMFC020
  name: DigitalIdentityManagement
  functionalBlock: PartyManagement
  publicationDate: 2023-08-18T00:00:00.000Z
  status: specified
  version: 1.1.1
  description: >-
    The Digital Identity Management is responsible for the parties (customers,
    employees, partners) and resources authentication.
