apiVersion: oda.tmforum.org/v1beta3
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      id: TMF620
      name: product-catalog-management-api
      port: 8080
      required: true
      resources:
      - productCategory:
        - GET
        - GET /id
      - productOffering:
        - GET
        - GET /id
      - productOfferingPrice:
        - GET
        - GET /id
      - productSpecification:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF620_v4.1.0.swagger.json
      version: v4.1.0
    - apiType: openapi
      id: TMF637
      name: product-inventory-management-api
      port: 8080
      required: true
      resources:
      - product:
        - GET
        - GET /id
        - POST
        - PATCH
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF637_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF679
      name: product-offering-qualification-management-api
      port: 8080
      required: false
      resources:
      - productOfferingQualification:
        - GET
        - GET /id
        - POST
        - PATCH
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF679_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF645
      name: service-qualification-management-api
      port: 8080
      required: false
      resources:
      - checkServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
      - queryServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF645_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF646
      name: appointment-management-api
      port: 8080
      required: false
      resources:
      - appointment:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - searchTimeSlot:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF646_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF673
      name: geographic-address-management-api
      port: 8080
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      - geographicSubAddress:
        - GET
        - GET /id
      - geographicAddressValidation:
        - GET
        - GET /id
        - POST
        - PATCH
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF673_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF674
      name: geographic-site-management-api
      port: 8080
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF674_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF716
      name: resource-reservation
      port: 8080
      required: false
      resources:
      - resourceReservation:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - cancelResourceReservation:
        - GET
        - GET /id
        - POST
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF716_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF687
      name: stock-management-api
      port: 8080
      required: false
      resources:
      - checkProductStock:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - queryProductStock:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - reserveProductStock:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - productStock:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF687_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF632
      name: party-management-api
      port: 8080
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      port: 8080
      required: false
      resources:
      - partyRole:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF666
      name: account-management-api
      port: 8080
      required: false
      resources:
      - billingAccount:
        - GET /id
        - GET
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF666_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF676
      name: payment-management-api
      port: 8080
      required: false
      resources:
      - payment:
        - GET / id
        - GET
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF676_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF683
      name: party-interaction-management-api
      port: 8080
      required: false
      resources:
      - partyInteraction:
        - GET / id
        - GET
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF683_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF638
      name: service-inventory-management-api
      port: 8080
      required: false
      resources:
      - service:
        - GET / id
        - GET
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF638_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF639
      name: resource-inventory-management-api
      port: 8080
      required: false
      resources:
      - resource:
        - GET / id
        - GET
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF639_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF760
      name: product-configuration-management-api
      port: 8080
      required: false
      resources:
      - checkProductConfiguration:
        - GET
        - GET /id
        - POST
      - queryProductConfiguration:
        - GET
        - GET /id
        - POST
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF760_v5.0.0.swagger.json
      version: v5.0.0
    - apiType: openapi
      id: TMF651
      name: agreement-management-api
      port: 8080
      required: false
      resources:
      - agreement:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF651_v4.0.0.swagger.json
      version: v4.0.0
    exposedAPIs:
    - apiType: openapi
      id: TMF622
      name: product-ordering-management-api
      port: 8080
      required: true
      resources:
      - productOrder:
        - POST
        - GET
        - GET /id
        - PATCH
        - DELETE
      - cancelProductOrder:
        - POST
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF622_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF648
      name: quote-management-api
      port: 8080
      required: false
      resources:
      - quote:
        - POST
        - GET
        - GET /id
        - PATCH
        - DELETE
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF648_v4.0.0.swagger.json
      version: v4.0.0
    - apiType: openapi
      id: TMF663
      name: shopping-cart-management-api
      port: 8080
      required: false
      resources:
      - shoppingCart:
        - POST
        - GET
        - GET /id
        - PATCH
        - DELETE
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF663_v4.0.0.swagger.json
      version: v4.0.0
  description: Addresses the means of capturing what a customer wants to order, based
    on the CSP Product Catalog. This component permits to choose the configuration
    of the product offerings and products desired, to provide a quote, to check the
    eligibility of the customer order, and to complete it with information needed
    such as the related parties or associated the billing account and the delivery
    appointment if needed. This component is globally in charge of these quote management,
    order capture and validation steps, using dedicated components (e.g., Offering
    Configurator, Service Qualification, Party Mgt) when needed. After the delivery
    of the customer product order items, this component is also in charge of the commercial
    closure of the order. It includes update of the Product Inventory (status and
    starting/end date of tariffs and discounts) and potential commercial rules control
    (e.g. receipt of the contract document signed by the customer)
  eventNotification:
    publishedEvents:
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOrder/hub
      id: TMF622
      implementation: /{{.Release.Name}}-ProductOrderEvent
      name: ProductOrder
      port: 80
      resources:
      - productOrderStateChange
      - productOrderCreateEvent
      - productOrderAttributeValueChange
      - productOrderDelete
      - productOrderInformationRequired
      - cancelProductOrderCreateEvent
      - cancelProductOrderStateChange
      - cancelProductOrderInformationRequired
      specification: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/master/TMF622-ProductOrder-v4.0.0.swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Quote/hub
      id: TMF648
      implementation: /{{.Release.Name}}-QuoteEvent
      name: Quote
      port: 80
      resources:
      - quoteStateChange
      - quoteCreateEvent
      - quoteAttributeValueChange
      - quoteDelete
      - quoteInformationRequired
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF648_QuoteManagement/master/TMF648-QuoteManagement-v4.0.0.swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ShoppingCart/hub
      id: TMF663
      implementation: /{{.Release.Name}}-ShoppingCartEvent
      name: ShoppingCart
      port: 80
      resources:
      - shoppingCartCreateEvent
      - shoppingCartAttributeValueChange
      - shoppingCartDelete
      specification: https://github.com/tmforum-apis/TMF663_ShoppingCart/blob/master/TMF663-ShoppingCart-v4.0.0.swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      id: TMF701
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
    subscribedEvents:
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOfferingQualification/call-back
      id: TMF679
      implementation: /{{.Release.Name}}-ProductOfferingQualificationEvent
      name: ProductOfferingQualification
      port: 80
      resources:
      - productOfferingQualificationStateChangeEvent
      specification: https://github.com/tmforum-apis/TMF679_ProductOfferingQualification/blob/master/TMF679-ProductOfferingQualification-v4.0.0.swagger.json
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/call-back
      id: TMF645
      implementation: /{{.Release.Name}}-ServiceQualificationEvent
      name: ServiceQualification
      port: 80
      resources:
      - checkServiceQualificationStateChangeEvent
      - queryServiceQualificationStateChangeEvent
      specification: https://github.com/tmforum-apis/TMF645_ServiceQualification/blob/master/TMF645-ServiceQualification-v4.0.0.swagger.json
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/call-back
      id: TMF673
      implementation: /{{.Release.Name}}-GeographicAddressManagementEvent
      name: GeographicAddressManagement
      port: 80
      resources:
      - geographicAddressValidationStateChange
      specification: https://github.com/tmforum-apis/TMF673_GeographicAddress/blob/master/TMF673-GeographicAddress-v4.0.1.swagger.json
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PaymentManagementEvent/call-back
      id: TMF676
      implementation: /{{.Release.Name}}-PaymentManagementEvent
      name: PaymentManagement
      port: 80
      resources:
      - paymentCreate
      - paymentStateChange
      specification: https://github.com/tmforum-apis/TMF676_PaymentManagement/blob/master/TMF676-Payment-v4.0.0.swagger.json
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceReservationEvent/call-back
      id: TMF716
      implementation: /{{.Release.Name}}-ResourceReservationEvent
      name: ResourceReservation
      port: 80
      resources:
      - resourceReservationCreateEvent
      - resourceReservationAttributeValueChangeEvent
      - resourceReservationDeleteEvent
      - resourceReservationStateChangeEvent
      - resourceReservationInformationRequiredEvent
      - cancelResourceReservationCreateEvent
      - cancelResourceReservationStateChangeEvent
      - cancelResourceReservationInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF716_ResourceReservation/blob/master/TMF716-ResourceReservation-v4.1.0.swagger.json
  functionalBlock: CoreCommerce
  id: TMFC002
  maintainers:
  - email: components@tmforum.org
    name: Redacted
  managementFunction:
    exposedAPIs:
    - apiType: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  name: ProductOrderCaptureAndValidation
  owners:
  - email: Redacted
    name: Redacted
  publicationDate: 2024-09-05 00:00:00
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    dependentAPIs: []
    exposedAPIs:
    - apiType: openapi
      id: TMF669
      name: party-role-management-api
      port: 8080
      required: true
      resources: []
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      version: v4.0.0
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
  status: specified
  version: 2.0.1
