component:
  id: tmfc037
  name: tmfc037-serviceperformancemanagement
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf642: tmforumorg/tmfc037-tmf642-v4.0.0:latest
  tmf669: tmforumorg/tmfc037-tmf669-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
