apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
    exposedAPIs:
    - array_id: null
      minItems: null
      apis: []
    - array_id: null
      minItems: null
      apis: []
  componentMetadata:
    id: TMFC007
    name: ServiceOrderManagement
    version: 2.0.0
    description: Service Order Management (SOM) component is the entry point to the
      Production Domain. It oversees delivery of Customer-Facing-Service (CFS) resources
      (network and service platform equipment). The SOM exposes the API ServiceOrder.
      It is triggered when the Product Order Delivery Orchestration And Management
      component calls this API to request CFS delivery. To achieve delivery of a CFS,
      the SOM orchestrates the CFS delivery process which identifies possible RFS
      and chooses one, using the catalog and technical inventory. It selects the resources
      (servers, equipment, etc.) and their instances, and requests the Resource Order
      Management (ROM) component to update selected resource instances to deliver
      CFS. Requests sent to the ROM contain the CFS and the list of configured resource
      instances to be updated.
    publicationDate: 2024-02-23
    status: specified
    functionalBlock: Production
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.4.5-Service_Configuration_&_Activation-v21.5
    - 1.4.5.1-Design_Solution-v21.5
    - 1.4.5.2-Allocate_Specific_Service_Parameters_to_Services-v21.5
    - 1.4.5.3-Track_&_Manage_Service_Provisioning-v21.5
    - 1.4.5.4-Implement,_configure_&_activate_service-v21.5
    - 1.4.5.6-Issue_Service_Order-v21.5
    - 1.4.5.7-Report_service_provisioning-v21.5
    - 1.4.5.8-Close_Service_Order-v21.5
    - 1.5.6-Resource_Provisioning-v21.5
    - 1.5.6.7-Issue_Resource_Order-v21.5
    functionalFrameworkFunctions:
    - 584-Service_Activation_Planning-v21.5
    - 588-Service_Orchestration_Configuration-v21.5
    - 591-Service_Parameters_Allocation-v21.5
    - 596-Service_Order_Transfer_Supervision-v21.5
    - 598-Service_Order_Orchestration-v21.5
    - 733-Service_Order_Decomposition-v21.5
    - 734-Service_Data_Collection-v21.5
    - 963-Service_Task_Item_Decomposition-v21.5
    - 968-Service_Work_Item_Sequence_Execution-v21.5
    - 969-Service_Work_Item_Sequence_Execution_Configuration-v21.5
    - 571-Service_Delivery_Due_Date_Calculation-v21.5
    - 1061-Service_Order_Initiation-v21.5
    - 595-Service_Order_Completion-v21.5
    - 600-Service_Order_Validation-v21.5
    - 583-Activation_Notification-v21.5
    - 594-Service_Order_Storage-v21.5
    - 597-Service_Order_Exposure-v21.5
    - 599-Service_Order_Tracking-v21.5
    - 735-Access_Provider_Selection-v21.5
    - 341-Service_Activation-v21.5
    - 342-Mass_Service_Pre-activation-v21.5
    - 570-Solution_Services_Design_Management-v21.5
    - 589-Cross_Services_Dependencies_Configuration-v21.5
    - 590-Service_Configuration-v21.5
    - 585-Service_Configuration_Activation-v21.5
    - 592-Service_Parameters_Reservation-v21.5
  managementFunction:
    exposedAPIs:
    - name: metrics
      apiType: prometheus
      apiSDO: not_defined
      specification:
      - url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        version: v4.0.0
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
      id: exposedAPI_id
      version: exposedAPI_version
      resources: []
      required: false
      developerUI: exposedAPI_developerUI
    dependentAPIs:
    - name: dependentAPI_name
      id: dependentAPI_id
      version: dependentAPI_version
      apiType: dependentAPI_apiType
      apiSDO: dependentAPI_apiSDO
      specification:
      - url: dependentAPI_spec
        version: dependentAPI_version
      resources: []
      required: false
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - array_id: null
      minItems: null
      apis: []
    dependentAPIs:
    - array_id: null
      minItems: null
      apis: []
  eventNotification:
    publishedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceOrdeManagement/hub
      name: TMF641 Service Ordering Management API
      port: 80
      resources:
      - serviceOrderCreateEvent
      - serviceOrderStateChangeEvent
      - serviceOrderDeleteEvent
      - serviceOrderAttributeValueChangeEvent
      - serviceOrderInformationRequiredEvent
      - serviceOrderMilestoneEvent
      - serviceOrderJeopardyEvent
      - cancelServiceOrderCreateEvent
      - cancelServiceOrderStateChangeEvent
      - cancelServiceOrderInformationRequiredEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.1.0/swagger/TMF641_Service_Ordering_Management_API_v4.1.0_swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF641
      apiSDO: not_defined
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF701
      apiSDO: not_defined
    subscribedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceOrderManagement/hub
      name: ResourceOrderManagement
      port: 80
      resources:
      - resourceOrderStateChange
      - resourceOrderAttributeValueChangeEvent
      - resourceOrderInformationRequiredEvent
      - cancelResourceOrderStateChange
      - cancelResourceOrderInformationRequiredEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.1.0/swagger/TMF634_Resource_Catalog_Management_API_v4.1.0_swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF634
      apiSDO: not_defined
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/hub
      name: ServiceQualification
      port: 80
      resources:
      - checkServiceQualificationStateChangeEvent
      - queryServiceQualificationStateChangeEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF645_Service_Qualification_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF645
      apiSDO: not_defined
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Communication/hub
      name: Communication
      port: 80
      resources:
      - communicationMessageStateChangeEvent
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF681_Communication_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF681
      apiSDO: not_defined
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/WorkOrder/hub
      name: WorkOrder
      port: 80
      resources:
      - workOrderStateChange
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/4.0.0/swagger/TMF697_Work_Order_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF697
      apiSDO: not_defined
