apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: '{{.Release.Name}}-{{.Values.component.name}}'
  name: '{{.Release.Name}}-mongodb'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: '{{.Release.Name}}-mongodb'
  template:
    metadata:
      labels:
        app: '{{.Release.Name}}-{{.Values.component.name}}'
        impl: '{{.Release.Name}}-mongodb'
        version: mongo-5.0.1
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: '{{.Release.Name}}-mongodb'
        - name: RELEASE_NAME
          value: '{{.Release.Name}}'
        - name: COMPONENT_NAME
          value: '{{.Release.Name}}-{{.Values.component.name}}'
        image: mongo:5.0.1
        imagePullPolicy: Always
        name: '{{.Release.Name}}-mongodb'
        ports:
        - containerPort: 27017
          name: '{{.Release.Name}}-mongodb'
        volumeMounts:
        - mountPath: /data/db
          name: '{{.Release.Name}}-mongodb-pv-storage'
      volumes:
      - name: '{{.Release.Name}}-mongodb-pv-storage'
        persistentVolumeClaim:
          claimName: '{{.Release.Name}}-mongodb-pv-claim'
