apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: '{{.Release.Name}}-{{.Values.component.name}}'
  name: '{{.Release.Name}}-mongodb'
spec:
  ports:
  - name: tcp-{{.Release.Name}}-mongodb
    port: 27017
    targetPort: '{{.Release.Name}}-mongodb'
  selector:
    impl: '{{.Release.Name}}-mongodb'
