component:
  id: tmfc012
  name: tmfc012-resourceinventory
  publicationDate: '2024-10-17T00:00:00.000Z'
images:
  tmf639: tmforumorg/tmfc012-tmf639-v4.0.0:latest
  tmf669: tmforumorg/tmfc012-tmf669-v4.0.0:latest
secretsManagement:
  podSelector:
    name: '{{.Release.Name}}-{{.Values.component.name}}'
    namespace: default
    serviceaccount: default
security:
  controllerRole: admin
