apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF639
      apiType: openapi
      apiSDO: tmForum
      name: resource-inventory-management-api
      required: true
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF639_Resource_Inventory/4.0.0/swagger/TMF639_Resource_Inventory_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      resources:
      - resource:
        - GET
        - GET /id
    - id: TMF673
      apiType: openapi
      apiSDO: tmForum
      name: geographic-address-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF673_Geographic_Address/4.0.0/swagger/TMF673_Geographic_Address_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      resources:
      - geographicAddress:
        - GET
        - GET/id
      - geographicSubAddress:
        - GET
        - GET /id
    - id: TMF674
      apiType: openapi
      apiSDO: tmForum
      name: geographic-site-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF674_Geographic_Site/4.0.0/swagger/TMF674_Geographic_Site_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      resources:
      - geographicSite:
        - GET
        - GET/id
    - id: TMF675
      apiType: openapi
      apiSDO: tmForum
      name: geographic-location-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF675_Geographic_Location/4.0.0/swagger/TMF675_Geographic_Location_Management_API_v4.0.0_beta_swagger.json
        version: v4.0.0
      resources:
      - geographicLocation:
        - GET
        - GET/id
    - id: TMF688
      apiType: openapi
      apiSDO: tmForum
      name: event-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF688_Event/4.0.0/swagger/TMF688_Event_Management_API_v4.0.0_beta_swagger.json
        version: v4.0.0
      resources:
      - event:
        - GET
        - GET /id
    - id: TMF701
      apiType: openapi
      apiSDO: tmForum
      name: process-flow-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
    exposedAPIs:
    - id: TMF649
      apiType: openapi
      apiSDO: tmForum
      name: performance-thresholding-management-api
      required: true
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF649_Performance_Thresholding/4.0.0/swagger/TMF649_Performance_Thresholding_Management_API_v4.0.0_beta_swagger.json
        version: v4.0.0
      path: not_defined
      developerUI: not_defined
      implementation: not_defined
      port: 8080
      resources:
      - threshold:
        - POST
        - GET
        - GET /id
        - PATCH /id
        - DELETE /id
      - thresholdJob:
        - POST
        - GET
        - GET /id
        - PATCH /id
        - DELETE /id
    - id: TMF642
      apiType: openapi
      apiSDO: tmForum
      name: alarm-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF642_Alarm/4.0.0/swagger/TMF642_Alarm_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      path: not_defined
      developerUI: not_defined
      implementation: not_defined
      port: 8080
      resources:
      - alarm:
        - POST
        - GET
        - GET /id
        - PATCH /id
        - DELETE /id
    - id: TMF701
      apiType: openapi
      apiSDO: tmForum
      name: process-flow-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
      path: not_defined
      developerUI: not_defined
      implementation: not_defined
      port: 8080
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
  componentMetadata:
    id: TMFC038
    name: ResourcePerformanceManagement
    version: 1.2.0
    description: Resource Performance Management component monitors, analyzes, and
      reports on the performance of the service provider's resources.
    publicationDate: 2024-12-17
    status: specified
    functionalBlock: IntelligenceManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs: []
    functionalFrameworkFunctions: []
    SIDs:
    - Resource_Domain|Resource_Performance_ABE|v25.0
    - Patterns_Domain|Performance_ABE|Performance_Monitoring ABE|Performance_Production
      ABE|MeasurementProductionJob_BE|v25.0
    - Patterns_Domain|Performance_ABE|Performance_Monitoring ABE|Performance_Collection
      ABE|AdhocCollection_BE|v25.0
    - Patterns_Domain|Performance_ABE|Performance_Monitoring ABE|Performance_Collection
      ABE|MeasurementCollectionJob_BE|v25.0
    - Patterns_Domain|Performance_ABE|Performance_Threshold ABE|v25.0
    - Resource_Domain|Resource_Trouble_ABE|Alarm_ABE|v25.0
  managementFunction:
    exposedAPIs:
    - name: metrics
      apiType: prometheus
      apiSDO: not_defined
      specification:
      - url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        version: v4.0.0
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
      id: exposedAPI_id
      version: exposedAPI_version
      resources: []
      required: false
      developerUI: exposedAPI_developerUI
    dependentAPIs:
    - name: dependentAPI_name
      id: dependentAPI_id
      version: dependentAPI_version
      apiType: dependentAPI_apiType
      apiSDO: dependentAPI_apiSDO
      specification:
      - url: dependentAPI_spec
        version: dependentAPI_version
      resources: []
      required: false
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - id: TMF669
      apiType: openapi
      apiSDO: not_defined
      name: party-role-management-api
      required: true
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      implementation: '{{.Release.Name}}-partyroleapi'
      port: 8080
      resources: []
    dependentAPIs: []
  eventNotification:
    publishedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF701
      apiSDO: not_defined
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Alarm/hub
      implementation: /{{.Release.Name}}-Alarm
      name: AlarmManagement
      port: 80
      resources:
      - alarmStateChange**
      - alarmCreateEvent**
      - alarmClearEvent**
      - alarmAckEvent**
      specification:
      - url: https://github.com/tmforum-apis/TMF642_AlarmManagement/blob/master/TMF642-Alarm-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF642
      apiSDO: not_defined
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Performance/hub
      implementation: /{{.Release.Name}}-Performance
      name: PerformanceManagement
      port: 80
      resources:
      - measurementCollectionJobCreateEvent
      - measurementCollectionJobExecutionStateChangeEvent
      - measurementCollectionJobDeleteEvent
      - measurementCollectionJobAttributeValueChangeEvent
      - measurementCollectionJobFilesReadyEvent
      - measurementCollectionJobFilesPreparationErrorEvent
      - onDemandCollectionCreateEvent
      - onDemandCollectionExecutionStateChangeEvent
      - onDemandCollectionDeleteEvent
      - onDemandCollectionAttributeValueChangeEvent
      - onDemandCollectionFilesReadyEvent
      - onDemandCollectionFilesPreparationErrorEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF628_Performance/blob/main/TMF628-Performance-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF628
      apiSDO: not_defined
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PerformanceThreshold/hub
      implementation: /{{.Release.Name}}-PerformanceThreshold
      name: PerformanceThresholdManagement
      port: 80
      resources:
      - thresholdCreateNotification
      - thresholdChangeNotification
      - thresholdRuleCreateNotification
      - thresholdRuleChangeNotification
      - thresholdJobCreateNotification
      - thresholdJobChangedNotification
      - thresholdJobSuspendedNotification
      - thresholdJobResumedNotification
      specification:
      - url: https://github.com/tmforum-apis/TMF628_Performance/blob/main/TMF649-PerformanceThreshold-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF628
      apiSDO: not_defined
    subscribedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/hub
      implementation: /{{.Release.Name}}-ResourceCatalog
      name: ResourceCatalogManagement
      port: 80
      resources:
      - ResourceSpecificationChangeEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF634_ResourceCatalog/blob/master/TMF634-ResourceCatalog-v4.1.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF634
      apiSDO: not_defined
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/hub
      implementation: /{{.Release.Name}}-ResourceInventory
      name: ResourceInventoryManagement
      port: 80
      resources:
      - ResourceCreateEvent
      - ResourceAttributeValueChangeEvent
      - ResourceStateChangeEvent
      - ResourceDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF639_ResourceInventory/blob/master/TMF639-ResourceInventory-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF639
      apiSDO: not_defined
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/hub
      implementation: /{{.Release.Name}}-GeographicAddressManagement
      name: GeographicAddressManagement
      port: 80
      resources:
      - geographicAddressValidationStateChange
      specification:
      - url: https://github.com/tmforum-apis/TMF673_GeographicAddress/blob/master/TMF673-GeographicAddress-v4.0.1.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF673
      apiSDO: not_defined
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF701
      apiSDO: not_defined
