apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF620
      name: product-catalog-management-api
      apiSDO: tmForum
      required: true
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF620_Product_Catalog/5.0.0/swagger/TMF620-Product_Catalog_Management-v5.0.0.oas.yaml
        resources:
        - productSpecification:
          - GET
          - GET /id
      - version: v4.1.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF620_Product_Catalog/4.1.0/swagger/TMF620_Product_Catalog_Management_API_v4.1.0_swagger.json
        resources:
        - productSpecification:
          - GET
          - GET /id
    - id: TMF637
      name: product-inventory-management-api
      apiSDO: tmForum
      required: true
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF637_Product_Inventory/5.0.0/swagger/TMF637-ProductInventory-v5.0.0.oas.yaml
        resources:
        - product:
          - GET
          - GET /id
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF637_Product_Inventory/4.0.0/swagger/TMF637_Product_Inventory_Management_API_v4.0.0_swagger.json
        resources:
        - product:
          - GET
          - GET /id
    - id: TMF632
      name: party-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/5.0.0/swagger/TMF632-Party_Management-v5.0.0.oas.yaml
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
    - id: TMF669
      name: party-role-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/5.0.0/swagger/TMF669-Party_Role_Management-v5.0.0.oas.yaml
        resources:
        - partyRole:
          - GET
          - GET /id
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        resources:
        - partyRole:
          - GET
          - GET /id
    - id: TMF653
      name: service-test-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.2.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF653_Service_Test/4.2.0/swagger/TMF653_Service_Test_Management_API_v4.2.0_swagger.json
        resources:
        - serviceTestSpecification:
          - GET
          - GET /id
        - serviceTest:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
    - id: TMF638
      name: service-inventory-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF638_Service_Inventory/5.0.0/swagger/TMF638-Service_Inventory_Management-v5.0.0.oas.yaml
        resources:
        - service:
          - GET
          - GET /id
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF638_Service_Inventory/4.0.0/swagger/TMF638_Service_Inventory_Management_API_v4.0.0_swagger.json
        resources:
        - service:
          - GET
          - GET /id
    - id: TMF724
      name: incident-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF724_Incident/4.0.0/swagger/TMF724_Incident_Management_API_v4.0.0_swagger.json
        resources:
        - incident:
          - GET
          - GET /id
    - id: TMF701
      name: process-flow-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.1.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        resources:
        - processFlow:
          - GET
          - GET /id
          - POST
          - PATCH
        - taskFlow:
          - GET
          - GET /id
          - POST
          - PATCH
    exposedAPIs:
    - id: TMF769
      name: product-test-api
      apiSDO: tmForum
      required: true
      specification:
      - version: v5.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF769_Product_Test/5.0.0/swagger/TMF769-Product_Test-v5.0.0.oas.yaml
        resources:
        - productTestSpecification:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
        - productTest:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
        path: not_defined
        developerUI: not_defined
        implementation: not_defined
        port: 8080
    - id: TMF701
      name: process-flow-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.1.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        resources:
        - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
        - taskFlow:
          - PATCH
          - GET
          - GET /id
        path: not_defined
        developerUI: not_defined
        implementation: not_defined
        port: 8080
  componentMetadata:
    id: TMFC054
    name: ProductTestManagement
    version: 1.1.0
    description: Product Test Management component is responsible for product test
      specification for each Product Specification, and identification of the possible
      tests to be launched automatically by the delivery or assurance processes, or
      manually by the customer or user or by a CSR, to test that a product is functioning
      correctly. It utilizes tests available at the service specification level (or
      resource specification level for a tangible product). Product Test Management
      owns end-to-end execution and reporting of product tests according to the context
      and/or the actor.
    publicationDate: '2026-06-02'
    status: preview
    functionalBlock: CoreCommerce
    owners:
    - name: Redacted
      email: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.2.1.5|Product_Test_Strategy|v25.0
    - 1.2.4.9|Manage_Product_Test|v25.0
    - 1.2.1|Product_Portfolio_Strategy_Management|v25.0
    - 1.2.4|Product_Support_Management|v25.0
    functionalFrameworkFunctions:
    - 1073|Product_Test_Specification_Design|v26.0
    - 1074|Product_Test_Configuration_Design|v26.0
    - 1075|Product_Test_Restitution_Design|v26.0
    - 1130|Product_Test_Authorization_Check|v26.0
    - 1131|Product_Test_Execution|v26.0
    - 1132|Product_Test_Reporting|v26.0
    SIDs:
    - Product_Domain|Product_Test_ABE|v25.0
  managementFunction:
    exposedAPIs:
    - name: metrics
      id: exposedAPI_id
      apiSDO: not_defined
      required: false
      specification:
      - version: v4.0.0
        url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        apiType: prometheus
        implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
        port: 4000
        resources: []
        developerUI: exposedAPI_developerUI
    dependentAPIs: []
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - id: TMF669
      name: partyrole
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        resources: []
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
        implementation: '{{.Release.Name}}-partyroleapi'
        port: 8080
    - id: TMF672
      name: user-role-permission-management-api
      apiSDO: tmForum
      required: false
      specification:
      - version: v4.0.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/4.0.0/swagger/TMF672_User_Role_Permission_Management_API_v4.0.0_swagger.json
        resources: []
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v4/docs
        implementation: '{{.Release.Name}}-userrolepermissionapi'
        port: 8080
      - version: v5.1.0
        apiType: openapi
        url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/5.1.0/swagger/TMF672-User_Role_Permission_Management_API-v5.1.0.oas.yaml
        resources: []
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v5
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/userRolePermissionManagement/v5/docs
        implementation: '{{.Release.Name}}-userrolepermissionapi'
        port: 8080
    dependentAPIs: []
  eventNotification:
    publishedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productTestManagement/hub
      implementation: /{{.Release.Name}}-productTestManagement
      name: productTestManagement
      port: 80
      resources:
      - ProductTestSpecificationCreateEvent
      - ProductTestSpecificationDeleteEvent
      - ProductTestSpecificationAttributeValueChangeEvent
      - ProductTestSpecificationStateChangeEvent
      - ProductTestCreateEvent
      - ProductTestAttributeValueChangeEvent
      - ProductTestStateChangeEvent
      specification: ''
      apiType: openapi
      id: unknown
      apiSDO: not_defined
    subscribedEvents:
    - implementation: /{{.Release.Name}}-productCatalogManagement
      name: productCatalogManagement
      port: 80
      resources:
      - productSpecificationCreateEvent
      - productSpecificationDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.1.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF620
      apiSDO: not_defined
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productCatalogManagement/call-back
    - implementation: /{{.Release.Name}}-serviceTestManagement
      name: serviceTestManagement
      port: 80
      resources:
      - serviceTestSpecificationCreateEvent
      - serviceTestSpecificationAttributeValueChangeEvent
      - serviceTestSpecificationDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF653_ServiceTestManagement/blob/master/TMF653-ServiceTest-v4.1.0.swagger.json
        version: v4.0.0
      id: TMF653
      apiSDO: not_defined
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceTestManagement/call-back
    - implementation: /{{.Release.Name}}-Party
      name: Party
      port: 80
      resources:
      - individualDeleteEvent
      - organizationDeleteEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF632_Party/master/TMF632-Party-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF632
      apiSDO: not_defined
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/partyManagement/call-back
