apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF620
      apiType: openapi
      apiSDO: tmForum
      name: product-catalog-management-api
      required: true
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF620_Product_Catalog/4.1.0/swagger/TMF620_Product_Catalog_Management_API_v4.1.0_swagger.json
        version: v4.0.0
      resources:
      - productSpecification:
        - GET
        - GET /id
    - id: TMF637
      apiType: openapi
      apiSDO: tmForum
      name: product-inventory-management-api
      required: true
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF637_Product_Inventory/4.0.0/swagger/TMF637_Product_Inventory_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      resources:
      - product:
        - GET
        - GET /id
    - id: TMF632
      apiType: openapi
      apiSDO: tmForum
      name: party-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      resources:
      - individual:
        - GET
        - GET /id
      - organisation:
        - GET
        - GET /id
    - id: TMF669
      apiType: openapi
      apiSDO: tmForum
      name: party-role-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF669_Party_Role/4.1.0/swagger/TMF669_Party_Role_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
      resources:
      - partyRole:
        - GET
        - GET /id
    - id: TMF653
      apiType: openapi
      apiSDO: tmForum
      name: service-test-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF653_Service_Test/4.2.0/swagger/TMF653_Service_Test_Management_API_v4.2.0_swagger.json
        version: v4.0.0
      resources:
      - serviceTestSpecification:
        - GET
        - GET /id
      - serviceTest:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
    - id: TMF638
      apiType: openapi
      apiSDO: tmForum
      name: service-inventory-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF638_Service_Inventory/4.0.0/swagger/TMF638_Service_Inventory_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      resources:
      - service:
        - GET
        - GET /id
    - id: TMF724
      apiType: openapi
      apiSDO: tmForum
      name: incident-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF724_Incident/4.0.0/swagger/TMF724_Incident_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      resources:
      - incident:
        - GET
        - GET /id
    - id: TMF701
      apiType: openapi
      apiSDO: tmForum
      name: process-flow-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
      resources:
      - processFlow:
        - GET
        - GET /id
        - POST
        - PATCH
      - taskFlow:
        - GET
        - GET /id
        - POST
        - PATCH
    exposedAPIs:
    - id: TMF769
      apiType: openapi
      apiSDO: tmForum
      name: product-test-api
      required: true
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF769_Product_Test/5.0.0/swagger/TMF769-Product_Test-v5.0.0.oas.yaml
        version: v5.0.0
      path: not_defined
      developerUI: not_defined
      implementation: not_defined
      port: 8080
      resources:
      - productTestSpecification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - productTest:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
    - id: TMF701
      apiType: openapi
      apiSDO: tmForum
      name: process-flow-management-api
      required: false
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
        version: v4.0.0
      path: not_defined
      developerUI: not_defined
      implementation: not_defined
      port: 8080
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
  componentMetadata:
    id: TMFC054
    name: ProductTestManagement
    version: 1.0.0
    description: Product Test Management component is responsible for product test
      specification for each Product Specification, and identification of the possible
      tests to be launched automatically by the delivery or assurance processes, or
      manually by the customer or user or by a CSR, to test that a product is functioning
      correctly. It utilizes tests available at the service specification level (or
      resource specification level for a tangible product). Product Test Management
      owns end-to-end execution and reporting of product tests according to the context
      and/or the actor.
    publicationDate: 2025-02-25
    status: specified
    functionalBlock: CoreCommerce
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs: []
    functionalFrameworkFunctions: []
    SIDs:
    - Product_Domain|Product_Test_ABE|v25.0
  managementFunction:
    exposedAPIs:
    - name: metrics
      apiType: prometheus
      apiSDO: not_defined
      specification:
      - url: '{{.Release.Name}}-{{.Values.component.name}}-sm'
        version: v4.0.0
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
      id: exposedAPI_id
      version: exposedAPI_version
      resources: []
      required: false
      developerUI: exposedAPI_developerUI
    dependentAPIs:
    - name: dependentAPI_name
      id: dependentAPI_id
      version: dependentAPI_version
      apiType: dependentAPI_apiType
      apiSDO: dependentAPI_apiSDO
      specification:
      - url: dependentAPI_spec
        version: dependentAPI_version
      resources: []
      required: false
  securityFunction:
    canvasSystemRole: '{{ .Values.security.controllerRole }}'
    secretsManagement:
      type: sideCar
      sideCar:
        port: 8080
      podSelector:
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
    exposedAPIs:
    - id: TMF669
      apiType: openapi
      apiSDO: not_defined
      name: party-role-management-api
      required: true
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        version: v4.0.0
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      implementation: '{{.Release.Name}}-partyroleapi'
      port: 8080
      resources: []
    dependentAPIs: []
  eventNotification:
    publishedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productTestManagement/hub
      implementation: /{{.Release.Name}}-productTestManagement
      name: productTestManagement
      port: 80
      resources:
      - ProductTestSpecificationCreateEvent
      - ProductTestSpecificationDeleteEvent
      - ProductTestSpecificationAttributeValueChangeEvent
      - ProductTestSpecificationStateChangeEvent
      - ProductTestCreateEvent
      - ProductTestAttributeValueChangeEvent
      - ProductTestStateChangeEvent
      specification: ''
      apiType: openapi
      id: null
      apiSDO: not_defined
    subscribedEvents:
    - implementation: /{{.Release.Name}}-productCatalogManagement
      name: productCatalogManagement
      port: 80
      resources:
      - productSpecificationCreateEvent
      - productSpecificationDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.1.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF620
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productCatalogManagement/call-back
      apiSDO: not_defined
    - implementation: /{{.Release.Name}}-serviceTestManagement
      name: serviceTestManagement
      port: 80
      resources:
      - serviceTestSpecificationCreateEvent
      - serviceTestSpecificationAttributeValueChangeEvent
      - serviceTestSpecificationDeleteEvent
      specification:
      - url: https://github.com/tmforum-apis/TMF653_ServiceTestManagement/blob/master/TMF653-ServiceTest-v4.1.0.swagger.json
        version: v4.0.0
      id: TMF653
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceTestManagement/call-back
      apiSDO: not_defined
    - implementation: /{{.Release.Name}}-Party
      name: Party
      port: 80
      resources:
      - individualDeleteEvent
      - organizationDeleteEvent
      specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF632_Party/master/TMF632-Party-v4.0.0.swagger.json
        version: v4.0.0
      apiType: openapi
      id: TMF632
      callback: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/partyManagement/call-back
      apiSDO: not_defined
