apiVersion: oda.tmforum.org/v1beta1
kind: component
metadata:
  name: TMFC027-productconfigurator
  labels:
    oda.tmforum.org/componentName: TMFC027-productconfigurator
    oda.tmforum.org/funtionalBlockName: CoreCommerceManagement
spec:
  type: TMFC027-productconfigurator
  version: 1.1.0
  description: >-
    product configurator ODA-Component specification, from Open-API
    reference implementation.
  maintainers:
    - name: Matteo Destino
      email: matteo.destino@accenture.com
      owners: null
    - name: Matteo Destino
      email: matteo.destino@accenture.com
coreFunction:
  exposedAPIs:
    - name: ProductOfferingQualificationManagement
      id: TMF679
      isRequired: 'yes'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF679_ProductOfferingQualificationManagement/master/TMF679-ProductOfferingQualificationManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-pdtquali'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOfferingQualificationManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOfferingQualificationManagement/v4/docs
      port: 8080
      resources:
        - ProductOfferingQualification:
            - GET
            - GET/id
            - POST
            - PATCH/id
            - DELETE/id
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: 'no'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlowManagement/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-procmngttapi'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
      port: 8080
      resources:
        - processFlow:
            - GET
            - GET/id
            - POST
            - DELETE/id
        - taskFlow:
            - GET
            - GET/id
            - PATCH/id
    - name: Event
      id: TMF688
      isRequired: not
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-PromotionManagement'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      port: 8080
      resources:
        - event:
            - GET
            - GET /id
            - POST
            - PATCH
            - DELETE
  dependantAPIs:
    - name: SalesQuoteManagement
      id: TMF648
      isRequired: 'yes'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF648_SalesQuoteManagement/master/TMF648-SalesQuoteManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - quote:
            - GET
            - GET/id
    - name: ShoppingCartManagement
      id: TMF663
      isRequired: 'yes'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF663-ShoppingCartManagement/blob/master/TMF663-ShoppingCartManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - shoppingCart:
            - GET
            - GET /id      
    - name: ProductInventoryManagement
      id: TMF663
      isRequired: 'yes'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF637-ProductInventoryManagement/blob/master/TMF637-ProductInventoryManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - product:
            - GET
            - GET /id            
    - name: ProductCatalogManagement
      id: TMF62o
      isRequired: 'yes'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF620-ProductCatalogManagement/blob/master/TMF620-ProductCatalogManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - catalog:
            - GET
            - GET /id
        - productOffering:
            - GET
            - GET /id
        - productOfferingPrice:
            - GET
            - GET /id   
        - productSpecification:
            - GET
            - GET /id 
    - name: ServiceQualificationManagement
      id: TMF645
      isRequired: 'yes'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF645-ServiceQualificationManagement/blob/master/TMF645-ServiceQualificationManagement-v4.0.0.swagger.json
      apitype: openapi
      resources: 
        - checkServiceQualification:
            - GET
            - GET /id            
    - name: ProductOrdering
      id: TMF622
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF622-ProductOrdering/blob/master/TMF622-ProductOrdering-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - productOrder:
            - GET
            - GET /id            
    - name: StockManagement
      id: TMF687
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF687-StockManagement/blob/master/TMF687-StockManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - productStock:
            - GET
            - GET /id           
    - name: SalesManagement
      id: TMF699
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF699-SalesManagement/blob/master/TMF699-SalesManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - sales:
            - GET
            - GET /id           
    - name: PartyManagement
      id: TMF632
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF632-PartyManagement/blob/master/TMF632-PartyManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - individual:
            - GET
            - GET /id  
        - organization:
            - GET
            - GET /id            
    - name: AgreementManagement
      id: TMF651
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF651-AgreementManagement/blob/master/TMF651-AgreementManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - agreement:
            - GET
            - GET /id            
    - name: AppointmentManagement
      id: TMF645
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF645-AppointmentManagement/blob/master/TMF645-AppointmentManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - appointment:
            - GET
            - GET /id            
    - name: AccountManagement
      id: TMF666
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF666-AccountManagement/blob/master/TMF666-AccountManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - partyAccount:
            - GET
            - GET /id             
    - name: ServiceInventoryManagement
      id: TMF638
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF638-ServiceInventoryManagement/blob/master/TMF638-ServiceInventoryManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - service:
            - GET
            - GET /id             
    - name: ResourceInventoryManagement
      id: TMF639
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF639-ResourceInventoryManagement/blob/master/TMF639-ResourceInventoryManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - resource:
            - GET
            - GET /id
    - name: PartyRoleManagement
      id: TMF669
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - partyRole:
            - GET
            - GET /id
    - name: UserRolesandPermissions
      id: TMF672
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF672-UserRolesandPermissions/blob/master/TMF672-UserRolesandPermissions-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - permission:
            - GET
            - GET /id
        - userRole:
            - GET
            - GET /id
    - name: RiskManagement
      id: TMF696
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF696-RiskManagement/blob/master/TMF696-RiskManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - partyRoleRiskAssessment:
            - GET
            - GET /id
        - productOfferingRiskAssessment:
            - GET
            - GET /id
    - name: GeographicAddressManagement
      id: TMF673
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF673-GeographicAddressManagement/blob/master/TMF673-GeographicAddressManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - GeographicAddress:
            - GET
            - GET /id
    - name: GeographicSiteManagement
      id: TMF674
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF674-GeographicSiteManagement/blob/master/TMF674-GeographicSiteManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - GeographicSite:
            - GET
            - GET /id
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: 'no'
      version: 4
      specification: >-
        ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - processFlow:
            - POST
            - GET
            - GET /id
            - DELETE
        - taskFlow:
            - PATCH
            - GET
            - GET /id
    - name: Event
      id: TMF688
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - event:
            - GET
            - GET /id
  publishedEvents:
    - name: ProductOfferingQualification
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF679-ProductOfferingQualification/master/TMF679-ProductOfferingQualification-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-pdtquali'
      apitype: openapi
      port: 80
      resources:
        ProductOfferingQualification:
          - ProductOfferingQualificationCreateEvent
          - ProductOfferingQualificationAttributeValueChangeEvent
          - ProductOfferingQualificationStateChangeEvent
          - ProductOfferingQualificationDeleteEvent
          - ProductOfferingQualificationInformationRequiredEvent
  subscribedEvents:
    - name: ProductCatalogManagement
      specification: >-
        https://github.com/tmforum-apis/TMF622-ProductCatalogManagement/blob/master/TMF622-ProductCatalogManagement-v4.0.0.swagger.json
      apitype: openapi
      port: 80
      resources:
        ProductCatalogManagement:
          - CatalogCreateEvent
          - CatalogAttributeValueChangeEvent
          - CatalogStateChangeEvent
          - ProductOfferingCreateEvent
          - ProductOfferingAttributeValueChangeEvent
          - ProductOfferingStateChangeEvent
          - ProductOfferingDeleteEvent
          - ProductOfferingPriceCreateEvent
          - ProductOfferingPriceAttributeValueChangeEvent
          - ProductOfferingPriceStateChangeEvent
          - ProductOfferingPriceDeleteEvent  
          - ProductSpecificationCreateEvent
          - ProductSpecificationAttributeValueChangeEvent
          - ProductSpecificationStateChangeEvent
          - ProductSpecificationDeleteEvent  
management: []
reporting: []
security: []
