apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: '{{.Release.Name}}-{{.Values.component.name}}'
  name: '{{.Release.Name}}-process-flow-management-api'
spec:
  ports:
  - name: tcp-{{.Release.Name}}-process
    port: 8080
    targetPort: '{{.Release.Name}}-process'
  selector:
    impl: '{{.Release.Name}}-process-flow-management-api'
