apiVersion: oda.tmforum.org/v1beta3
kind: Component
metadata:
  labels:
    oda.tmforum.org/componentName: '{{.Release.Name}}-{{.Values.component.name}}'
  name: '{{.Release.Name}}-{{.Values.component.name}}'
spec:
  coreFunction:
    dependentAPIs:
    - apiType: openapi
      name: product-catalog-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF620_Product_Catalog/4.1.0/swagger/TMF620_Product_Catalog_Management_API_v4.1.0_swagger.json
    - apiType: openapi
      name: product-inventory-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF637_Product_Inventory/4.0.0/swagger/TMF637_Product_Inventory_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: product-offering-qualification-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF679_Product_Offering_Qualification/4.0.0/swagger/TMF679_Product_Offering_Qualification_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: service-qualification-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF645_Service_Qualification/4.0.0/swagger/TMF645_Service_Qualification_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: appointment-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF646_Appointment/4.0.0/swagger/TMF646_Appointment_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: geographic-address-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF673_Geographic_Address/4.0.0/swagger/TMF673_Geographic_Address_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: geographic-site-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF674_Geographic_Site/4.0.0/swagger/TMF674_Geographic_Site_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: stock-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF687_Stock/4.0.0/swagger/TMF687_Stock_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: party-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: party-role-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: account-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF666_Account/4.0.0/swagger/TMF666_Account_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: payment-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF676_Payment/4.0.0/swagger/TMF676_Payment_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: party-interaction-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Historic/TMF683_Party_Interaction/4.0.0/swagger/TMF683-PartyInteraction-4.0.0.swagger.json
    - apiType: openapi
      name: service-inventory-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF638_Service_Inventory/4.0.0/swagger/TMF638_Service_Inventory_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: resource-inventory-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF639_Resource_Inventory/4.0.0/swagger/TMF639_Resource_Inventory_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      name: process-flow-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
    - apiType: openapi
      name: product-configuration-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF760_Product_Configuration/5.0.0/swagger/TMF760-ProductConfiguration-v5.0.0.oas.yaml
    - apiType: openapi
      name: agreement-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF651_Agreement/4.0.0/swagger/TMF651_Agreement_Management_API_v4.0.0_swagger.json
    exposedAPIs:
    - apiType: openapi
      implementation: '{{.Release.Name}}-product-ordering-management-api'
      name: product-ordering-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/productOrderingManagement/v4/
      port: 8080
      specification:
      - https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF622_Product_Ordering/4.0.0/swagger/TMF622_Product_Ordering_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      implementation: '{{.Release.Name}}-quote-management-api'
      name: quote-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/quoteManagement/v4/
      port: 8080
      specification:
      - https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF648_Quote/4.0.0/swagger/TMF648_Quote_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      implementation: '{{.Release.Name}}-shopping-cart-management-api'
      name: shopping-cart-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/shoppingCart/v4/
      port: 8080
      specification:
      - https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF663_Shopping_Cart/4.0.0/swagger/TMF663_Shopping_Cart_Management_API_v4.0.0_swagger.json
    - apiType: openapi
      implementation: '{{.Release.Name}}-process-flow-management-api'
      name: process-flow-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/processFlowManagement/v4/
      port: 8080
      specification:
      - https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Beta/TMF701_Process_Flow/4.1.0/swagger/TMF701_Process_Flow_Management_API_v4.1.0_beta_swagger.json
  description: Addresses the means of capturing what a customer wants to order, based
    on the CSP Product Catalog. This component permits to choose the configuration
    of the product offerings and products desired, to provide a quote, to check the
    eligibility of the customer order, and to complete it with information needed
    such as the related parties or associated the billing account and the delivery
    appointment if needed. This component is globally in charge of these quote management,
    order capture and validation steps, using dedicated components (e.g., Offering
    Configurator, Service Qualification, Party Mgt) when needed. After the delivery
    of the customer product order items, this component is also in charge of the commercial
    closure of the order. It includes update of the Product Inventory (status and
    starting/end date of tariffs and discounts) and potential commercial rules control
    (e.g. receipt of the contract document signed by the customer)
  eventNotification:
    publishedEvents:
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOrder/hub
      id: TMF622
      implementation: /{{.Release.Name}}-ProductOrderEvent
      name: ProductOrder
      port: 80
      resources:
      - productOrderStateChange
      - productOrderCreateEvent
      - productOrderAttributeValueChange
      - productOrderDelete
      - productOrderInformationRequired
      - cancelProductOrderCreateEvent
      - cancelProductOrderStateChange
      - cancelProductOrderInformationRequired
      specification: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/master/TMF622-ProductOrder-v4.0.0.swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Quote/hub
      id: TMF648
      implementation: /{{.Release.Name}}-QuoteEvent
      name: Quote
      port: 80
      resources:
      - quoteStateChange
      - quoteCreateEvent
      - quoteAttributeValueChange
      - quoteDelete
      - quoteInformationRequired
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF648_QuoteManagement/master/TMF648-QuoteManagement-v4.0.0.swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ShoppingCart/hub
      id: TMF663
      implementation: /{{.Release.Name}}-ShoppingCartEvent
      name: ShoppingCart
      port: 80
      resources:
      - shoppingCartCreateEvent
      - shoppingCartAttributeValueChange
      - shoppingCartDelete
      specification: https://github.com/tmforum-apis/TMF663_ShoppingCart/blob/master/TMF663-ShoppingCart-v4.0.0.swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      id: TMF701
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
    subscribedEvents:
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOfferingQualification/call-back
      id: TMF679
      implementation: /{{.Release.Name}}-ProductOfferingQualificationEvent
      name: ProductOfferingQualification
      port: 80
      resources:
      - productOfferingQualificationStateChangeEvent
      specification: https://github.com/tmforum-apis/TMF679_ProductOfferingQualification/blob/master/TMF679-ProductOfferingQualification-v4.0.0.swagger.json
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/call-back
      id: TMF645
      implementation: /{{.Release.Name}}-ServiceQualificationEvent
      name: ServiceQualification
      port: 80
      resources:
      - checkServiceQualificationStateChangeEvent
      - queryServiceQualificationStateChangeEvent
      specification: https://github.com/tmforum-apis/TMF645_ServiceQualification/blob/master/TMF645-ServiceQualification-v4.0.0.swagger.json
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/call-back
      id: TMF673
      implementation: /{{.Release.Name}}-GeographicAddressManagementEvent
      name: GeographicAddressManagement
      port: 80
      resources:
      - geographicAddressValidationStateChange
      specification: https://github.com/tmforum-apis/TMF673_GeographicAddress/blob/master/TMF673-GeographicAddress-v4.0.1.swagger.json
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PaymentManagementEvent/call-back
      id: TMF676
      implementation: /{{.Release.Name}}-PaymentManagementEvent
      name: PaymentManagement
      port: 80
      resources:
      - paymentCreate
      - paymentStateChange
      specification: https://github.com/tmforum-apis/TMF676_PaymentManagement/blob/master/TMF676-Payment-v4.0.0.swagger.json
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceReservationEvent/call-back
      id: TMF716
      implementation: /{{.Release.Name}}-ResourceReservationEvent
      name: ResourceReservation
      port: 80
      resources:
      - resourceReservationCreateEvent
      - resourceReservationAttributeValueChangeEvent
      - resourceReservationDeleteEvent
      - resourceReservationStateChangeEvent
      - resourceReservationInformationRequiredEvent
      - cancelResourceReservationCreateEvent
      - cancelResourceReservationStateChangeEvent
      - cancelResourceReservationInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF716_ResourceReservation/blob/master/TMF716-ResourceReservation-v4.1.0.swagger.json
  functionalBlock: CoreCommerce
  id: TMFC002
  maintainers:
  - email: components@tmforum.org
    name: Redacted
  name: ProductOrderCaptureAndValidation
  owners:
  - email: Redacted
    name: Redacted
  publicationDate: '{{.Values.component.publicationDate}}'
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - apiType: openapi
      implementation: '{{.Release.Name}}-partyrole-management-api'
      name: partyrole-management-api
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      specification:
      - https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
    secretsManagement:
      podSelector:
        name: '{{ .Values.secretsManagement.podSelector.name }}'
        namespace: '{{ .Values.secretsManagement.podSelector.namespace }}'
        serviceaccount: '{{ .Values.secretsManagement.podSelector.serviceaccount }}'
      sideCar:
        port: 8080
      type: sideCar
  status: specified
  version: 2.0.1
