apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-userrolepermapi
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: {{.Release.Name}}-userrolepermapi
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-{{.Values.component.name}}
        impl: {{.Release.Name}}-userrolepermapi
        version: {{.Values.userrolepermapi.versionLabel}}
    spec:
      containers:
      - name: {{.Release.Name}}-userrolepermapi
        image: {{.Values.userrolepermapi.image}}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name}}
        - name: COMPONENT_NAME
          value: {{.Release.Name}}-{{.Values.component.name}}
        - name: PORT
          value: "8672"
        - name: OTL_EXPORTER_CONSOLE_ENABLED
          value: "{{.Values.userrolepermapi.otlp.console.enabled}}"
        - name: OTL_EXPORTER_TRACE_PROTO_ENABLED
          value: "{{.Values.userrolepermapi.otlp.protobuffCollector.enabled}}"
        - name: OTL_EXPORTER_TRACE_PROTO_COLLECTOR_URL
          value: {{.Values.userrolepermapi.otlp.protobuffCollector.url}}
        - name: MONGODB_HOST
          value: {{.Release.Name}}-mongodb
        - name: MONGODB_PORT
          value: "{{.Values.mongodb.port}}"
        - name: MONGODB_DATABASE
          value: {{.Values.mongodb.database}}
        - name: NODE_ENV
          value: production
        - name: CANVAS_INFO_HOST_PORT
          value: "{{.Values.canvasinfo.host}}"
        - name: CANVAS_INFO_BASEPATH
          value: "{{.Values.canvasinfo.basepath}}"
        ports:
        - containerPort: 8672
        startupProbe:
          httpGet:
            path: /{{.Release.Name}}-{{.Values.component.name}}/rolesAndPermissions/v4/permission
            port: 8672
          initialDelaySeconds: 10
          failureThreshold: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /{{.Release.Name}}-{{.Values.component.name}}/rolesAndPermissions/v4/permission
            port: 8672
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
