apiVersion: oda.tmforum.org/v1beta2
coreFunction:
  dependantAPIs:
  - apitype: openapi
    id: TMF666
    isRequired: true
    name: AccountManagement
    resources:
    - BillingAccount:
      - GET
      - GET /id
      - POST
      - PATCH /id
      - DELETE /id
    - BillingCycleSpecification:
      - GET
      - GET /id
      - POST
      - PATCH /id
      - DELETE /id
    - BillFormat:
      - GET
      - GET /id
      - POST
      - PATCH /id
      - DELETE /id
    - BillPresentationMedia:
      - GET
      - GET /id
      - POST
      - PATCH /id
      - DELETE /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF666_AccountManagement/master/TMF666-AccountManagement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF632
    isRequired: true
    name: PartyManagement
    resources:
    - individual:
      - GET
      - GET /id
    - organization:
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF637
    isRequired: false
    name: Productinventory
    port: 8080
    resources:
    - product:
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF637_ProductInventory/master/TMF637-ProductInventory-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF669
    isRequired: true
    name: PartyRoleManagement
    resources:
    - PartyRole:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF672
    isRequired: true
    name: UserRolePermissionManagement
    resources:
    - permission:
      - GET
      - GET /id
    - userRole:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF672-UserRolePermission/blob/master/TMF672-UserRolePermission-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF701
    isRequired: false
    name: ProcessFlowManagement
    resources:
    - processFlow:
      - POST
      - GET
      - GET /id
      - PATCH
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF688
    isRequired: false
    name: Event
    resources:
    - event:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF635
    isRequired: true
    name: UsageManagement
    resources:
    - usage:
      - GET
      - GET /id
    - usageSpecification:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF635_UsageManagement/blob/master/TMF635-UsageManagement-v4.0.0.swagger.json
    version: 4.0
  exposedAPIs:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/customerBillManagement/v4/docs
    id: TMF678
    implementation: /{{.Release.Name}}-CustomerBill
    isRequired: true
    name: CustomerBill
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/customerBillManagement/v4
    port: 8080
    resources:
    - appliedCustomerBillingRate:
      - GET
      - GET /id
    specification: 'https://github.com/tmforum-apis/TMF678_CustomerBill/blob/master/TMF678-CustomerBill-v4.0.0.swagger.json#L33 '
    version: 4.0
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
    id: TMF701
    implementation: /{{.Release.Name}}-procmngttapi
    isRequired: false
    name: ProcessFlowManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
    port: 8080
    resources:
    - processFlow:
      - GET
      - GET /id
      - POST
      - DELETE /id
    - taskFlow:
      - GET
      - GET /id
      - PATCH /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlowManagement/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4/docs
    id: TMF688
    implementation: /{{.Release.Name}}-Event
    isRequired: false
    name: Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4
    port: 8080
    resources:
    - listener:
      - POST
    - hub:
      - POST
      - DELETE /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF688-Event/master/TMF688-Event-v4.0.0.swagger.json
    version: 4.0
  publishedEvents:
    - apiType: OpenAPI
      CustomerBill:
      name: CustomerBill
      port: 80
      resources:
      - CustomerBillCreateEvent
      - CustomerBillOnDemandCreateEvent
      - CustomerBillOnDemandStateChangeEvent
      - CustomerBillStateChangeEven
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF678_CustomerBill/master/TMF678-CustomerBill-v4.0.0.swagger.json
  subscribedEvents:
  - apitype: openapi
    name: PartyRoleManagement
    port: 80
    resources:
    - partyRoleCreateEvent
    - partyRoleAttributeValueChangeEvent
    - partyRoleStateChangeEvent
    - partyRoleDeleteEvent
    specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
  - apitype: openapi
    name: UserRolePermissionManagement
    port: 80
    resources:
    - permissionCreateEvent
    - permissionAttributeValueChangeEvent
    - permissionStateChangeEventac
    - permissionDeleteEvent
    - userRoleCreateEvent
    - userRoleAttributeValueChangeEvent
    - userRoleStateChangeEvent
    - userRoleDeleteEvent
    specification: https://github.com/tmforum-apis/TMF672-UserRolePermission/blob/master/TMF672-UserRoleandPermission-v4.0.0.swagger.json
  - name: usageManagement
    port: 80
    resources:
    - UsageCreateEvent
    - UsageAttributeValueChangeEvent
    - UsageDeleteEvent
    - UsageStateChangeEvent
    - UsageSpecificationCreateEvent
    - UsageSpecificationAttributeValueChangeEvent
    - UsageSpecificationDeleteEvent
    specification: https://github.com/tmforum-apis/TMF635_UsageManagement/blob/master/TMF635-UsageManagement-v4.0.0.swagger.json
kind: component
managementFunction: []
metadata:
  name: components.oda.tmforum.org
reportingFunction: []
securityFunction: []
spec:
  description: Bill generation mgmt. manage the party invoice management. It addresses
    the invoice formatting, presentation and dispatching to the proper means of communication.
  functionalBlock: PartyManagement
  id: TMFC031
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  managementFunction:
    exposedAPIs:
    - apitype: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  name: BillCalculation
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  publicationDate: 2023-11-21
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      id: TMF669
      implementation: '{{.Release.Name}}-partyroleapi'
      name: partyrole
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
  status: specified
  version: 1.0.0
